const fs = require('fs');
const file = 'src/data/templates.json';
const data = JSON.parse(fs.readFileSync(file, 'utf-8'));

const newTemplates = [
  {
    slug: 'cold-email-for-saas-startup-founders',
    title: 'Cold Email Templates for SaaS Startup Founders',
    description: 'Connect with busy SaaS startup founders using these highly personalized, high-converting cold outreach email templates.',
    intro: 'Pitching a SaaS startup founder is notoriously difficult. Founders are fiercely protective of their time, aggressively filter their inboxes, and possess a sixth sense for generic, automated sales pitches. To successfully capture a founder’s attention, your cold email must be ruthlessly concise, highly relevant to their immediate business goals, and immediately establish your credibility.\n\nThe most fatal mistake when emailing a startup founder is focusing on your own product rather than their specific problem. A winning cold email to a founder immediately proves that you understand their current stage of growth. Are they post-Seed and trying to scale outbound sales? Are they struggling with early-stage user retention? Identify a highly specific, painful bottleneck they are likely experiencing and position your solution as the definitive answer. Keep the email under 100 words. Founders respect brevity and directness over lengthy corporate prose.\n\nUse the templates below to structure your founder outreach. Whether you are pitching a new piece of infrastructure software, an agency service, or requesting a partnership, these templates prioritize respect for the founder’s time while maximizing your chances of a positive reply.',
    templates: [
      "Subject: Scaling [Company Name]'s outbound infrastructure\n\nHi [Founder Name],\n\nI’ve been following [Company Name] since your recent Seed round announcement—congratulations on the milestone!\n\nAs you begin to aggressively scale your sales team this quarter, you will likely hit a massive bottleneck regarding [Specific Problem, e.g., email deliverability and domain reputation]. \n\nMy team at [Your Company] built the exact infrastructure that helped [Similar SaaS Company] solve this, allowing them to scale from 2 to 10 SDRs without hitting spam folders.\n\nAre you open to a brief 10-minute chat next week to see if we can save your team from the same growing pains?\n\nBest,\n[Your Name]",
      "Subject: Quick question about [Company Name]'s recent launch\n\nHi [Founder Name],\n\nI loved the recent Product Hunt launch for [Feature/Product]. It’s a brilliant solution to a problem I actually deal with daily.\n\nI’m reaching out because I noticed that while your core product is phenomenal, the [Specific Area, e.g., user onboarding flow] seems to be causing a slight drop-off in free trial conversions.\n\nI run a specialized agency that helps SaaS founders increase trial-to-paid conversions. I actually recorded a brief 3-minute video showing two immediate tweaks you could make to [Company Name]’s onboarding to boost conversions by roughly 15%.\n\nWould you like me to send over the video link?\n\nCheers,\n[Your Name]",
      "Subject: Idea for [Company Name] + [Your Company] partnership\n\nHi [Founder Name],\n\nI’ll keep this brief. I am the founder of [Your Company], a platform that helps [Target Audience] achieve [Specific Goal].\n\nGiven the massive overlap between our user base and [Company Name]’s target market, I believe a co-marketing partnership or native integration could drive significant mutual pipeline for both of our startups this quarter.\n\nIf generating low-CAC leads is a priority for you right now, do you have 10 minutes to chat next Tuesday?\n\nBest regards,\n[Your Name]",
      "Subject: Your thoughts on [Industry Trend]?\n\nHi [Founder Name],\n\nI’m currently speaking with several leading founders in the [Industry] space regarding the recent shift toward [Specific Trend]. \n\nAs the CEO of [Company Name], your insights on how this will impact [Specific Niche] would be invaluable. I’m putting together a brief report and would love to feature a quote from you.\n\nWould you be open to answering 3 quick questions asynchronously via email? \n\nBest,\n[Your Name]",
      "Subject: Solving [Company Name]'s [Specific Issue] bottleneck\n\nHi [Founder Name],\n\nI know you are incredibly busy focused on scaling [Company Name], so I will be direct.\n\nWe provide [Service/Software] that specifically helps post-Series A SaaS companies automate their [Specific Process]. We recently helped [Competitor or Similar Company] reduce their [Cost/Time] by [X]% in under 30 days.\n\nIf this is a bottleneck your team is currently trying to solve, I’d love to show you a quick 5-minute demo.\n\nAre you available next Thursday afternoon?\n\nThanks,\n[Your Name]"
    ],
    tips: [
      "Keep it under 100 words. Founders scan emails on their phones between meetings.",
      "Reference a specific, recent company milestone (e.g., a funding round, a new product launch).",
      "Do not ask them 'Who is the best person to speak with?' A founder wants you to pitch them directly if it involves revenue or growth."
    ],
    faq: [
      { question: "Should I mention their competitors in the pitch?", answer: "Yes, strategically. Mentioning that you successfully helped a company similar to theirs (or a direct competitor) immediately builds credibility and FOMO." },
      { question: "What time should I email a founder?", answer: "Early mornings (7 AM - 8 AM) or late evenings (after 6 PM) often yield higher open rates as founders clear their inboxes outside of core meeting hours." },
      { question: "Is a Loom video effective for founders?", answer: "Extremely. A highly personalized, 2-minute Loom video audit proves you did genuine research and aren't just blasting an automated list." }
    ]
  },
  {
    slug: 'cold-email-for-demo-booking-saas',
    title: 'Cold Email Templates to Book SaaS Demos',
    description: 'Transform your outbound funnel. Book more qualified software demos with these highly effective SaaS cold email templates.',
    intro: 'Booking a software demo via cold email is the lifeblood of B2B SaaS sales. However, asking a busy professional to sacrifice 30 minutes of their day to watch a software presentation is a massive ask. If your cold email focuses entirely on listing your software\'s features rather than solving the prospect\'s urgent problems, your email will be deleted. To successfully book a demo, your email must sell the meeting, not the software.\n\nThe most effective demo-booking emails follow a strict framework: establish relevance immediately, agitate a specific pain point, introduce your software as the definitive solution, provide social proof, and end with a frictionless Call to Action (CTA). Do not send a bulleted list of ten different features; focus entirely on the one feature that solves their most painful daily headache. The CTA should be incredibly low-pressure. Instead of aggressively demanding a 45-minute demo, ask if they are open to a brief 10-minute introduction.\n\nUse the customized templates below to supercharge your SDR efforts. Whether you are targeting Enterprise accounts or SMBs, these templates are designed to pique curiosity, establish undeniable value, and seamlessly transition the prospect onto your calendar.',
    templates: [
      "Subject: Automating [Company Name]'s manual [Process Name] process\n\nHi [Name],\n\nI imagine your team at [Company Name] spends a massive amount of time manually handling [Specific Process/Task] every week.\n\nWe built [Your Software] specifically to eliminate this bottleneck. Our platform automates [Specific Pain Point], allowing teams like yours to save upwards of [X] hours per week and focus on high-value strategy.\n\nWe recently helped [Similar Company] completely automate their workflow, resulting in a [X]% increase in operational efficiency.\n\nAre you open to a brief 10-minute walkthrough next week to see how it works?\n\nBest,\n[Your Name]",
      "Subject: Quick question regarding your [Specific Software/Stack]\n\nHi [Name],\n\nI noticed that [Company Name] is currently using [Competitor Tool] to manage your [Specific Operations]. \n\nWhile [Competitor Tool] is great for early-stage teams, many [Industry] leaders find it severely lacking when it comes to [Specific Flaw/Missing Feature, e.g., advanced reporting].\n\n[Your Software] was built specifically to solve [Specific Flaw]. We offer robust, automated [Feature] right out of the box, which is why teams like [Client A] and [Client B] recently switched over to us.\n\nDo you have 10 minutes next Tuesday for a quick demo of how the reporting engine works?\n\nCheers,\n[Your Name]",
      "Subject: Idea to reduce [Specific Cost/Metric] at [Company Name]\n\nHi [Name],\n\nAs the [Title] at [Company Name], I know that reducing [Specific Metric, e.g., customer churn] is likely a massive priority for your team this quarter.\n\nMost teams try to solve this by [Common Ineffective Solution], which rarely scales. We approach it differently. [Your Software] utilizes [Unique Mechanism] to proactively identify [Pain Point] before it costs you revenue.\n\nIf driving down [Specific Metric] is on your radar right now, I’d love to show you a quick 10-minute demo of the platform.\n\nAre you free next Thursday morning?\n\nBest regards,\n[Your Name]",
      "Subject: [Company Name] + [Your Company]\n\nHi [Name],\n\nI’ll keep this incredibly brief. \n\nWe help companies like [Company Name] increase their [Core Metric] by [X]%. \n\nOur platform, [Your Software Name], plugs directly into your existing infrastructure to automate the tedious parts of [Specific Process].\n\nI’d love to earn 10 minutes of your time to show you a quick demo. If the platform isn’t a fit, I promise to never email you again.\n\nDoes next week work for a quick chat?\n\nBest,\n[Your Name]",
      "Subject: Following up with a quick 2-minute video\n\nHi [Name],\n\nSince I know finding time for a full demo is tough, I went ahead and recorded a highly customized, 2-minute walkthrough of how [Your Software] would look integrated specifically with [Company Name]’s currently workflow.\n\nYou can watch the quick demo video here: [Link to Loom/Video].\n\nIf you see the value in automating [Process], I’d love to schedule a formal 15-minute call to answer any of your technical questions.\n\nTalk soon,\n[Your Name]"
    ],
    tips: [
      "Sell the meeting, not the software. Your only goal is to pique enough curiosity to get them on a call.",
      "Ask for a 10 or 15-minute meeting. Asking for 30 or 60 minutes in a cold email is an immediate turn-off.",
      "Use strong social proof by name-dropping impressive clients who are in the exact same industry as the prospect."
    ],
    faq: [
      { question: "Should I include a calendar link in the first cold email?", answer: "Usually, no. Including links in the first cold email can harm deliverability. Ask a 'Yes/No' question first, and send the link when they reply." },
      { question: "What if they ask for pricing before booking a demo?", answer: "Provide a rough estimate or a starting price to respect their time, but reiterate that the custom demo will allow you to provide an exact, tailored quote." },
      { question: "Is it better to attach a PDF deck or do a live demo?", answer: "A live demo is infinitely better because it allows you to handle objections in real-time and tailor the presentation dynamically." }
    ]
  },
  {
    slug: 'cold-email-for-real-estate-investors',
    title: 'Cold Email Templates for Real Estate Investors',
    description: 'Find off-market deals and distressed properties with these proven cold outreach templates for real estate investors and wholesalers.',
    intro: 'In the highly competitive world of real estate investing, finding lucrative off-market deals requires aggressive, precise outreach. Distressed property owners, absentee landlords, and motivated sellers receive a constant barrage of junk mail and colorful postcards. To stand out and secure the deal, your cold email must be remarkably transparent, professional, and empathetic to their potential situation.\n\nA great real estate outreach email avoids sounding like a scam. Do not use overly aggressive sales language, all-caps, or promises of "Instant Cash." Instead, pitch yourself as a local, professional investor looking to simplify their life. State clearly how you found their property, affirm that you can close quickly with cash (bypassing the headache of traditional financing contingencies), and most importantly, offer to purchase it "as-is" without requiring any repairs or cleaning on their part. This alleviates the massive mental friction associated with selling a distressed asset.\n\nThe templates below are tailored for various real estate scenarios, including contacting out-of-state absentee owners, reaching out regarding a pre-foreclosure, or inquiring about a multi-family commercial asset. Customize them with the specific property address to prove you are a serious, local buyer.',
    templates: [
      "Subject: Inquiry regarding your property at [Property Address]\n\nHi [Owner's Name],\n\nMy name is [Your Name] and I am a local real estate investor here in [City/Area]. \n\nI am currently looking to purchase a few more investment properties in the [Neighborhood] area this month, and your property at [Property Address] immediately caught my eye.\n\nIf you have any interest in selling, I would love to make you a fair, all-cash offer. We purchase properties completely 'as-is'—meaning you won't have to make a single repair, clean the property, or pay any traditional realtor commissions.\n\nWe can close on your timeline, whether that is in 14 days or 3 months.\n\nAre you open to a brief 5-minute phone call this week to discuss a potential cash offer?\n\nBest regards,\n[Your Name]",
      "Subject: Buying [City] rentals — Cash offer for [Property Address]\n\nHi [Owner's Name],\n\nI noticed through public tax records that you currently own the rental property at [Property Address], but your primary mailing address is out of state.\n\nAs a landlord myself, I know how incredibly stressful managing out-of-state properties and dealing with tenant issues can become.\n\nIf you are tired of merely breaking even or dealing with the operational headaches, my investment group is actively buying multi-family properties in [City]. We can take the property off your hands quickly, with cash, and we will happily inherit any existing tenants so you don't have to deal with evictions.\n\nIf you are interested in exploring an off-market sale, please reply to this email or call me directly at [Your Number].\n\nThanks,\n[Your Name]",
      "Subject: Quick question about [Property Address]\n\nHi [Owner's Name],\n\nI’ll keep this very brief. I am a local investor heavily buying in the [Zip Code] area. \n\nI drove by your property at [Property Address] yesterday and I absolutely love the lot. \n\nIf you have ever considered selling, I can offer you a stress-free, all-cash transaction. No open houses, no bank appraisals falling through, and absolutely no repair costs on your end.\n\nDo you have 5 minutes for a quick chat sometime next week?\n\nBest,\n[Your Name]",
      "Subject: Interested in selling your commercial building at [Address]?\n\nHi [Owner's Name],\n\nMy investment firm is actively acquiring commercial and mixed-use assets in the [Neighborhood/City] submarket.\n\nGiven the current market dynamics, we are prepared to make highly competitive, non-contingent cash offers for properties that fit our criteria. Your building at [Property Address] perfectly aligns with our current Q3 acquisition goals.\n\nWe are principals, not brokers, so you would save completely on standard commission fees.\n\nWould you be open to a confidential conversation regarding the valuation of your asset?\n\nSincerely,\n[Your Name]",
      "Subject: Checking in regarding [Property Address]\n\nHi [Owner's Name],\n\nI reached out a few weeks ago regarding your property at [Property Address], but I know life gets busy.\n\nI am still actively buying in the area and my cash offer stands. If you have been considering offloading the property to free up capital without the headache of a traditional listing, I’d love to be the one to buy it.\n\nJust let me know if you are open to a quick 5-minute exploratory call.\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Always include the exact property address in the subject line. This guarantees high open rates.",
      "Emphasize the primary benefits: 'All Cash', 'As-Is', and 'No Realtor Commissions'.",
      "Ensure your email signature contains your full phone number, website, and physical business address to prove you are legitimate."
    ],
    faq: [
      { question: "Where do I find email addresses for property owners?", answer: "Investors use 'skip tracing' software (like PropStream or BatchLeads) to cross-reference public property tax records with consumer databases to find phone numbers and emails." },
      { question: "Is cold emailing property owners legal?", answer: "Yes, standard CAN-SPAM laws apply. Ensure you provide a clear way to opt-out, and do not use deceptive subject lines." },
      { question: "What if the property is already listed with an agent?", answer: "If it is actively listed on the MLS, you must legally submit your offer through their listing agent, not by cold emailing the seller directly." }
    ]
  },
  {
    slug: 'cold-email-for-b2b-lead-generation',
    title: 'High-Converting B2B Lead Generation Cold Emails',
    description: 'Fill your sales pipeline with qualified B2B leads using these proven, high-converting outbound lead generation email templates.',
    intro: 'Generic, mass-blasted B2B mass emails are dead. Today, decision-makers utilize aggressive spam filters and possess zero tolerance for automated templates that treat them like a number on a spreadsheet. To succeed in modern B2B lead generation, your outbound strategy must shift from purely volume-based approaches to highly targeted, hyper-personalized "spear phishing." A successful B2B cold email must immediately prove that you understand their specific industry constraints and offer a quantifiable, proven solution.\n\nThe framework for a perfect B2B lead generation email is: hook, customized observation, social proof, and a low-friction Call to Action. Begin by referencing a recent trigger event—a new round of funding, a recent C-suite hire, or an expansion into a new market. Next, highlight the specific operational pain point that typically accompanies that transition. Provide undeniable social proof by stating exactly how you solved that exact problem for a direct competitor or a similar-sized company in their space. Finally, ask for a brief 10-minute discovery call.\n\nImplement these B2B outbound templates to dramatically increase your positive reply rates. Tailor them for various sectors, from selling enterprise software to pitching high-ticket consulting services, ensuring your messaging resonates deeply with executive buyers.',
    templates: [
      "Subject: Ideas for scaling [Company Name]'s [Department]\n\nHi [Name],\n\nI noticed the recent news regarding [Company Name]’s expansion into the [New Market/Region]—congratulations to the team! \n\nTypically, when companies scale their [Specific Department] that quickly, they run into massive inefficiencies regarding [Specific Pain Point, e.g., manual data entry or compliance tracking].\n\nMy team at [Your Company] specializes in eliminating that exact bottleneck. We recently partnered with [Similar Company], helping them automate [Process], which resulted in a [X]% decrease in operational overhead within a month.\n\nAre you open to a brief 10-minute call next Tuesday to see if we can drive similar efficiencies for your new team?\n\nBest,\n[Your Name]",
      "Subject: Quick question about [Company Name]'s Q3 goals\n\nHi [Name],\n\nAs the [Title] at [Company Name], I imagine that hitting your aggressive Q3 targets for [Specific Goal, e.g., Lead Generation or Revenue] is currently top of mind.\n\nMost teams in your space rely heavily on [Ineffective Standard Practice], which often yields diminishing returns. We take a completely different approach. Our platform, [Your Product/Service], leverages [Unique Mechanism] to guarantee a [X]% improvement in [Metric].\n\nIf improving [Metric] is a priority this quarter, I’d love to share a quick case study on how we achieved this for [Competitor/Similar Brand].\n\nDo you have 10 minutes available next week?\n\nCheers,\n[Your Name]",
      "Subject: A quick resource for your team at [Company Name]\n\nHi [Name],\n\nI know you are incredibly busy, so I’ll be brief.\n\nI was doing some research on [Company Name]’s current strategy regarding [Specific Area], and I noticed an opportunity to optimize your [Specific Process].\n\nI actually put together a highly-customized, 1-page roadmap detailing exactly how you could implement [Solution] to save roughly [X] hours a week. There is absolutely no pitch attached; I just love what your company is building and wanted to share some value.\n\nWould you like me to send the roadmap over?\n\nBest regards,\n[Your Name]",
      "Subject: [Company Name] + [Your Company]\n\nHi [Name],\n\nI am reaching out because we help companies similar to [Company Name] solve [Specific Problem].\n\nFor context, we recently helped [Impressive Client] overhaul their [Process], resulting in a [Huge Tangible Result, e.g., $100k savings or 50% faster closing time].\n\nOur solution integrates directly into your existing workflow without requiring a massive IT overhaul. \n\nIf this sounds like something that could benefit your team this year, I’d love to schedule a brief introductory call.\n\nAre you available next Thursday?\n\nSincerely,\n[Your Name]",
      "Subject: Following up on my previous note\n\nHi [Name],\n\nI know how quickly inboxes fill up, so I just wanted to bump my previous email to the top of your stack.\n\nIf solving [Specific Pain Point] isn’t a priority for [Company Name] right now, absolutely no worries. But if it is on the roadmap for this quarter, I am highly confident we can deliver serious ROI.\n\nLet me know if you’re open to a quick 10-minute chat.\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Personalize the first sentence heavily. Mentioning a specific recent event shows you aren't mass-emailing.",
      "Keep the email focused entirely on the prospect's problems and metrics, not your product's internal features.",
      "A CTA asking 'Are you open to learning more?' often converts better than demanding a specific calendar time."
    ],
    faq: [
      { question: "How many emails should I send in a B2B sequence?", answer: "A standard highly-targeted B2B outbound sequence consists of 4 to 6 emails spread out over 21 to 30 days." },
      { question: "What is an 'Account-Based Marketing' (ABM) approach to cold email?", answer: "ABM means targeting multiple specific stakeholders at a single large company simultaneously, tailoring a highly specific message to the CEO, the CTO, and the VP of Sales based on their unique roles." },
      { question: "How do I avoid getting sent to spam in B2B outreach?", answer: "Always use a customized warmup domain, avoid using too many links or any images in the first email, and verify all email addresses using a tool like ZeroBounce before sending." }
    ]
  },
  {
    slug: 'cold-email-for-digital-marketing-clients',
    title: 'Cold Emails to Get Digital Marketing Clients',
    description: 'Grow your agency rapidly by landing high-ticket clients with these specialized digital marketing cold outreach templates.',
    intro: 'The digital marketing agency space is incredibly saturated. Business owners are bombarded daily with automated emails promising them "Page 1 on Google" or "Guaranteed 10x ROI." Because they have likely been burned by amateur agencies in the past, they view generic marketing pitches with extreme skepticism. To successfully land high-ticket retainer clients, your cold email must break through this skepticism by offering undeniable, customized upfront value before you ever ask for a dime.\n\nThe most successful agency cold emails utilize a "Show, Don\'t Tell" strategy. Do not tell a prospect you are great at SEO; show them a screenshot of their site\'s broken technical errors. Do not tell them you are a masterful copywriter; rewrite their current Facebook Ad and send the improved version for free in the very first email. By leading with an actionable audit, a custom Loom video, or a tangible strategy document, you instantly position yourself as a consultative expert. You eliminate the risk for the prospect because you have already proven your competence.\n\nUse the specialized templates below to pitch SEO, PPC, social media management, or web design services. Tailor them to highlight the specific revenue the prospect is currently losing due to their marketing gaps.',
    templates: [
      "Subject: 3 quick ideas to improve [Company Name]'s Google Ads\n\nHi [Name],\n\I was doing some market research in [City] and noticed that [Company Name] is currently running paid ads for the keyword '[Specific Keyword]'.\n\nI clicked through your funnel and noticed that the ad points to your generic homepage rather than a highly optimized landing page. In my experience running ads for [Industry], this single mistake typically cuts conversion rates in half, wasting thousands in ad spend.\n\nI put together a quick 3-minute video showing exactly how you can fix this today and instantly lower your Cost Per Lead. \n\nWould you like me to send the video over?\n\nBest,\n[Your Name]",
      "Subject: [Competitor Name] is outranking you for '[Valuable Keyword]'\n\nHi [Name],\n\nI run an SEO agency that exclusively helps [Industry] businesses dominate local search.\n\nI ran a quick technical audit on [Company Name]’s website today. While your site design is fantastic, you are currently losing massive organic traffic to [Competitor Name] for the term '[Valuable Keyword]'.\n\nThis is largely due to three easily fixable technical errors on your homepage. I mapped out exactly what these errors are and how your current web developer can patch them to regain that traffic.\n\nAre you open to a brief 10-minute chat next week to review the audit?\n\nCheers,\n[Your Name]",
      "Subject: I rewrote [Company Name]'s Facebook Ad for free\n\nHi [Name],\n\nI saw [Company Name]'s recent Facebook Ad campaign regarding [Product] in my feed today.\n\nAs a direct response copywriter, I love the product, but I think the current ad copy is leaving a lot of money on the table by focusing on features rather than the core customer pain point.\n\nI actually took the liberty of rewriting the ad copy for you using a highly-converting framework. I’ve attached it below. Feel completely free to drop this into your Ads Manager today and A/B test it against your current control—no strings attached!\n\nIf it ends up lowering your acquisition costs, I’d love to schedule a call to discuss how we can overhaul your entire funnel.\n\nBest regards,\n[Your Name]",
      "Subject: Quick feedback on your website's mobile design\n\nHi [Name],\n\nI came across [Company Name] while searching for [Service] in [City]. \n\nYour services look amazing, but when I pulled up the site on my phone, the \"Request a Quote\" button was broken and the text was misaligned, making it extremely difficult to contact you on mobile.\n\nSince over 60% of local traffic comes from mobile devices, fixing this could immediately result in a massive uptick in leads for you.\n\nI run a web design agency focused on high-conversion redesigns. Would you be open to a 10-minute call to discuss a potential refresh of the site?\n\nBest,\n[Your Name]",
      "Subject: Idea for [Company Name]'s email marketing\n\nHi [Name],\n\nI signed up for your email newsletter last week to learn more about [Company Name]. \n\nWhile the content is great, I noticed there wasn't an automated Welcome Sequence in place to nurture new leads like me into paying customers. You are likely missing out on a significant amount of passive revenue.\n\nWe build highly automated email flows for ecommerce brands that typically increase revenue by 15-20% on autopilot. \n\nDo you have 10 minutes next Tuesday to chat about implementing this for [Company Name]?\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Never attack the prospect's current marketing aggressively; they may have designed the website themselves and will take offense.",
      "Provide actionable solutions they can use immediately without hiring you. Counter-intuitively, giving away your secrets makes them want to hire you to execute them.",
      "Personalized Loom videos are the highest converting medium for pitching digital marketing services."
    ],
    faq: [
      { question: "Should I attach a pricing sheet in my cold email?", answer: "Never. Your goal is to get a discovery call, diagnose their unique problem, and then build a custom high-ticket proposal. Giving prices upfront commoditizes your service." },
      { question: "Who is the decision-maker for a marketing pitch?", answer: "At small businesses, target the CEO/Owner. At larger companies, target the Director of Marketing or the VP of Growth." },
      { question: "How much free value should I offer in the first email?", answer: "Offer a 'bite-sized' audit. Point out 1 or 2 specific errors. Do not spend 3 hours doing a complete site overhaul for free before they have even replied." }
    ]
  }
];

const out = [...data, ...newTemplates];
fs.writeFileSync(file, JSON.stringify(out, null, 2));
