const fs = require('fs');
const file = 'src/data/templates.json';
const data = JSON.parse(fs.readFileSync(file, 'utf-8'));

const newTemplates = [
  {
    slug: 'apology-email-for-missing-a-meeting',
    title: 'How to Apologize for Missing a Meeting',
    description: 'Save your professional reputation. Use these perfectly crafted apology emails when you completely forget or miss an important meeting.',
    intro: 'You sit down at your desk, glance at your calendar, and your heart drops: you entirely missed a massive client meeting 45 minutes ago. Whether you overslept, got trapped in horrific traffic, or simply wrote the wrong date in your planner, missing a committed professional meeting is an aggressive breach of etiquette. The immediate instinct is to panic, invent an elaborate lie regarding a sudden illness, or simply ghost the person out of sheer embarrassment. Do not do this. You must proactively own the mistake instantly.\n\nA masterclass apology email for a missed meeting is radically, painfully honest. Acknowledge your failure specifically in the first sentence. State exactly what happened (e.g., "I mismanaged my calendar" or "I was stuck dealing with a sudden server crash") without turning the email into a lengthy, defensive sob story. Most importantly, profusely value their time and immediately offer a frictionless solution to get the sync back on the books or simply answer their primary questions asynchronously via email to save them the hassle of jumping on another call.\n\nUse the tested triage templates below to instantly salvage your professional reputation when you drop the ball. These scripts rely on extreme accountability and immediate action.',
    templates: [
      "Subject: So incredibly sorry I missed our call!\n\nHi [Name],\n\nI am writing to offer my most sincere apologies for entirely missing our scheduled sync this afternoon regarding the [Project Name].\n\nI completely dropped the ball. I was dealing with a sudden [Brief Honest Reason: e.g., urgent client escalation] that absolutely commanded my attention, and I completely mismanaged my calendar in the chaos.\n\nI deeply respect your time and I am incredibly frustrated that I inconvenienced you.\n\nTo ensure we avoid further delays on the [Project Development], I am happy to either answer your core questions right here in an email thread, or jump on a quick call anytime tomorrow afternoon at your absolute earliest convenience.\n\nAgain, my sincerest apologies for the mix-up.\n\nBest regards,\n[Your Name]",
      "Subject: Missed our meeting / Sincere apologies\n\nHi [Name],\n\nPlease accept my immense apologies for missing our introductory call this morning. \n\nI somehow completely messed up the time zone conversion when I added the invite to my planner, and I just realized you must have been waiting in the Zoom room for me.\n\nI am incredibly eager to connect and learn more about [Company Name]'s Q3 goals. Would you be open to giving me another chance to chat later this week? \n\nI am completely free next Tuesday at [Time 1] or Thursday at [Time 2] if either of those options work better for your schedule.\n\nThanks,\n[Your Name]",
      "Subject: Apologies for the no-show today\n\nHi [Name],\n\nI want to sincerely apologize for completely missing our meeting today.\n\nI had an unforeseen family issue pull me entirely offline this morning at the absolute last minute, and I didn’t have a chance to alert you beforehand to cancel the calendar invite.\n\nI know how busy you are, and I deeply regret wasting that block of your morning. I will follow up tomorrow once things settle down on my end to find a better time for us to finally properly connect.\n\nWarmly,\n[Your Name]"
    ],
    tips: [
      "Never blame your assistant, the software (e.g., 'Zoom completely froze!'), or traffic. Blaming external factors makes you look weak and unaccountable. Own the mistake.",
      "Send it instantly. The second you discover you missed the meeting, draft the email fast. Do not wait hours out of embarrassment.",
      "Offer to handle it asynchronously. Tell them 'I can answer the 3 questions via email right now to save you another call.' They will deeply appreciate the time saved."
    ],
    faq: [
      { question: "Is it better to call or email an apology?", answer: "If you realize you are 10 minutes late, call them instantly. If the meeting was two hours ago, email them. A sudden phone call hours later is highly disruptive." },
      { question: "What if it was a final round job interview?", answer: "Missing a job interview is virtually always fatal to your candidacy unless it was a verifiable hospitalization. Send an apology to clear your conscience, but move on." },
      { question: "Should I offer a discount to an angry client?", answer: "If missing the meeting severely impacted a massive launch timeline, quietly crediting them 1 billable hour on their next invoice is a classy, unspoken peace offering." }
    ]
  },
  {
    slug: 'email-to-cancel-a-meeting-last-minute',
    title: 'How to Cancel a Meeting Last Minute',
    description: 'Handle emergencies properly. Use these extremely polite email templates to cancel a scheduled meeting at the last minute.',
    intro: 'It happens to every professional: you are staring at a massive, unmovable deadline, your inbox is exploding, and you realize you have a non-essential "brainstorming sync" scheduled in exactly 45 minutes. You must cancel the meeting to survive the afternoon, but canceling a colleague or client’s meeting at the last minute is deeply rude unless executed perfectly. The goal is to cancel the meeting without sounding like you believe your time is vastly more important than theirs.\n\nA masterfully executed last-minute cancellation relies on prioritization and respect. You must explicitly tell them exactly what emergency is forcing the cancellation, so they realize they aren\'t simply being blown off for a coffee break. Is there a massive server outage? A crucial board presentation? State the reason briefly. Crucially, do not leave the meeting in limbo. Either explicitly push the sync off indefinitely (e.g., "Let\'s revisit this in Q4") or immediately propose a hard reschedule date.\n\nDeploy the tested cancellation scripts below to gracefully clear your calendar during corporate emergencies. These templates prioritize empathy while vehemently guarding your own operational bandwidth.',
    templates: [
      "Subject: Canceling our 2 PM sync / [Your Name]\n\nHi [Name],\n\nI am so incredibly sorry, but I urgently need to cancel our 2:00 PM sync today regarding the [Project Name] initiative.\n\nSpecifically, the [Department Name] team just flagged a massive [Status/Bug/Issue] that requires my completely undivided attention to resolve before the end of the day.\n\nI hate to shuffle your schedule at the absolute last minute. Rather than scrambling to find a new time this week, would you be comfortable handling the structural review asynchronously via a Google Doc instead? \n\nI can tag you with my specific comments once this fire is put out on my end.\n\nBest regards,\n[Your Name]",
      "Subject: Urgently needing to cancel our call today\n\nHi [Name],\n\nI’m writing to quickly and profusely apologize, but I must cancel our call scheduled for this afternoon.\n\nI have unexpectedly been pulled into an all-day leadership offsite regarding the upcoming [Initiative], and I won't have the appropriate time to thoughtfully review the [Deliverable Document] with you beforehand as promised.\n\nCan we definitively push this meeting to next Tuesday afternoon? If that works on your end, I will send over an officially updated invite.\n\nCheers,\n[Your Name]",
      "Subject: Re: [Meeting Title] / Request to cancel\n\nHi [Name],\n\nI am so sorry for the massive late notice, but I need to cancel our brainstorming session in 30 minutes.\n\nI am currently running aggressively behind on the delivery of the [Crucial Client Deliverable] and desperately need to recapture every spare minute of deep work today to ensure we hit the 5 PM launch deadline.\n\nI’ll review the preliminary notes you attached to the invite over the weekend and circle back on Monday morning with next steps.\n\nThanks for understanding!\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Cancel via their preferred platform. If you normally communicate with this client strictly via Slack, cancel via Slack. Do not send an email they won't check until tomorrow.",
      "The 'Asynchronous Out'. Always offer to simply handle the topic via email. Internal recurring meetings can almost always be handled via a bulleted list instead of a 45-minute call.",
      "Validate their prep work. If they built a 10-slide deck for the meeting, acknowledge that you will read it on your own time so they don't feel their labor was wasted."
    ],
    faq: [
      { question: "What is considered 'last minute'?", answer: "Anything less than 4 to 6 hours before the meeting. At that point, the person has already planned their entire morning around speaking with you." },
      { question: "Is it okay to lie about being sick?", answer: "No. The professional world is shockingly small. Simply state 'I am completely overwhelmed by a client crisis'—everyone universally understands and respects honest workload constraints." },
      { question: "How do I cancel with a VIP or CEO?", answer: "You generally do not. If you absolutely must, offer to hop on a massively condensed 5-minute phone call instead of the scheduled 60-minute Zoom to deliver your core update instantly." }
    ]
  },
  {
    slug: 'welcome-email-to-new-client-agency',
    title: 'Welcome Email Templates for New Agency Clients',
    description: 'Set identical expectations from day one. Use these highly structured welcome emails to rapidly onboard new agency clients seamlessly.',
    intro: 'The exact moment a massive client signs the Master Services Agreement and pays the initial deposit, their psychological state transitions from excitement to "Buyer\'s Remorse Anxiety." They just finalized a five-figure commitment and are terrified they made a mistake. A brilliantly structured welcome email completely eliminates this anxiety. It instantly proves that your agency is a hyper-organized, deeply professional machine that possesses absolute control over the entire engagement process.\n\nA great agency welcome email removes all guesswork. It must explicitly outline exactly what happens next. Do not send a massive wall of text. Use bulleted lists to clearly articulate the timeline, request any immediate login credentials or brand assets you desperately need to begin production, and officially introduce them to their dedicated Account Manager. Crucially, explicitly state your agency\'s strict communication boundaries (e.g., "We only process revisions via Basecamp, never via urgent weekend text messages").\n\nUtilize the heavily optimized agency templates below to smoothly transition prospects into long-term clients. These scripts establish brutal efficiency, cement boundaries, and set the tone for a massively successful partnership.',
    templates: [
      "Subject: Welcome to [Agency Name]! Next Steps for [Company Name]\n\nHi [Client/Founder Name],\n\nWelcome aboard! The entire team here at [Agency Name] is incredibly excited to officially kick off the [Project Name] initiative with you.\n\nOur accounting team confirmed receipt of the initial deposit this morning. To ensure we can rapidly hit the ground running for your targeted launch date, here is a quick overview of exactly what happens next:\n\n1. Onboarding Questionnaire: Please complete this incredibly brief form [Link] by Friday so our design team fully understands your current brand guidelines.\n2. Asset Handoff: Please grant our engineering team administrative access to your [Platform/CMS/AWS Environment] using this secure portal link.\n3. Kickoff Call: Once the assets are securely handed over, your dedicated Account Manager, [Colleague Name] (CC'd here), will reach out to schedule our formal deep-dive kickoff strategy session.\n\nIf you have any billing or strategic questions, simply reply directly to this thread. Otherwise, [Colleague Name] will be taking excellent care of you moving forward!\n\nCheers,\n[Your Name]",
      "Subject: Official kickoff — [Client Name] & [Agency Name]\n\nHi [Client Name],\n\nThank you for returning the signed Master Services Agreement!\n\nI want to personally welcome you to [Agency Name]. We are diving straight into intense research regarding the [Niche/Sector] market this afternoon.\n\nTo ensure our communication remains perfectly streamlined as production heavily ramps up over the next 3 weeks, we have automatically set up a dedicated client portal for your team here: [Link: Basecamp/Asana/ClickUp Portal]. \n\nAll specific revision requests, daily updates, and massive file transfers will be exclusively routed securely through that portal rather than getting lost in giant email threads.\n\nPlease log in today, poke around, and let me know if you run into any permission issues.\n\nBest,\n[Your Name]",
      "Subject: Next Steps for the [Specific Service] Retainer\n\nHi [Client Name],\n\nWelcome to the [Agency Name] family! \n\nStarting this Monday, we will officially begin generating the promised [Deliverable Name] weekly batches for your review.\n\nPlease ensure you take exactly 15 minutes today to fill out the 'Voice & Tone' style guide located here: [Link]. \n\nThe deeper the insights you provide in that specific document, the faster our copywriting team can perfectly nail [Company Name]'s exact brand voice on the very first draft.\n\nI’m thrilled we are finally making this project a reality!\n\nBest regards,\n[Your Name]"
    ],
    tips: [
      "Establish the 'Point of Contact'. If you are the CEO who sold the deal, the welcome email is the precise moment you gracefully hand them off to a Junior Account Manager so they don't constantly email you directly for minor updates.",
      "Always set communication boundaries early. Explicitly demanding they use Asana or Basecamp instead of texting you is 100x easier on Day 1 than attempting to enforce it 3 months later during a crisis.",
      "Send a physical gift. For deals exceeding $10,000, sending a branded bottle of wine or high-end coffee via a separate automated system within 48 hours is a legendary retention metric."
    ],
    faq: [
      { question: "Should I schedule the kickoff call immediately?", answer: "No. Force them to complete the intake questionnaire and hand over all passwords first. A kickoff call is entirely useless if your team doesn't have secure access to their systems yet." },
      { question: "What if they ignore the onboarding questionnaire?", answer: "Send a polite follow-up in 3 days natively inside the project management tool (not an email). Remind them: 'Our production timeline is officially paused until this questionnaire is submitted.'" },
      { question: "How long should a welcome email be?", answer: "Keep it under 250 words. They are busy founders who simply want to know what to click next." }
    ]
  },
  {
    slug: 'client-offboarding-email-template',
    title: 'Professional Client Offboarding Templates',
    description: 'End the engagement flawlessly. Use these highly professional offboarding emails to gracefully transition agency clients while securing a glowing review.',
    intro: 'The end of an enormously successful, 6-month consulting or agency engagement is heavily overlooked by most business owners. They simply send the final invoice and awkwardly stop communicating. This is a fatal strategic mistake for your long-term pipeline. The "offboarding" phase is the absolute peak of the client\'s emotional satisfaction curve; they have just received the beautiful final product they paid for. You must heavily leverage this specific window to securely lock in a glowing 5-star testimonial, request a massive referral, and ensure a pristine project hand-off.\n\nA brilliant offboarding email accomplishes three distinct administrative tasks efficiently. First, it explicitly confirms exactly where all final intellectual property and source files are permanently stored (so they do not email you frantically 5 years later asking for a logo file). Second, it explicitly confirms that all final retainer billing has ceased to alleviate financial anxiety. Third, it warmly asks for a brutally specific testimonial regarding a specific metric you improved for them.\n\nEmploy the structured offboarding templates below to securely close out massive projects. These scripts ensure you leave a legacy of radical professionalism while passively generating high-quality inbound leads for your business.',
    templates: [
      "Subject: Wrapping up the [Project Name] project\n\nHi [Client Name],\n\nIt is hard to believe we have officially hit the final milestone of the [Project Name] initiative!\n\nI am incredibly proud of the massive [Specific Metric, e.g., 40% organic traffic surge] the team generated over the last quarter. Because all production has officially concluded, I wanted to formally send over the remaining administrative offboarding materials.\n\nYou can access every single original source file, administrative password, and final vector deliverable permanently stored in this dedicated Google Drive folder: [Link]. Please download a hard copy to your internal servers this week.\n\nAll recurring billing on your end has been officially officially canceled.\n\nIf you have 2 spare minutes this week, I would be absolutely honored if you could leave a brief review detailing your experience utilizing our [Specific Service] on our Clutch profile here: [Link: Review Site].\n\nIt was an absolute pleasure partnering with [Company Name]!\n\nBest regards,\n[Your Name]",
      "Subject: Offboarding details for [Client Company Name]\n\nHi [Client Name],\n\nNow that the new [Platform/Website] is officially live and humming perfectly, I wanted to quickly send over our official offboarding checklist.\n\nEffective tomorrow, we will systematically revoke our agency's administrative access from your [System Names] environments strictly for your own internal security and peace of mind.\n\nAttached to this email is a final 5-page PDF 'Launch Guide' documenting precisely how your junior team can easily update the new systems moving forward without requiring external developer help.\n\nShould you find you need ongoing monthly maintenance later this year, please don’t hesitate to reach back out for a deeply discounted alumni retainer.\n\nWishing the entire team massive success with the launch!\n\nCheers,\n[Your Name]",
      "Subject: Thank you from [Agency Name]!\n\nHi [Client Name],\n\nThank you so much for trusting [Agency Name] to execute the [Project Name] overhaul.\n\nSince the deliverables have officially been handed off and the final invoice is fully settled, I wanted to humbly ask a brief favor.\n\nWe primarily grow our boutique agency purely through incredibly strong word-of-mouth. If you know any other B2B founders currently struggling with [Specific Pain Point we just solved for them], would you be open to introducing us?\n\nIf not, no worries at all! I will continue following [Company Name]’s incredible growth on LinkedIn.\n\nStay in touch,\n[Your Name]"
    ],
    tips: [
      "Ask for the review natively. Provide a direct, clickable link directly to your Google My Business, Clutch, or LinkedIn profile. Do not make them hunt for it.",
      "Offer the 'Alumni Discount'. Mentioning that returning clients receive a small loyalty discount heavily incentivizes them to call you first when a new project arises next year.",
      "Send a physical gift. Offboarding a $50k project? Send a personalized, handcrafted closing gift to the executive's physical office. They will vividly remember you forever."
    ],
    faq: [
      { question: "Should I offboard a client who violently terminated the contract?", answer: "Yes, even more so. Send a hyper-professional, brutally cold administrative email securely transferring all assets and heavily documenting that all contractual obligations have been legally met." },
      { question: "How long should I keep their massive source files?", answer: "Outline this in your contract! Typically, an agency is legally required to host the 50GB of raw source files for 30 to 60 days post-launch before deleting them to save server costs." },
      { question: "Can I use their logo on my website?", answer: "Always explicitly ask their legal team in the offboarding email: 'Are we officially cleared to feature the [Company] logo in our public case study portfolio?'" }
    ]
  },
  {
    slug: 'out-of-office-autoresponder-professional',
    title: 'Professional Out of Office (OOO) Emails',
    description: 'Take a vacation guilt-free. Use these highly professional Out of Office autoresponder templates to maintain extreme reliability while entirely offline.',
    intro: 'Activating your vacation auto-responder is deeply cathartic. However, a poorly constructed Out of Office (OOO) email causes massive logistical chaos for your remaining team members. When a major client frantically emails you on a Tuesday regarding an aggressively broken production server, a generic "I am currently away from my desk" response is brutally insufficient. They need to know exactly who to escalate the 5-alarm fire to instantly, and they need to know explicitly when they can expect a direct response from you.\n\nA flawless OOO message strictly prioritizes delegation over conversational warmth. Remove all the cute emojis illustrating your trip to the Bahamas. State the exact, absolute date of your return (so they do not expect a reply over the weekend). Most importantly, provide the specific, clickable email address of the exact colleague who is currently covering your urgent portfolio. If you are a solo founder, brutally manage their expectations by stating they will absolutely not receive a reply from you until you return.\n\nUse the tested autoresponders below to seamlessly automate your absence. Whether you are taking a week-long honeymoon, stepping out for a 2-hour root canal, or attending a massive corporate retreat, these scripts preserve your reputation.',
    templates: [
      "Subject: Out of Office: [Your Name]\n\nHello,\n\nThank you for reaching out. I am currently out of the office entirely offline starting [Start Date] and will officially return on [Return Date].\n\nDuring this time, I will have absolutely no access to my email inbox.\n\nIf your request is non-urgent, I will review and respond to your email promptly upon my return early next week.\n\nIf you require immediate, urgent assistance regarding an active [Department Name] project, please reach out directly to my colleague, [Colleague's Name], at [Colleague's Email Address] and they will gladly assist you.\n\nBest regards,\n[Your Name]",
      "Subject: OOO - Attending the [Conference Name] Summit\n\nHi there,\n\nThank you for your email.\n\nI am currently attending the [Conference Name] in [City] from [Start Date] to [End Date]. Because I am rapidly jumping between seminars and networking events, my response times will be heavily delayed.\n\nIf you are also attending the summit, please shoot me a direct message on LinkedIn and I would love to connect for a quick coffee!\n\nFor any highly urgent technical escalations, please submit a direct ticket to [Support Email Address] and the engineering team will prioritize the fix instantly.\n\nThanks,\n[Your Name]",
      "Subject: Out of Office: Maternity/Paternity Leave\n\nHello,\n\nThank you for your message.\n\nI am currently taking extended parental leave to spend time with my growing family. I will be entirely away from my inbox starting [Date] through roughly [Return Date].\n\nDuring my extensive absence, the [Department Name] portfolio has been completely transitioned to the deeply capable hands of [Alternative Contact Name].\n\nPlease direct all inquiries, contract approvals, and project updates directly to them at [Alternative Email] to ensure there are no delays in production.\n\nThank you so much for your understanding, and I look forward to reconnecting heavily in the Fall.\n\nWarmly,\n[Your Name]",
      "Subject: OOO - Deep Work Block\n\nHi,\n\nThanks for reaching out! \n\nI am currently operating in a 'deep work' communication block today to finalize the massive [Project Name] rollout. \n\nI will only be checking my inbox actively at exactly 12:00 PM and 4:00 PM EST today. I appreciate your extreme patience as I wrap up this critical launch!\n\nIf this is a massive emergency regarding server downtime, please ping me immediately via Slack.\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Format the alternative email address explicitly. Do not just say 'Contact Janet'. Write 'Janet Smith (jsmith@company.com)' so they can click and copy it instantly.",
      "Buffer your return date. If you get back on Monday the 12th, tell them you return on Tuesday the 13th. This buys you one full quiet day of catching up on hundreds of emails without them instantly demanding a reply.",
      "Remove your phone number. Never leave your personal cell phone number in an OOO email unless you are actively on call for massive corporate emergencies."
    ],
    faq: [
      { question: "Can I say I am on vacation?", answer: "Yes, but keep it brief. 'I am taking some much-needed PTO with my family' is fine. A massive multi-paragraph recap of your Disney itinerary is wildly unprofessional." },
      { question: "Should I set an OOO for a single day?", answer: "Absolutely. If you are out sick entirely, an OOO saves massive internal panic when an urgent client request goes ignored for 8 hours." },
      { question: "What if I am a solo founder with no coverage?", answer: "Simply state the truth: 'I am taking 3 days completely offline. Because I am a solo operation, all normal project communications will be heavily paused until Thursday. I deeply appreciate your patience.'" }
    ]
  }
];

const out = [...data, ...newTemplates];
fs.writeFileSync(file, JSON.stringify(out, null, 2));
