const fs = require('fs');
const file = 'src/data/templates.json';
const data = JSON.parse(fs.readFileSync(file, 'utf-8'));

const newTemplates = [
  {
    slug: 'cold-email-newsletter-sponsorship',
    title: 'How to Pitch a Newsletter Sponsorship',
    description: 'Acquire deeply engaged customers. Use these cold outreach templates to secure insanely profitable sponsorship deals with niche newsletter creators.',
    intro: 'Modern digital marketers are abandoning broad Facebook Ads in favor of highly targeted, extreme-niche newsletter sponsorships. When an influential creator with 15,000 highly engaged Chief Marketing Officers (CMOs) personally recommends your B2B SaaS product in their morning digest, the conversion rates are staggering. However, securing a sponsorship slot on a prominent newsletter is incredibly difficult. Top creators possess strict gatekeepers and actively reject sponsorships that offer irrelevant products or attempt to haggle aggressively on price.\n\nA highly successful newsletter sponsorship pitch respects the creator\'s profound influence. Do not blast them demanding "What is your CPM (Cost Per Mille)?" Your cold email must instantly prove you actually actively read their newsletter. Reference a specific, brilliant joke they made in last Tuesday’s edition. Explicitly state exactly why your specific product natively solves massive pain points for their specific demographic context. Make the financial transaction entirely frictionless by asking for their media kit upfront.\n\nLeverage the heavily refined templates below to start securing massive B2B and B2C newsletter sponsorships. These scripts bypass the creator\'s mental spam filter by immediately validating their authority and offering massive mutual value.',
    templates: [
      "Subject: Sponsoring the [Newsletter Name] for Q3\n\nHi [Creator First Name],\n\nI am a massive, daily reader of the [Newsletter Name]. Your deep dive on [Specific Niche Topic] last Thursday fundamentally changed how my engineering team handles [Process]. Brilliant work.\n\nI actually handle growth at [Your Company Name], a tool that helps [Target Audience] completely automate their [Specific Problem].\n\nBecause your subscriber base perfectly aligns with our most successful power users, I am actively looking to secure a 4-week dedicated sponsorship slot in your newsletter for the upcoming quarter.\n\nCould you please send over your current Media Kit and pricing availability for [Month]?\n\nThanks for creating such an incredible resource for the community!\n\nBest,\n[Your Name]",
      "Subject: Quick question regarding a dedicated email blast\n\nHi [Creator Name],\n\nI’ve been subscribed to your list since 2022. I genuinely believe you possess the highest quality [Industry] content currently available.\n\nMy team just launched a brand new SaaS product specifically engineered to help [Target Persona] save 10 hours a week on [Task].\n\nWe have a massive marketing budget allocated specifically for creator partnerships this month. Rather than buying standard banner ads, I would love to explore paying for a dedicated, solo 'deep dive' email where you review the software extensively for your audience.\n\nAre you currently open to taking on dedicated product deep-dives? If so, I’d love to see your pricing tiers.\n\nCheers,\n[Your Name]",
      "Subject: Exploring a long-term partnership with [Creator Name]\n\nHi [Creator Name],\n\nI wanted to reach out because your recent wildly viral thread on Twitter regarding [Topic] was incredibly insightful.\n\nAt [Company Name], we strictly sell premium [Product/Service] designed entirely for the exact demographic of your audience.\n\nWe are currently looking for 3 highly influential creators to partner with on a long-term, 6-month continuous sponsorship basis. We strongly prefer to lock in long-term inventory rather than buying one-off ads.\n\nIf you have long-term inventory available for Q4, I would love to hop on a quick 10-minute call to discuss your rates and see if our brand is a strong fit for your readers.\n\nBest regards,\n[Your Name]"
    ],
    tips: [
      "Ask for the 'Media Kit'. A Media Kit is a standard PDF detailing their open rates, click-through rates, audience demographics, and pricing. Using this terminology proves you are a serious buyer.",
      "Offer them product access. If you are selling software, tell them 'I just created a free lifetime Pro account for you so you can actually test it before deciding if you want to feature it.'",
      "Do not haggle blindly. If a creator charges $1,500 per email, do not immediately counter with $200. It is insulting. If it is too expensive, simply walk away politely."
    ],
    faq: [
      { question: "How do I know if their audience is real?", answer: "Always aggressively ask for specific metrics in replies: 'What was the exact unique open rate and click-through rate of your last 3 standard sends?'" },
      { question: "Should I write the ad copy or should they?", answer: "Ideally, they should. Give them brief talking points, but let the creator write the ad in their own native, trusted voice for drastically higher conversions." },
      { question: "Is buying one ad enough?", answer: "Rarely. Marketing requires multiple touches. Always try to buy a 'bundle' of 3 to 4 ads spread across a single month to build recognition." }
    ]
  },
  {
    slug: 'cold-email-affiliate-partnership-request',
    title: 'Cold Email Affiliate Partnership Requests',
    description: 'Scale your affiliate program rapidly. Use these targeted templates to recruit massive influencers and bloggers into your affiliate marketing program.',
    intro: 'Building a massive affiliate and referral ecosystem is the holy grail of zero-CAC (Customer Acquisition Cost) growth marketing. If you can convince a highly influential blogger to embed your affiliate link natively inside their #1 ranking SEO article, they will generate passive sales for you for years. However, high-traffic affiliates receive dozens of spammy "Join our Affiliate Program" emails every single day. Because integrating a new affiliate link is deeply annoying administrative work, they will aggressively ignore generic outreach.\n\nA highly converting affiliate request must make the financial transition incredibly lucrative and explicitly effortless. You must identify the exact, highly trafficked article where your link belongs. Do not pitch a standard 10% commission. To acquire a massive "whale" affiliate, you must offer them a highly inflated VIP commission rate (e.g., 40%) exclusively customized for their audience. You are buying their distribution; compensate them accordingly.\n\nLeverage the optimized partnership templates below to systematically recruit elite bloggers, YouTubers, and niche influencers. These scripts focus heavily on massive custom payouts and minimal operational friction.',
    templates: [
      "Subject: Massive affiliate bump for the [Website Name] blog\n\nHi [Name],\n\nI was doing some keyword research and noticed your incredible guide on [Topic] currently ranks #1 on Google for '[High Volume Keyword]'.\n\nI actually handle growth for [Company Name]. We sell a highly premium [Product/Service] that completely solves the exact pain point you highlighted in section 3 of that article.\n\nBecause your traffic is so highly qualified, I would love to offer you an exclusive, VIP affiliate rate of 40% recurring commission strictly for your readers.\n\nIf you simply swap out your current generic link to [Competitor Name] with our custom tracker, you could realistically double your current Monthly Recurring Revenue from that exact post overnight.\n\nLet me know if you are open to exploring a quick test!\n\nBest,\n[Your Name]",
      "Subject: Partnering with your YouTube channel\n\nHi [Creator Name],\n\nI’ve been subscribed to your channel for a year. Your recent massive deep-dive video comparing [Tool A] vs [Tool B] was brilliantly structured.\n\nI noticed you frequently heavily review [Product Category] tools but aren't currently monetizing them heavily with backend affiliate links in the description box.\n\nMy team built [Your Product Name], which natively integrates with the exact workflow you teach on your channel. We pay out a massive $200 CPA (Cost Per Acquisition) for every single user you refer.\n\nIf you are interested, I can provision a free lifetime Enterprise account for you to test on the channel. \n\nAre you open to reviewing custom affiliate opportunities this quarter?\n\nCheers,\n[Your Name]",
      "Subject: Upgrading your review of [Our Company Name]\n\nHi [Name],\n\nThank you so much for featuring [Company Name] heavily as the #2 option on your massive '[Top 10 List]' article!\n\nI noticed you are currently using a standard generic domain link to our current homepage instead of an affiliate tracking link. You are practically leaving thousands of dollars on the table!\n\nI went ahead and proactively generated a custom, dedicated affiliate link specifically for you right here: [Link]\n\nIf you quickly update the URL in your article, our system will automatically track your conversions and pay you a 30% recurring commission immediately.\n\nThank you again for the incredibly detailed review!\n\nBest regards,\n[Your Name]"
    ],
    tips: [
      "Target comparisons. If an affiliate ranks #1 for 'Best CRM Software 2024' and you are a CRM missing from the list, pitch them aggressively with a massive commission rate to buy your way onto the list.",
      "Offer exclusive discount codes. Telling an influencer 'I created the code JANET20 for your readers to get 20% off' makes them look incredibly generous to their audience, forcing them to promote you.",
      "Always offer a 'VIP Tier' rate. Standard programs offer 10%. Elite influencers will only even open the email if the subject line mentions 30% to 50% cuts."
    ],
    faq: [
      { question: "What software should I use to manage affiliates?", answer: "Rewardful and PartnerStack are two wildly popular, highly trusted platforms that handle the massive logistical nightmare of tracking clicks and handling automated tax payouts." },
      { question: "Can I just pay them for a link instead of via affiliate?", answer: "Yes, many massive enterprise blogs require a flat 'Sponsorship Fee' just to be included on their Top 10 lists, regardless of affiliate clicks." },
      { question: "Is offering 50% commission too high?", answer: "For SaaS companies with zero marginal cost of replication, acquiring a customer for 50% of the first year's revenue is often highly profitable. Digital products scale beautifully with aggressive affiliate payouts." }
    ]
  },
  {
    slug: 'follow-up-email-after-career-fair',
    title: 'The Perfect Career Fair Follow-Up Email',
    description: 'Don\'t get lost in the stack of resumes. Secure the interview with these polite, memorable career fair follow-up emails sent directly to the recruiter.',
    intro: 'Attending a massive university career fair is exhausting. You dress impeccably, stand in chaotic lines for hours, and finally hand your slightly wrinkled resume to an exhausted corporate recruiter. However, that entire effort is virtually pointless if you do not instantly execute a highly aggressive digital follow-up. Recruiters at major career fairs return to their hotel rooms with literally hundreds of identical paper resumes. If your resume is going to survive the initial brutal culling process, you must bypass the physical pile entirely and hit their inbox directly.\n\nA masterclass career fair follow-up email bridges the gap between chaotic real-world networking and organized corporate hiring. Your primary objective is to trigger their memory. The subject line must explicitly name the exact specific event. In the first sentence, prominently reference a highly specific, unique detail you discussed (e.g., "I loved chatting about your team’s recent expansion into the Austin market"). Attach a pristine, perfectly formatted PDF of your resume, and explicitly state you have officially submitted the formal digital application through their clunky portal as requested.\n\nUtilize the heavily tested student templates below to stand out aggressively in the corporate pipeline. These scripts guarantee the recruiter remembers you vividly and pulls your digital file to the top of the interview list.',
    templates: [
      "Subject: Great meeting you at the [University Name] Career Fair - [Your Name]\n\nHi [Recruiter's Name],\n\nThank you so much for taking the time to speak with me today at the [University] Career Fair.\n\nAmidst all the chaos, I really appreciated our brief, fantastic conversation regarding [Specific topic, e.g., the new data analytics transition] happening at [Company Name]. It fully solidified my deep desire to join the team.\n\nAs we discussed, I have officially submitted my formal application through the corporate online portal for the [Job Title] position.\n\nI’ve also attached a pristine digital copy of my resume here for your direct internal reference. \n\nI look forward to hearing about the next steps and potentially interviewing in the coming weeks!\n\nBest regards,\n[Your Name]",
      "Subject: Following up from the [Event Name] Expo - [Your Name]\n\nHi [Recruiter Name],\n\nIt was an absolute pleasure connecting with you yesterday at the [Event Name] Expo.\n\nI was incredibly impressed by the heavy emphasis [Company Name] places on [Specific Value or Trait], specifically how you detailed the intense hands-on mentorship program for new junior engineers.\n\nGiven my extensive academic background in [Specific Skill/Software], I am highly confident I could hit the ground running efficiently on day one.\n\nI’ve attached my updated resume and a link to my Github portfolio below.\n\nThank you again for your time and guidance!\n\nCheers,\n[Your Name]",
      "Subject: Re: [Company Name] Junior Roles / [University Name] Career Fair\n\nHi [Recruiter Name],\n\nI know you likely spoke to hundreds of eager students today, so I will keep this extremely brief!\n\nThank you for chatting with me regarding the open [Job Title] role. I actually took your explicit advice and heavily edited the attached resume to highlight my hands-on experience handling [Specific Project/Task].\n\nI’ve formally submitted my application online as requested.\n\nPlease let me know if there is anything else I can provide to the internal hiring team to bolster my candidacy.\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Send the email within 12 hours of the event ending. Waiting three days means they have already flown back to corporate headquarters and sorted the initial resumes.",
      "Find their email stealthily. If they refused to hand out business cards, use LinkedIn to find their name, then use an email hunting tool (like Hunter.io) to guess their corporate email address.",
      "Include a direct link to your digital portfolio, Github, or a highly curated LinkedIn profile right in the body of the email."
    ],
    faq: [
      { question: "What if I forgot the recruiter's specific name?", answer: "Look up '[Company Name] University Recruiter' on LinkedIn immediately after the fair. Usually, there are only 1 or 2 dedicated staff members handling your specific massive university." },
      { question: "Should I mention my GPA in the email?", answer: "No. The email body is purely for relationship building and establishing culture fit. Let your attached PDF resume handle the hard academic data." },
      { question: "Do I really need to apply online if I handed them my physical resume?", answer: "Yes, 100%. Major corporations literally cannot legally hire you unless your demographic data is securely logged in their Applicant Tracking System (ATS) portal." }
    ]
  },
  {
    slug: 'cold-email-informational-interview-request',
    title: 'Cold Email Templates for Informational Interviews',
    description: 'Networking made easy. Learn how to ask a senior executive or industry leader for a 15-minute informational interview using these polite templates.',
    intro: 'Requesting an "informational interview" is the single most powerful networking strategy for ambitious career builders, college students, and pivoting professionals. An informational interview is not a job pitch; it is a highly targeted, 15-minute exploratory chat where you strictly ask a senior executive for deeply specific career advice. Massive tech executives, hedge fund managers, and brilliant designers will frequently eagerly accept these requests because humans universally enjoy talking about their own success. However, finding the time is difficult, so your request must be incredibly frictionless.\n\nA flawless cold email requesting an informational interview is anchored in profound flattery and aggressive brevity. Do not ask for a "quick 60-minute sync." Ask specifically for a rigid 10 or 15-minute call. You must explicitly promise that you are not pitching a product and you are not looking for a job handout. Your sole objective is to extract highly specialized advice regarding how they navigated a specific hurdle you are currently facing in your own career. By lowering the stakes and complimenting their unique expertise, you drastically raise your response rate.\n\nDeploy the highly strategic, polite templates below to bypass gatekeepers and get on the calendar of elite industry leaders. These scripts are engineered to secure invaluable mentorship connections.',
    templates: [
      "Subject: Aspiring [Job Title] seeking brief advice\n\nHi [Name],\n\nI have followed your incredible career trajectory at [Company Name] heavily over the last year. Your work massively scaling the [Specific Department/Initiative] is incredibly inspiring to me.\n\nI am currently a [Your Current Title] looking to aggressively pivot my career directly into the [Target Industry] sector over the next 12 months.\n\nBecause your expertise in [Specific Niche Topic] is virtually unmatched, I was hoping to ask a massive favor. Would you be open to a strictly 15-minute brief phone call next week so I could ask you three specific questions about how you navigated [Challenge]?\n\nI completely understand if your calendar is entirely full right now. No pressure at all.\n\nBest regards,\n[Your Name]",
      "Subject: Quick question from a [University Name] student \n\nHi [Name],\n\nI am currently a Junior at [Your University Name] heavily studying [Major]. \n\nI noticed on LinkedIn that you also graduated from [Shared University] before building such an incredible career at [Company Name]!\n\nAs I begin looking closely at entry-level [Job Title] roles, I am finding the landscape incredibly daunting. Since you successfully made the exact leap I am currently attempting, would you be willing to do a quick 10-minute informational coffee chat over Zoom?\n\nI strictly just want to gather your brilliant advice on what skills I am currently lacking. \n\nLet me know if you have a brief window next Thursday!\n\nCheers,\n[Your Name]",
      "Subject: Admiring your work at [Company Name]\n\nHi [Name],\n\nI recently read your incredibly insightful article on [Topic/Publication] regarding [Specific details]. It completely changed my perspective on [Subject].\n\nI am actively working on building my deep technical skills within [Niche Area]. Because I deeply respect your specific management style, I’d love to briefly pick your brain regarding exactly how you evaluate junior talent.\n\nWould you be open to a highly targeted, 15-minute Google Meet next week? I promise to keep a strict eye on the clock and entirely respect your time.\n\nThanks,\n[Your Name]"
    ],
    tips: [
      "Find the 'Shared Alumni' connection. If you both attended the same college, definitively put the college name directly in the subject line. This increases open rates exponentially.",
      "Strictly enforce the time limit yourself. When you finally get on the call, set a timer. At exactly 14 minutes, loudly announce 'I want to respect your time, I have to let you go!'. They will deeply respect your boundary management.",
      "Never bait and switch. If you promised an informational interview, do not instantly drop your resume and beg for a job. Build the relationship purely on advice first."
    ],
    faq: [
      { question: "What questions should I ask during the actual interview?", answer: "Ask highly specific, 'tactical' questions. E.g., 'What was the exact hardest technical concept you had to master during your first 90 days on the job?'" },
      { question: "How long should I wait for a reply?", answer: "Executives are busy. Wait one full week and gently bump the thread once. If they ignore the bump, move on." },
      { question: "Should I send a thank you note afterward?", answer: "Always. Immediately send a warm thank-you email highlighting the single most valuable piece of advice they gave you. This heavily cements the new mentorship connection." }
    ]
  },
  {
    slug: 'thank-you-email-after-zoom-interview',
    title: 'Thank You Email After a Zoom Interview',
    description: 'Master remote hiring. Use these flawless virtual thank-you email templates to stand out aggressively after a remote Zoom interview.',
    intro: 'The entire corporate hiring landscape has permanently shifted to virtual environments. Whether you are interviewing over Zoom, Microsoft Teams, or Google Meet, the core fundamentals of aggressive professional follow-ups remain completely unchanged. However, remote interviews present highly unique friction points: awkward silences, slight audio delays, and a massive lack of organic physical body language. Because the interviewer cannot feel your physical "presence," your post-interview thank-you email holds exponentially more weight in cementing a positive, engaging culture fit.\n\nA brilliant post-Zoom thank you email must successfully bridge the digital gap. It is critical to acknowledge the virtual nature gracefully—perhaps briefly joking about a minor tech glitch you both laughed through or complimenting their chaotic home office background if it was discussed. More importantly, reiterate exactly how your deep technical skillset perfectly maps to the entirely remote (or hybrid) workflow required for the role. Prove you are highly capable of operating aggressively without intense micromanagement.\n\nUse the customized virtual interview templates below to expertly conclude your digital hiring process. These scripts ensure you appear intensely reliable, deeply tech-literate, and perfectly suited for modern corporate environments.',
    templates: [
      "Subject: Thank you! / [Your Name] - [Job Title] Interview\n\nHi [Interviewer's Name],\n\nThank you so much for taking the time to meet with me over Zoom this afternoon regarding the [Job Title] role.\n\nDespite the slight audio glitch early on, I thoroughly enjoyed our massive deep dive into [Specific Topic discussed]. Your strategic vision regarding how the remote team collaborates asynchronously on [Project Idea] is absolutely brilliant, and it aligns heavily with exactly how I operate best.\n\nI am incredibly excited about the prospect of joining the [Company Name] team. \n\nPlease let me know if you need any additional portfolio samples sent over as you finalize your internal hiring decisions this week.\n\nBest regards,\n[Your Name]",
      "Subject: Great chatting today - [Your Name]\n\nHi [Interviewer Name],\n\nThank you for a truly fantastic virtual conversation earlier today!\n\nLearning more about the fast-paced, highly autonomous culture at [Company Name] completely solidified my interest in the open [Job Title] role. I particularly loved hearing your thoughts closely regarding [Specific Insight they shared].\n\nBecause my entire background involves heavily scaling [Specific Process] in distributed, remote environments, I am highly confident I could generate massive immediate impact for the team.\n\nI look forward to hearing about the next steps!\n\nCheers,\n[Your Name]",
      "Subject: Re: Next Steps / [Job Title] position\n\nHi [Hiring Manager Name],\n\nThank you again for coordinating our extensive virtual interview today. \n\nThe technical whiteboard session was incredibly rigorous and exciting! I deeply appreciated your candid feedback regarding how the team approaches [Specific Technical Concept we discussed].\n\nAs promised, I have directly attached the original PDF summary of the [Previous Project] architecture we discussed for your review over the weekend.\n\nLooking forward to potentially collaborating heavily in the future.\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Send it exactly within 6 to 12 hours. Because everything is digital, hiring managers move rapidly. Land in their inbox the exact same day they virtually interviewed you.",
      "Reference the remote environment. If you are applying for a fully remote position, subtly remind them of your 'experience managing large projects autonomously.'",
      "Attach work immediately. If you casually mentioned a massive success during the video call, use the thank you email to attach hard proof (a deck or PDF) of that stated success."
    ],
    faq: [
      { question: "Should I mention my cat jumping on the keyboard?", answer: "Yes! If an organic, funny moment happened during the Zoom call (like a pet interruption), briefly mentioning it in the email builds massive, warm rapport." },
      { question: "What if the Zoom connection was terrible?", answer: "Apologize briefly for the tech issues, but do not dwell on it. Say: 'Despite the connection issues, I loved learning about X!'" },
      { question: "Do I email everyone on the Zoom call?", answer: "Yes. Use LinkedIn to find their individual corporate emails, or ask the recruiter to explicitly forward your note to every silent participant." }
    ]
  }
];

const out = [...data, ...newTemplates];
fs.writeFileSync(file, JSON.stringify(out, null, 2));
