const fs = require('fs');
const file = 'src/data/templates.json';
const data = JSON.parse(fs.readFileSync(file, 'utf-8'));

const newTemplates = [
  {
    slug: 'enterprise-sales-email-template',
    title: 'Enterprise Sales Cold Email Templates',
    description: 'Close massive corporate deals. Use these highly customized enterprise sales email templates to penetrate Fortune 500 accounts and book meetings with C-Suite executives.',
    intro: 'Selling into the enterprise is fundamentally different from selling to mid-market SMBs. When you target a Fortune 500 company, you are not pitching a single founder who can immediately write a check; you are navigating a multi-layered, highly bureaucratic buying committee consisting of the CTO, VP of Engineering, Procurement, and Legal. Blasting them with generic cold emails detailing your software\'s features will result in instant deletion. Enterprise executives do not care about features; they only care about massive risk mitigation, strategic alignment, and enormous financial ROI.\n\nA masterclass enterprise cold email is profoundly customized. You must heavily research the account before hitting send. Reference their most recent terrifying quarterly earnings call or a massively ambitious strategic initiative their CEO just announced publicly in the press. Your objective in the first email is not to close a six-figure deal; your sole objective is to secure a 15-minute exploratory chat with a Vice President by proving you deeply understand the bespoke macro-challenges currently threatening their department.\n\nDeploy the rigorous enterprise templates below to bypass heavily fortified corporate gatekeepers. These scripts prioritize hyper-personalization and strategic business acumen over generic feature-dumping.',
    templates: [
      "Subject: [Company Name]'s Q3 push for [Specific Initiative]\n\nHi [Executive Name],\n\nI was intensely reviewing [Company Name]'s recent Q2 earnings transcript this morning. When your CEO mentioned the explicit goal of aggressively reducing [Specific Cost/Metric] by 15% before year-end, I immediately thought of your team.\n\nAs the VP of [Department], that immense operational burden likely falls heavily on your shoulders.\n\nAt [Your Company Name], we strictly focus on helping enterprise [Industry] organizations exactly like yours permanently eliminate [Specific Pain Point]. We recently partnered with [Competitor/Similar Enterprise] to completely overhaul their [System], resulting in a verifiable $4M reduction in annual OPEX.\n\nI am not looking to pitch you blindly. If reducing [Metric] is a Tier 1 priority for your department right now, I’d love to share the exact 3-step technical blueprint we used with [Competitor].\n\nAre you open to a brief 10-minute executive briefing next week?\n\nBest regards,\n[Your Name]",
      "Subject: Re: Next Steps / [Company Name] + [Your Company Name]\n\nHi [Executive Name],\n\nSince you are actively spearheading the [Publicly Announced Project] integration at [Company Name], I wanted to quickly put [Your Company Name] on your radar.\n\nMost enterprise [Job Titles] I currently speak with are terrified that migrating their legacy systems to the cloud will cause massive data compliance breaches. \n\nWe built a highly secure, SOC2 Type II compliant [Software Type] that completely automates this transition without risking a single byte of customer data. We actually just successfully migrated [Major Enterprise Client] manually in under 14 days.\n\nIf the sheer technical risk of migration is currently delaying your launch window, would you be strongly opposed to briefly reviewing our architecture over a quick coffee chat?\n\nCheers,\n[Your Name]",
      "Subject: Idea regarding [Company Name]'s recent acquisition\n\nHi [Name],\n\nI saw the massive news on TechCrunch this morning regarding [Company Name]'s aggressive acquisition of [Startup Name]. Massive congratulations to the entire leadership team!\n\nAs you begin the painful process of merging two entirely separate [Department] tech stacks over the next few months, you will likely hit enormous friction with [Specific technical bottleneck].\n\nI handle Strategic Accounts at [Your Company]. My team specifically helps enterprise leaders seamlessly consolidate their fractured [Software] licenses to avoid massive duplicate billing during massive M&A events.\n\nIf integrating the tech stack quickly is on your roadmap, let's chat for 15 minutes next week.\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Hunt for trigger events. An enterprise company hiring a brand new VP, missing an earnings target, or acquiring a company gives you a massive, highly relevant excuse to organically reach out.",
      "Target the actual decision-makers. Do not email a junior manager. Email the 'VP of IT' or 'Director of Engineering'—the people who actually control the $250k budget.",
      "Never attach a PDF. Enterprise spam filters will automatically quarantine any cold email from an external domain containing a massive attachment."
    ],
    faq: [
      { question: "How long is a typical enterprise sales cycle?", answer: "Usually 6 to 18 months. You must consistently and politely nurture the account over multiple quarters using highly relevant insights." },
      { question: "Should I mention my software's price?", answer: "Never in a cold email. Enterprise pricing is heavily customized based on seat count, implementation fees, and compliance requirements. Focus purely on value." },
      { question: "What if they tell me to contact Procurement?", answer: "This is actually a massive win! Reply stating: 'Absolutely, I will reach out to them today. Who should I mention directed me to them?'" }
    ]
  },
  {
    slug: 'saas-contract-renewal-email',
    title: 'SaaS Contract Renewal Email Templates',
    description: 'Prevent costly churn. Use these strategic SaaS contract renewal email templates to secure annual renewals smoothly without aggressive discounting.',
    intro: 'In the SaaS industry, acquiring a new massive enterprise account is exhilarating, but retaining them at the end of their 12-month annual contract is where true compounding revenue is built. When a major client approaches the 30-day renewal window, massive anxiety ensues for the Customer Success team. If the client has not actively logged into the platform in months, they will aggressively churn. Even if they are heavy power users, their CFO might suddenly demand a massive 20% discount just to sign the renewal paperwork.\n\nA brilliant contract renewal email is entirely proactive, not reactive. You must mathematically prove the massive return on investment (ROI) your software generated over the past year before you ever explicitly ask for their money again. Do not send a generic automated invoice stating "Your contract is expiring." Send a deeply personalized executive summary detailing exactly how many hours your tool saved their team, the specific feature they utilized most frequently, and a roadmap of the exciting new features launching next quarter that they will exclusively benefit from.\n\nUse the tested renewal sequences below to seamlessly transition Annual Contract Value (ACV) from year one into year two. These scripts completely eliminate billing friction and reaffirm the client’s purchasing decision.',
    templates: [
      "Subject: Your upcoming [Company Name] renewal & account review\n\nHi [Client/Champion Name],\n\nCan you believe it has almost been a full year since we officially deployed [Product Name] across the [Client Company] team?\n\nBecause your annual contract is set to renew on [Renewal Date], I wanted to send over a quick impact analysis. Over the past 12 months, your team has aggressively leveraged the platform to completely automate [Number] tasks, securely saving your engineering department roughly [Number] hours of manual labor.\n\nTo ensure we aggressively maintain this momentum into Year 2, I highly recommend we hop on a brief 15-minute strategic alignment call next week. I’d love to walk you through our upcoming Q3 product roadmap and ensure our priorities perfectly match yours.\n\nUnless you need to heavily adjust your licensed seat count, the current contract will smoothly auto-renew at your existing rate in 30 days.\n\nLooking forward to catching up!\n\nBest regards,\n[Your Name]",
      "Subject: Action Required: Updating your [Company Name] Annual Plan\n\nHi [Client Name],\n\nI hope your Q2 is finishing incredibly strong!\n\nI’m writing because your annual subscription for the [Platform Name] Enterprise tier is officially up for renewal on [Date].\n\nBefore I route the final Docusign to your procurement team for signature, I wanted to proactively review your current usage metrics. Currently, your team is highly utilizing 48 of your 50 purchased seats. \n\nIf you plan to heavily expand the team next quarter, we can easily proactively upgrade you to the 100-seat tier now to lock in a massive volume discount.\n\nLet me know if you would like me to draft a new proposal, or if I should simply generate the standard renewal for the existing 50 seats.\n\nCheers,\n[Your Name]",
      "Subject: Important details regarding your [Product] subscription\n\nHi [Client Name],\n\nI am reaching out quickly regarding your [Product Name] annual contract renewing in exactly 60 days.\n\nOver the last year, you have been one of our absolute best power users of the [Specific Feature] module. Because we are rolling out a massive pricing increase for all new customers starting next month, I wanted to personally assure you that your account is completely \"grandfathered\" in.\n\nYour renewal invoice on [Date] will exclusively reflect your original negotiated rate.\n\nIf you need the official invoice routed directly to an alternate accounting email address this year, please let me know!\n\nThanks for a fantastic year of partnership,\n[Your Name]"
    ],
    tips: [
      "Start early. Never send the renewal notice exactly 3 days before the contract expires. Send a '90-Day Usage Check-In' followed by a formal 30-Day Renewal Notice.",
      "Acknowledge the Procurement team. Often, your 'Champion' (the person who loves your software) does not sign the checks. Make the email easily forward-able to their CFO.",
      "Defend the price proactively. By highlighting their specific usage data, you silently justify the immense five-figure price tag before they can even ask for a discount."
    ],
    faq: [
      { question: "What if they suddenly ask for a 20% renewal discount?", answer: "Never give a discount without a trade. Reply: 'I cannot discount the core software, but if you sign a 2-year agreement today instead of 1-year, I can waive the price increase entirely.'" },
      { question: "Should I call them instead of emailing?", answer: "Yes! If the ACV (Annual Contract Value) exceeds $20k, always conduct a formal 'Executive Business Review' (EBR) over Zoom 60 days prior to renewal." },
      { question: "What if it is an auto-renewing contract?", answer: "Still email them. Hiding an auto-renewal in the fine print and legally trapping a client who forgot to cancel destroys your company's long-term market reputation." }
    ]
  },
  {
    slug: 'saas-pricing-negotiation-email',
    title: 'SaaS Pricing Negotiation Emails',
    description: 'Hold the line on your margins. Utilize these incredibly strategic SaaS negotiation email templates to handle fierce procurement teams asking for massive discounts.',
    intro: 'You spent four incredibly grueling months navigating a massive Fortune 500 company’s buying committee. The engineering team is begging to buy your software. You finally send over the $150,000 annual contract, and immediately, their ruthless Procurement team emails back demanding a completely unreasonable 40% discount. Welcome to enterprise SaaS negotiations. The procurement department’s sole job is to aggressively test your pricing integrity; if you instantly capitulate and drop your price, you signal that your software is a cheap commodity with massive margins.\n\nA masterclass SaaS pricing negotiation email relies entirely on the principle of "Trade, never Cave." You must remain highly professional while aggressively defending the mathematical value of your product. Never give a blanket discount purely because they asked. If you must lower the final cash price to save a massive deal, you must aggressively extract equal value in return: demand an upfront annual cash payment instead of quarterly terms, require them to sign a multi-year lock-in agreement, or force them to serve as a heavily visible public case study upon successful launch.\n\nUtilize the heavily battle-tested negotiation templates below to confidently push back against procurement teams. These scripts protect your company\'s ARR (Annual Recurring Revenue) while closing deals smoothly.',
    templates: [
      "Subject: Re: Pricing Proposal for [Company Name]\n\nHi [Procurement Lead Name],\n\nThank you for reviewing the initial [Product Name] proposal.\n\nI completely understand the strict internal mandate to aggressively optimize your Q3 software budget. While we cannot accommodate a massive 30% reduction on our core Enterprise user licenses, I am highly committed to getting this deal across the finish line for your engineering team.\n\nIf [Company Name] is willing to commit to a 24-month agreement (rather than the standard 12 months) and agrees to provide a brief video testimonial 90 days post-launch, I can secure internal executive approval to heavily discount the massive $15,000 one-time implementation fee entirely to zero.\n\nWould this restructuring align better with your immediate upfront budget constraints?\n\nBest regards,\n[Your Name]",
      "Subject: Re: [Your Company] Contract Redlines\n\nHi [Lead/Champion Name],\n\nGreat speaking with Procurement today.\n\nWe generally do not discount the core [Software Name] subscription because the immense ROI generated by the [Specific High-Tier Feature] mathematically pays for the software itself within the first 60 days.\n\nHowever, I want to ensure we absolutely respect your financial guardrails. Rather than discounting the Enterprise plan, what if we officially downgrade the proposal to our standard 'Professional Tier'? \n\nThis removes complex active directory integrations and dedicated VIP support, but it drops the annual total to perfectly match your target $50k budget ceiling.\n\nLet me know how you’d like to creatively proceed!\n\nCheers,\n[Your Name]",
      "Subject: Re: Budget Approval for [Product Name]\n\nHi [Name],\n\nI appreciate you being incredibly transparent regarding your strict budget constraints for this quarter.\n\nTo bridge the small financial gap here without gutting the essential features your team desperately needs, I can offer an alternative payment structure. If your finance team is willing to pay the entire annual contract completely upfront via wire rather than our standard Net-60 quarterly billing, I can instantly apply a formal 10% cash discount to the bottom line.\n\nIf this works, I will immediately route the updated Docusign so we can begin the technical implementation on Monday.\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Remove features to lower the price. If they demand a cheaper price, cheerfully offer a vastly inferior version of the product. Often, the Champion will magically 'find the budget' because they desperately want the premium features.",
      "Leverage end-of-quarter pressure. If it is the last week of the month, explicitly state: 'This massive discount is highly contingent on the contract being legally executed by 5 PM this Friday.'",
      "Do not negotiate against yourself. Give them exactly one counter-offer, then stay completely silent. Let them sweat."
    ],
    faq: [
      { question: "Why do enterprise companies always ask for a discount?", answer: "Procurement managers are literally bonused on how much money they save the company. Asking you for a 30% discount is frequently a blind, automated script they run on every single vendor." },
      { question: "Is asking for a Case Study actually valuable?", answer: "Incredibly valuable. Having a Fortune 500 company publicly endorse your startup on video will single-handedly help you close 10 more deals next year." },
      { question: "What if they hold completely firm?", answer: "If they demand a 50% discount and threaten to walk, let them walk. Taking on unprofitable, highly demanding enterprise clients will violently bankrupt your startup's support resources." }
    ]
  },
  {
    slug: 'b2b-partnership-proposal-email',
    title: 'B2B Strategic Partnership Proposal Emails',
    description: 'Unlock massive distribution. Use these highly strategic B2B partnership email templates to pitch joint ventures, co-marketing webinars, and deep technical integrations to massive companies.',
    intro: 'Scaling a B2B startup purely through expensive paid advertising is a brutal, high-friction endeavor. The most efficient strategy for exponential growth is executing a massive strategic partnership with an established company that already possesses the exact audience you desperately want to reach. If you sell accounting software, partnering with a massive payroll provider integrates you directly into their highly trusted ecosystem. However, massive companies receive dozens of "Let\'s partner!" emails daily. If you sound like a desperate startup begging for their email list, they will instantly delete your email.\n\nA masterclass B2B partnership proposal is ruthlessly framed around mutual asymmetric value. Do not pitch how great your product is. Pitch exactly how your specific product solves a massive retention or feature gap currently hurting their ecosystem. You must fundamentally answer their only internal question: "How does this highly strategic partnership make us substantially more money or permanently lower our aggressive churn rate?" Make the technical execution of the partnership appear entirely frictionless.\n\nUtilize the highly sophisticated collaboration templates below to pitch massive channel partnerships, co-branded marketing campaigns, and deep API integrations to industry giants. These scripts bypass standard rejection by explicitly proposing an entirely undeniable, mathematically sound business case.',
    templates: [
      "Subject: Strategic Partnership Idea: [Your Company] + [Their Company]\n\nHi [Name],\n\nI have heavily admired the massive market penetration the [Their Company] team has achieved in the [Niche] space this year. \n\nI am the Head of Partnerships at [Your Company]. We have built a highly specialized tool that completely automates [Specific Pain Point]. \n\nIn analyzing your current feature set, I noticed you do not currently offer a native [Feature Type] solution for your Enterprise users. Because our respective user bases heavily overlap, I strongly believe a native API integration between our platforms would drastically lower your current user churn by creating a much stickier, comprehensive ecosystem.\n\nWe are fully prepared to aggressively dedicate our engineering resources to build the integration entirely for free on our end.\n\nAre you open to a brief 15-minute chat next week to explore the technical alignment?\n\nBest regards,\n[Your Name]",
      "Subject: Co-Marketing Opportunity / [Topic] Webinar\n\nHi [Head of Marketing Name],\n\nI am a massive fan of the high-quality content engine your team is currently running at [Their Company Name].\n\nI run marketing for [Your Company Name], a platform targeting [Specific Audience]. We are actively planning a massive, highly promoted virtual webinar next month focused entirely on 'How to massively scale [Specific Industry Metric]'.\n\nBecause your team are the preeminent experts in [Their Niche], I would absolutely love to have one of your executives join us as our premier guest speaker.\n\nWe will drive roughly 5,000 highly qualified registrants via our own massive paid ad budget, giving your brand enormous free visibility. In return, we would just ask that you send one brief email blast to your list promoting the event.\n\nLet me know if this sounds like a win-win for your Q3 pipeline!\n\nCheers,\n[Your Name]",
      "Subject: Joint venture opportunity for [Their Company] users\n\nHi [Name],\n\nI wanted to reach out regarding a potential massive value-add for your existing [Their Product Name] user base.\n\nAt [Your Company], we provide premium [Service/Software]. We recently successfully partnered with [Similar Company in their space], offering their users a highly exclusive, 30% lifetime discount on our platform. In return, we kicked back a 20% recurring revenue share directly to [Similar Company] for every single paid signup.\n\nIt generated an entirely new, highly lucrative revenue stream for them with absolutely zero operational overhead.\n\nSince your audience heavily struggles with [Pain Point], I’d love to explore launching the exact same highly profitable revenue-share campaign securely with you.\n\nAre you available for a quick exploratory call on Tuesday?\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Pitch 'Integrations' for SaaS. If you want a massive SaaS company to care about you, offer to build a native integration for them that makes their software 10x more valuable to their users.",
      "The 'Co-Marketing' Trojan Horse. Proposing a joint webinar is the easiest way to secure a first meeting. It is incredibly low-risk for them, provides massive value, and builds the deep trust required for later, more complex technical partnerships.",
      "Don't aim too high initially. If you have 0 users, do not pitch Salesforce. Pitch a company that is roughly 2x to 3x your current size for the highest probability of an enthusiastic 'Yes!'"
    ],
    faq: [
      { question: "Who do I send a partnership pitch to?", answer: "Search LinkedIn for 'Head of Partnerships', 'Director of Business Development', or 'Channel Manager' at the specific target company. If they are small, email the CEO." },
      { question: "Should I include a slide deck in the cold email?", answer: "No. The objective of the first email is strictly to secure the 15-minute introductory call. Do not overwhelm them with a massive 20-slide PDF." },
      { question: "How do I ensure they don't just steal my idea?", answer: "If you are pitching a massive, highly proprietary technical integration, always demand a standard Mutual Non-Disclosure Agreement (MNDA) immediately before jumping on the formal discovery call." }
    ]
  },
  {
    slug: 'enterprise-software-implementation-kickoff-email',
    title: 'Enterprise Software Implementation Kickoff Email',
    description: 'Ensure a smooth deployment limit technical chaos. Use these implementation templates to onboard massive corporate clients.',
    intro: 'Closing an enterprise deal is only the beginning. The implementation phase is a critical turning point; if the deployment fails, the client churns. Set the tone immediately with an organized, reassuring kickoff email.',
    templates: [
      "Subject: Welcome! [Project Name] Implementation Kickoff\n\nHi [Executive Name],\n\nThank you for choosing [Your Company]. We are thrilled to kick off the [Project Name] implementation.\n\nBelow is our secure link to the initial technical intake form. Please have your IT team complete this by Friday so we can begin provisioning your dedicated environments.\n\nLooking forward to our kickoff sync!\n\nBest,\n[Your Name]",
      "Subject: Next Steps: [Company] + [Your Company]\n\nHi [Name],\n\nWe are ready to begin drafting the massive data migration plan. I have attached a brief 1-page overview of the architecture we will deploy.\n\nLet me know when your lead engineer is available for a 20-minute alignment call.\n\nCheers,\n[Your Name]",
      "Subject: Kickoff Agenda & Prep\n\nHi [Name],\n\nTo ensure our kickoff call tomorrow is incredibly productive, please review the attached slide deck detailing the exact 3-phase rollout strategy.\n\nSee you tomorrow at 10 AM!\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Keep the initial technical requests organized to prevent overwhelming their IT team.",
      "Provide clear timelines for deliverables.",
      "Establish who the technical point of contact is."
    ],
    faq: [
      { question: "Should I include the CEO?", answer: "No, primarily keep the communication to the direct VP or technical lead." },
      { question: "What if implementation is delayed?", answer: "Communicate clearly immediately to adjust the timeline." },
      { question: "Do I need a kickoff meeting?", answer: "Absolutely. A 45-minute sync prevents a massive failure later." }
    ]
  }
];

const out = [...data, ...newTemplates];
fs.writeFileSync(file, JSON.stringify(out, null, 2));
