const fs = require('fs');
const file = 'src/data/templates.json';
const data = JSON.parse(fs.readFileSync(file, 'utf-8'));

const newTemplates = [
  {
    slug: 'second-follow-up-email-after-no-response',
    title: 'The Perfect Second Follow-Up Email After No Response',
    description: 'Learn exactly what to say when a prospect ignores you. Boost your reply rates with these strategic second follow-up email templates.',
    intro: 'Silence is the most common response in professional communication. When an important prospect, hiring manager, or client fails to reply to your initial outreach, it is natural to feel anxious or assume they are entirely uninterested. However, in the vast majority of cases, they simply opened your email while walking into a meeting, mentally noted to reply later, and completely forgot. The second follow-up email is statistically the most critical email in any outbound sequence, often generating higher reply rates than the initial cold email.\n\nThe most fatal mistake when sending a second follow-up is sending the dreaded "Just checking in" or "Just bubbling this to the top of your inbox." These phrases provide zero additional value and read as mildly annoying demands for attention. A masterful second follow-up must be a value-add touchpoint. Keep the email incredibly brief (under 3 sentences), pivot slightly from your original angle, and provide a new piece of compelling information—such as a relevant case study, an insightful industry article, or a restructured, lower-friction question.\n\nUse the customized templates below to gracefully re-engage cold prospects. Whether you are following up on a sales pitch, a networking request, or a project proposal, these templates are designed to elicit a response without coming across as desperate or pushy.',
    templates: [
      "Subject: Re: [Original Subject Line]\n\nHi [Name],\n\nI know how quickly inboxes can back up, so I just wanted to send a quick follow-up to my previous email.\n\nI actually thought of you this morning because we just published a new case study showing exactly how [Similar Company/Competitor] utilized our platform to increase their [Metric] by [X]%. I thought it might be highly relevant to your Q3 goals.\n\nYou can read the brief case study here: [Link].\n\nIf exploring this is a priority for you right now, let me know if you have 10 minutes next week to chat.\n\nBest,\n[Your Name]",
      "Subject: Re: [Original Subject Line]\n\nHi [Name],\n\nI’m reaching back out because I am highly confident that we can help [Company Name] solve your current [Specific Pain Point] bottleneck.\n\nTo make things as easy as possible, I recorded a customized, 2-minute video walkthrough showing exactly how our solution would integrate directly into your existing workflow to save you [Time/Money].\n\nTake a quick look here: [Link to Video].\n\nLet me know your thoughts!\n\nCheers,\n[Your Name]",
      "Subject: Re: [Original Subject Line]\n\nHi [Name],\n\nHope you are having a great week.\n\nI wanted to quickly bump this thread. Since my last email, we rolled out a massive update to our [Feature Name], making it significantly easier to [Action/Benefit].\n\nIs solving [Specific Problem] still on your roadmap for this quarter, or should I reach back out closer to the end of the year?\n\nBest regards,\n[Your Name]",
      "Subject: Re: [Original Subject Line]\n\nHi [Name],\n\nJust a quick note to follow up on the proposal I sent over last Tuesday.\n\nI understand your team is likely incredibly busy wrapping up the quarter. If you need any additional documentation, clarification on the pricing structure, or references from past clients to help make your decision, please let me know.\n\nLooking forward to hearing from you.\n\nBest,\n[Your Name]",
      "Subject: Re: [Original Subject Line]\n\nHi [Name],\n\nFollowing up on my previous note. \n\nI totally understand if this isn't a priority for your team right now. If it makes more sense for me to touch base with a different member of the [Department] team regarding this initiative, please let me know who might be best to connect with.\n\nThanks,\n[Your Name]"
    ],
    tips: [
      "Always reply in the same email thread to maintain context so they can easily scroll down to read your original pitch.",
      "Wait at least 3 to 4 full business days before sending your second follow-up to avoid appearing overly aggressive.",
      "Provide a specific 'out'. Asking 'Should I pause my outreach for now?' often triggers a highly honest, polite response."
    ],
    faq: [
      { question: "Why do people say 'Just checking in' is bad?", answer: "It is inherently selfish. It proves you have nothing new or valuable to say, and you are simply demanding they do the work of responding to you." },
      { question: "If they don't reply to the second email, is it over?", answer: "Not in sales. A standard B2B sales sequence usually encompasses 4 to 6 touches over a month before pausing." },
      { question: "Should I change the subject line?", answer: "No. Reply directly to your original email string so the subject line simply gains a 'Re:' prefix. This maintains context." }
    ]
  },
  {
    slug: 'third-follow-up-email-sales',
    title: 'The Third Follow-Up Email (Sales & B2B Outreach)',
    description: 'Keep the deal alive. Use these third follow-up email sales templates to re-engage silent prospects and push for a definitive answer.',
    intro: 'Sending the third follow-up email in a sales sequence is often a psychological hurdle. By the time a prospect has ignored your initial cold email and your second follow-up, it is easy to assume they are definitively saying "No." However, data proves otherwise. In complex B2B sales cycles, decision-makers are notoriously overwhelmed. They often require three, four, or even five touchpoints before a message finally reaches them at the precise moment they are actively experiencing the problem you solve.\n\nThe strategy for a third sales follow-up email is a combination of extreme brevity and a subtle push for a definitive answer. You have already pitched your product and provided value-add content in previous emails; now, you must clarify their stance. The third follow-up is an excellent place to utilize the "Permission to Close" framework. Simply ask if this project has been deprioritized, or if you should temporarily pause your outreach. By giving them permission to say "No," you remove the social friction, which ironically often prompts them to reply with a "Yes, sorry, I\'ve just been swamped!"\n\nUse the tested sales templates below to execute your third touchpoint effectively. These templates focus on generating a definitive "Yes" or "No", saving you from wasting time on dead prospects while successfully re-engaging busy executives.',
    templates: [
      "Subject: Re: [Original Subject Line]\n\nHi [Name],\n\nI want to respect your inbox, so I'll keep this incredibly brief.\n\nTypically, when I don't hear back, it means that solving [Specific Pain Point] simply isn't a major priority for your team this quarter, or you are currently locked into a contract with another vendor.\n\nIs that the case here? If so, just let me know and I will happily pause my outreach so I stop cluttering your inbox.\n\nBest,\n[Your Name]",
      "Subject: Re: [Original Subject Line]\n\nHi [Name],\n\nI know you are incredibly busy, so I'm not looking for a lengthy reply.\n\nSince we last spoke, I actually had my team run a deeper analysis on [Company Name]’s current setup. We identified a potential inefficiency regarding how your team handles [Specific Process] that is likely costing you around [Estimated Dollar Amount] annually.\n\nIf you have 5 minutes this week, I’d love to show you our findings. If this isn't a focus area right now, completely understood.\n\nCheers,\n[Your Name]",
      "Subject: Re: [Original Subject Line]\n\nHi [Name],\n\nJust floating this to the top of your inbox one last time.\n\nIf improving your [Metric/Area] isn't on the roadmap for [Company Name] right now, no worries at all. \n\nShould I reach back out closer to Q4, or is there someone else on the [Department Name] team who is better suited to evaluate [Software/Solution]?\n\nThanks,\n[Your Name]",
      "Subject: Re: [Original Subject Line]\n\nHi [Name],\n\nHope your week is off to a great start. \n\nI wanted to circle back regarding my previous emails about overhauling your [Service Area]. I completely understand if this project has been put on the back burner for now.\n\nFor future reference, I’m attaching a brief 1-page PDF detailing exactly how we helped [Similar Company] achieve [Result]. \n\nI will pause my outreach for now, but feel free to reach out whenever timing makes more sense on your end.\n\nBest regards,\n[Your Name]",
      "Subject: Re: [Original Subject Line]\n\nHi [Name],\n\nI’m guessing you’ve been swamped lately, so I’ll be quick.\n\nAre you still open to exploring a solution to automate your [Process Name], or has this initiative been tabled for the year?\n\nA quick reply of 'Yes' or 'No' is all I need!\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Embrace the 'No'. Giving them a polite, guilt-free way to reject you saves both of you time and stops the sequence gracefully.",
      "Keep this email aggressively short. Two or three sentences max.",
      "Never show annoyance or passive-aggression that they haven't replied to your previous emails."
    ],
    faq: [
      { question: "Is the third email the 'Break Up' email?", answer: "Not necessarily. A third follow-up usually asks for direction. The 'Break Up' email (the final email in a sequence) usually happens at touch 4 or 5." },
      { question: "What is the timeline for the third follow-up?", answer: "A common cadence is: Email 1 (Day 1), Email 2 (Day 4), Email 3 (Day 9 or 10)." },
      { question: "Why ask them to reply with just 'Yes' or 'No'?", answer: "It removes cognitive load. Telling a busy executive exactly how simple the reply needs to be drastically increases the chances they will actually hit send." }
    ]
  },
  {
    slug: 'follow-up-after-final-interview-no-response',
    title: 'Follow Up Email After a Final Interview (No Response)',
    description: 'Nervous after a final interview? Use these polite follow-up emails to ask for an update from the hiring manager without sounding desperate.',
    intro: 'Completing a final round interview is an exhilarating milestone, but the subsequent waiting period can be incredibly agonizing. If the hiring manager promised an update by Friday and Monday rolls around with complete silence, panic often sets in. It is crucial to remember that a delayed response rarely signifies a rejection. Hiring managers are juggling internal approvals, budget sign-offs, reference checks, and their own daily responsibilities. The hiring process almost always takes longer than the company initially projected.\n\nWhen sending a follow-up email after a final interview, your tone must be exceptionally polite, patient, and entirely devoid of frustration. The goal is to reaffirm your profound enthusiasm for the role while gently prompting them for a timeline update. Do not demand an immediate answer. Instead, briefly restate why you are excited about the key challenges discussed in the final interview, ask if they need any further documentation or references from you, and inquire about their updated timeline.\n\nBelow are customized templates designed for the post-interview waiting period. Use them to gently nudge the HR team, check in after a missed deadline, or update them professionally if you have received a competing job offer.',
    templates: [
      "Subject: Checking in - [Your Name] for [Job Title] role\n\nHi [Hiring Manager's Name],\n\nI hope you’re having a great week.\n\nI’m reaching out to check in on the status of my candidacy for the [Job Title] position. I thoroughly enjoyed our final interview last Tuesday, and the conversations regarding [Specific Project Discussed] only increased my excitement about the potential of joining your team.\n\nPlease let me know if you need any additional information, work samples, or references from me to help finalize your decision.\n\nI look forward to hearing an update when you have a moment.\n\nBest regards,\n[Your Name]",
      "Subject: Following up: [Your Name] / [Job Title] interview\n\nHi [Recruiter/HR Contact],\n\nI hope all is well!\n\nDuring my final interview last week, the team mentioned they were hoping to make a final decision by [Date passed]. I know how complex the hiring process can be, so I completely understand if that timeline has shifted!\n\nI remain incredibly interested in the [Job Title] role and the opportunity to contribute to the [Specific Department] team.\n\nCould you kindly let me know if there is an updated timeline on your end?\n\nSincerely,\n[Your Name]",
      "Subject: Update on my timeline regarding the [Job Title] role\n\nHi [Hiring Manager's Name],\n\nI hope your week is going well.\n\nI am reaching out to provide a quick update on my end. I remain incredibly passionate about the [Job Title] position at [Company Name] and truly believe my background is a perfect fit for the challenges we discussed.\n\nHowever, I recently received a competing job offer from another company. Because [Company Name] remains my absolute first choice, I wanted to respectfully check in on your timeline before I am required to make a final decision by [Deadline Date].\n\nPlease let me know if you have any updates on your process.\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Wait at least 2 full business days after their stated deadline before sending a follow-up.",
      "Always reply to the existing email thread with the recruiter or hiring manager to keep the context intact.",
      "If you have a competing offer, transparently stating your decision deadline is a highly effective way to force an immediate response."
    ],
    faq: [
      { question: "Who should I email: the recruiter or the hiring manager?", answer: "Email the internal recruiter or HR representative first. They manage the timeline. Only email the hiring manager directly if they told you to contact them specifically." },
      { question: "What if they don't respond to the follow-up?", answer: "Wait one more full week and send a second follow-up. If they ignore two polite check-ins after a final interview, assume they selected another candidate." },
      { question: "Does following up make me look annoying?", answer: "No. Sending one polite follow-up after a missed timeline demonstrates high professional standards, proactive communication, and genuine interest in the role." }
    ]
  },
  {
    slug: 'polite-follow-up-email-after-proposal',
    title: 'Polite Follow-Up Emails After Sending a Proposal',
    description: 'Close more deals with these polite, professional follow-up email templates designed to nudge clients after sending a project proposal or quote.',
    intro: 'Sending a customized business proposal, freelance quote, or vendor contract is a massive milestone. However, the momentum often stalls abruptly once you hit send. Business owners and executives are notoriously busy, and while they may be excited about your proposal, reviewing contracts and securing necessary budget approvals always takes a backseat to their daily operational fires. Leaving the deal entirely in their hands is a massive mistake; a professional follow-up is required to push the deal across the finish line.\n\nA masterful follow-up email to a proposal must walk a delicate line: it must be proactive without being pushy. The most effective strategy is to assume that the delay is caused by complexity, not rejection. Reach out with a helpful, consultative tone. Instead of demanding to know if they have signed it yet, ask if they require any points of clarification, if they need adjustments to the scope of work to better fit their budget, or if they need additional materials to present to their board.\n\nUse the customized templates below to gracefully follow up on lingering quotes, proposals, and contracts. These refined scripts will help you maintain your professional leverage while maintaining positive momentum to close the deal.',
    templates: [
      "Subject: Checking in regarding the [Project Name] proposal\n\nHi [Client Name],\n\nI hope you are having a fantastic week!\n\nI’m reaching out to softly check in on the proposal I sent over last [Day of week] regarding the [Project Name] initiative.\n\nI know reviewing scopes of work can be incredibly time-consuming. Have you had a chance to review the document with your team? Please let me know if you have any questions regarding the project phases or if you need any adjustments to the current timeline to better fit your Q3 goals.\n\nI’m happy to hop on a quick 10-minute call later this week if that is easier for you.\n\nBest regards,\n[Your Name]",
      "Subject: Re: Proposal for [Company Name]\n\nHi [Client Name],\n\nHope all is well.\n\nFollowing up on the quote I provided for the upcoming [Service Type] project. Since I know these decisions often require internal alignment, I wanted to see if you needed any additional information from me to present to the leadership team?\n\nI’m also happy to hop on a quick call to walk through the pricing structure or adjust the scope if budget constraints have shifted since we last spoke.\n\nLet me know your thoughts when you have a moment.\n\nCheers,\n[Your Name]",
      "Subject: Next Steps — [Project Name]\n\nHi [Client Name],\n\nJust floating this email back to the top of your inbox.\n\nI am incredibly excited about the potential of partnering with [Company Name]. To ensure we can hit your desired launch date of [Desired Date], we would ideally need to finalize the contract and begin the onboarding phase by [Deadline Date].\n\nIs your team still on track to move forward this month, or has the timeline for this initiative shifted?\n\nBest,\n[Your Name]",
      "Subject: Re: Contract for [Project Name]\n\nHi [Client Name],\n\nI hope you’re having a great week.\n\nI’m reaching out because I want to ensure my team is fully prepped and allocated for your upcoming project.\n\nHave you had a chance to review the contract I sent over? If there are any specific clauses or deliverables you would like to discuss or tweak before signing, please let me know and I will gladly send over a revised version today.\n\nLooking forward to getting started!\n\nSincerely,\n[Your Name]"
    ],
    tips: [
      "Create urgency by mentioning deadlines. If they have a specific launch date, remind them that signing the proposal is necessary to meet it.",
      "Offer to modify the scope. Sometimes a client 'ghosts' because the price was too high and they are embarrassed to negotiate.",
      "Keep a consultative tone. Assume they are busy, not actively ignoring you."
    ],
    faq: [
      { question: "How soon after sending a proposal should I follow up?", answer: "Wait roughly 3 to 4 business days. Give them adequate time to read the document and discuss it internally." },
      { question: "What if the client says they are 'still reviewing it'?", answer: "Reply politely acknowledging their timeline, and ask 'Is it okay if I check back in next Wednesday?' This secures permission for your next follow-up." },
      { question: "Should I offer a discount in the follow up to close the deal?", answer: "No. Never negotiate against yourself. Wait for them to state their objections to the price before offering to adjust the scope or provide a discount." }
    ]
  },
  {
    slug: 'linkedin-message-to-hiring-manager-after-applying',
    title: 'LinkedIn Message to Hiring Manager After Applying',
    description: 'Stand out from the crowd. Send these proven LinkedIn messages to hiring managers immediately after applying for a job.',
    intro: 'Applying for a job through a standard online portal often feels like sending your resume into a black hole. Modern Applicant Tracking Systems (ATS) automatically filter out hundreds of highly qualified candidates before human eyes ever see them. To bypass this automated filtering and guarantee your application is reviewed, you must proactively reach out to the hiring manager directly on LinkedIn immediately after submitting your formal application.\n\nA direct message to a hiring manager is not a venue to paste your entire cover letter. It must be aggressively concise, respectful, and highly strategic. A winning LinkedIn outreach message states clearly that you just formally applied, highlights your one or two most impressive, highly relevant metrics, and reiterates your profound enthusiasm for the company\'s mission. By reaching out directly, you demonstrate exceptional initiative, proactive communication skills, and intense interest in the specific role—traits every hiring manager values.\n\nUtilize the optimized LinkedIn connection requests and direct message templates below to follow up on your recent applications. Customize them to highlight specific intersections between your past achievements and exactly what is requested in their job description.',
    templates: [
      "Subject: [Job Title] Application / [Your Name]\n\nHi [Hiring Manager's Name],\n\nI hope you’re having a great week! \n\nI’m reaching out because I just formally applied for the open [Job Title] position via your careers portal. I have been following [Company Name]’s recent expansion into the [Specific Industry] space and I am incredibly passionate about the work your team is doing.\n\nGiven my extensive background in [Skill 1] and my recent success scaling [Specific Project] by [X]%, I strongly believe I could deliver immediate impact to your team.\n\nI understand you are incredibly busy reviewing applications, but I would be honored to briefly discuss how my skill set aligns with your current goals. \n\nBest regards,\n[Your Name]",
      "Subject: Connecting regarding the [Job Title] role\n\nHi [Hiring Manager's Name],\n\nI noticed on LinkedIn that you are the hiring manager for the [Job Title] role. I just submitted my formal application this morning.\n\nBecause I am incredibly passionate about solving [Specific Problem the Company Solves], I wanted to personally reach out. In my previous role at [Previous Company], I successfully managed a very similar challenge, resulting in a [Huge Tangible Metric—e.g., $5M revenue increase].\n\nI would love the opportunity to bring that same strategic rigor to your team.\n\nThank you for your time, and I look forward to potentially connecting. \n\nCheers,\n[Your Name]",
      "Subject: Connection Request (Note) \n\nHi [Hiring Manager],\n\nI just applied for the [Job Title] role! Given my 5+ years of driving [Specific Result] in the [Industry] space, I’m highly confident I can help the team tackle the upcoming Q3 goals mentioned in the job description. Would love to connect and keep up with your team's work!\n\nBest,\n[Your Name]",
      "Subject: Exploring the [Job Title] role at [Company Name]\n\nHi [Recruiter/Hiring Manager Name],\n\nI see your team is currently recruiting for a [Job Title]. I just submitted my resume through the portal but wanted to introduce myself directly.\n\nMy background is heavily anchored in [Skill A] and [Skill B]. Notably, I recently led a team to [Specific Achievement], which I noticed is closely aligned with the core responsibilities of this open role.\n\nI’d welcome the chance to briefly hop on a call to see if my background aligns with what you’re looking for currently.\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Keep it brief. Hiring managers read LinkedIn messages on their phones; get to the point instantly.",
      "If you are sending a Connection Request note, you are limited to 300 characters. Make every word count.",
      "Always apply through the formal portal first so the HR team has your data properly logged."
    ],
    faq: [
      { question: "How do I find the hiring manager on LinkedIn?", answer: "Search for '[Company Name] + [Department Leader Title]' (e.g., 'Director of Engineering' if you are applying for a developer role)." },
      { question: "Should I attach my resume via LinkedIn DM?", answer: "Yes, attaching your resume as a PDF directly in the message makes it incredibly frictionless for them to review it instantly." },
      { question: "What if they read it but don't reply?", answer: "Mission accomplished. The goal was to ensure they looked at your profile and pulled your resume from the ATS system. Give them time to process the application." }
    ]
  }
];

const out = [...data, ...newTemplates];
fs.writeFileSync(file, JSON.stringify(out, null, 2));
