const fs = require('fs');
const file = 'src/data/templates.json';
const data = JSON.parse(fs.readFileSync(file, 'utf-8'));

const newTemplates = [
  {
    slug: 'email-to-schedule-a-meeting-with-ceo',
    title: 'Email to Schedule a Meeting with a CEO or Executive',
    description: 'Get past the gatekeepers. Learn how to write highly effective emails to schedule a meeting with a CEO, President, or senior executive.',
    intro: 'Getting a meeting on a CEO or senior executive’s calendar requires navigating the highest levels of corporate defense. Executive Assistants act as ruthless gatekeepers, explicitly tasked with protecting the CEO’s time from low-value interruptions. To successfully schedule a meeting with a top executive, your email must immediately telegraph executive presence, demonstrate extreme brevity, and outline a highly specific, undeniable business value (ROI) for the company.\n\nWhen emailing a CEO, never present a vague pitch like "I’d love to learn more about your goals." CEOs are solely concerned with macro-level objectives: aggressively driving revenue, slashing operational costs, mitigating massive enterprise risks, or outmaneuvering direct competitors. Your email must clearly state how you plan to help them achieve one of those four objectives within the first two sentences. Furthermore, ask for an incredibly short meeting (e.g., 10 minutes) or provide an immediate "out" by asking them to delegate the meeting to the appropriate VP or Director.\n\nThe specialized templates below are engineered for C-suite outreach. Use them to request a meeting effectively, whether you are pitching an enterprise software solution, offering an exclusive strategic partnership, or reaching out as an acquisition target.',
    templates: [
      "Subject: Idea for reducing [Company Name]'s [Specific Cost/Risk]\n\nHi [CEO Name],\n\nI’m reaching out to you directly because we are currently helping [Direct Competitor/Similar Enterprise] drastically reduce their [Specific Cost/Risk Metric] by utilizing [Unique Mechanism].\n\nI know optimizing the [Specific Department] is a core strategic initiative for [Company Name] this year. Our platform typically drives a [X]% increase in efficiency under 60 days without requiring a massive IT overhaul.\n\nAre you open to a brief 10-minute executive briefing next week regarding how we achieved this for [Competitor]?\n\nAlternatively, if [VP/Director Name] is better suited to vet this initiative, I will gladly reach out to them instead.\n\nBest,\n[Your Name]",
      "Subject: Strategic partnership / [Your Company] + [Company Name]\n\nHi [CEO Name],\n\nI am the founder of [Your Company], a [Industry] platform currently serving [Number] enterprise clients globally.\n\nI am writing to you directly because I see a massive opportunity for a strategic partnership between our organizations. Because we both deeply service the [Target Audience Persona], integrating our tech stacks would allow [Company Name] to immediately offer [New Missing Feature] to your existing user base, driving projected secondary revenue of $[Amount].\n\nIf exploring strategic acquisitions or partnerships is a priority currently, I’d love to arrange a confidential 15-minute call.\n\nBest regards,\n[Your Name]",
      "Subject: Brief intro - [Your Company] / Solving [Specific Pain Point]\n\nHi [CEO Name], \n\nI’ll keep this under 60 seconds to respect your schedule.\n\nWe provide Enterprise [Service/Software] that specifically solves the bottleneck regarding [Massive Pain Point]—which I know is consistently a top 3 priority for CEOs in the [Industry] space right now.\n\nWe recently partnered with [Impressive Client] to automate this, resulting in a [Huge Tangible Metric—e.g., $5M annualized savings].\n\nIf this aligns with your Q4 cost-saving goals, do you have 10 minutes next Thursday for a brief chat, or is there a specific VP I should connect with?\n\nSincerely,\n[Your Name]"
    ],
    tips: [
      "Keep it brutally short. Aim for less than 75 words. CEOs scan emails on their phones during transit.",
      "Offer an 'out' by asking them to introduce you to the correct department head. The 'Top-Down Referral' carries massive weight.",
      "Name-drop a direct competitor or a massive enterprise client to establish immediate peer-level credibility."
    ],
    faq: [
      { question: "Should I bypass the CEO and email the VP instead?", answer: "A 'Top-Down' approach (emailing the CEO and asking to be directed to the right VP) often guarantees a meeting because the VP is essentially 'ordered' by the CEO to speak with you." },
      { question: "What if the Executive Assistant (EA) replies?", answer: "Treat the EA with the exact same respect as the CEO. The EA controls the calendar. Reply politely offering a meeting time." },
      { question: "How many times should I follow up with a CEO?", answer: "Max 3 touches. If you push too hard, they will simply block your domain." }
    ]
  },
  {
    slug: 'price-negotiation-email-with-vendor',
    title: 'Price Negotiation Email Templates (Vendors & Suppliers)',
    description: 'Save money without burning bridges. Use these B2B price negotiation email templates to strategically counter-offer your vendors and suppliers.',
    intro: 'Negotiating pricing via email with vendors, SaaS providers, or external suppliers is a fundamental skill for maintaining healthy profit margins. Sending a negotiation over email allows you the time to meticulously reference competitor pricing, assert your budget constraints calmly, and remove the pressure of a real-time phone confrontation. However, B2B negotiations must never become antagonistic. Your supplier is your business partner; grinding them down aggressively over minor fees can result in plummeting service quality.\n\nThe most successful price negotiation emails leverage objective constraints and future value, rather than personal demands. Before countering a quote, explicitly reiterate your desire to partner with them and praise the quality of their product. Then, introduce a logical constraint—such as a rigid departmental budget, a significantly lower competing bid, or a mandate from your CFO. You must give the vendor a graceful way to lower their price without losing face. Offering to sign a longer-term contract or increasing volume in exchange for a discount is a classic, highly effective B2B negotiation strategy.\n\nUse the customized B2B negotiation templates below to secure better pricing from software vendors, negotiate a long-term supplier contract, or challenge an unexpected rate increase.',
    templates: [
      "Subject: Reviewing the proposal for [Project/Service]\n\nHi [Vendor Name],\n\nThank you for sending over the detailed proposal. We are incredibly impressed with the [Company Name] platform and firmly believe your solution is the best technical fit for our team.\n\nHowever, upon reviewing our finalized Q3 budget, the quoted price of $[Amount] per month is approximately [X]% higher than we are currently authorized to spend for this specific initiative.\n\nWe would love to sign the contract today if we can adjust the pricing to align with our $[Target Budget] monthly cap. Alternatively, if we commit to an annual upfront payment rather than monthly billing, is there flexibility to meet that number?\n\nI look forward to finding a path forward together.\n\nBest,\n[Your Name]",
      "Subject: Discussing the renewal pricing for [Company Name]\n\nHi [Vendor Name],\n\nThanks for sending over the renewal documentation for our upcoming contract. We’ve really enjoyed working with your team over the past year!\n\nI did notice that the new proposed contract includes a [X]% rate increase. While I understand the market has shifted, my CFO has mandated strict budget freezes across all operational software this year.\n\nWe would love to renew our commitment to [Company Name] for another 12 months, but we will need to keep our pricing flat at the current rate of $[Current Rate] in order to secure approval.\n\nLet me know if this is something your team can accommodate so we can process the renewal this week.\n\nCheers,\n[Your Name]",
      "Subject: Quote comparison for [Service/Product]\n\nHi [Vendor Name],\n\nThank you again for the excellent presentation yesterday.\n\nWe are currently narrowing down our final vendors for this project. While your team remains our cultural top choice, we have received a competing bid from [Competitor Name, Optional] that is offering a very similar SLA and scope for $[Competitor Lower Price].\n\nBecause we strongly prefer your platform’s UI, I wanted to reach out transparently to see if you are able to match—or come closer to—this competing quote? \n\nLet me know your thoughts.\n\nBest regards,\n[Your Name]"
    ],
    tips: [
      "Praise their product heavily first. Vendors offer discounts to clients they actually want to work with.",
      "Blame the 'Invisible Boss' (e.g., 'My CFO won't approve this'). It removes the personal friction from the negotiation.",
      "Always offer a concession. Ask for a discount in exchange for signing a multi-year deal or paying upfront in cash."
    ],
    faq: [
      { question: "Is negotiating via email better than phone?", answer: "Email is better for laying out complex math and competitor quotes logically. Use phone calls to resolve a deadlock if they email back a 'No'." },
      { question: "Can I always negotiate SaaS pricing?", answer: "Almost always, yes. Especially if you are purchasing enterprise tiers or more than 10 seats, SaaS sales reps have authorized discount margins built in." },
      { question: "What if the vendor refuses to lower the price?", answer: "Identify your Walk Away Point beforehand. If they refuse, you must decide if the product is worth the premium, or if you must walk away to their competitor." }
    ]
  },
  {
    slug: 'contract-follow-up-email-to-client',
    title: 'Contract Follow-Up Emails to Clients',
    description: 'Get the deal signed rapidly. Nudge clients politely with these professional contract follow-up email templates for freelancers and B2B sales.',
    intro: 'You have verbally won the deal, outlined the scope, and sent the official contract via Docusign. Then... crickets. Deals stalling at the contract signature phase are incredibly common. Legal departments must review the clauses, executives must sign off on the budget, or the client simply forgot in the rush of their daily crisis. While frustrating, you must not panic. A hasty, aggressive email demanding a signature can completely sour a newly formed business relationship right at the finish line.\n\nA masterclass contract follow-up email establishes gentle urgency while maintaining a deeply supportive, consultative tone. The most effective strategy is to re-anchor the client to their own goals. Remind them that the contract signature is the only barrier standing between them and the desired outcome (e.g., launching their new website by Q3, or securing their software launch date). Offer to jump on a quick call alongside their legal counsel to clarify any confusing clauses or redlines.\n\nThe templates below are tailored for gracefully pushing contracts across the finish line. Use them to follow up on Docusigns, proposals, and freelance agreements without sacrificing your leverage or sounding desperate.',
    templates: [
      "Subject: Next Steps — [Project Name] Contract\n\nHi [Client Name],\n\nI hope you’re having a fantastic week!\n\nI’m reaching out to check in on the contract I sent over last [Day of week]. I know getting internal alignment and legal review can sometimes take a bit longer than anticipated.\n\nI want to ensure my team is fully allocated to hit your desired [Project Goal] launch date next month. To reserve our sprint capacity and keep the timeline on track, we would ideally need the agreement finalized by [Deadline Date].\n\nPlease let me know if your legal team requires any redline adjustments or if you’d like to hop on a quick call to clarify any deliverables.\n\nBest regards,\n[Your Name]",
      "Subject: Checking in on the [Company Name] MSA\n\nHi [Client Name],\n\nJust floating this to the top of your inbox.\n\nWe are incredibly excited to officially kick off the [Project Name] initiative with your team. Have you had a chance to review the Master Services Agreement (MSA)?\n\nIf the pricing structure or scope needs any final tweaks to better align with your Q3 budgets, I am fully open to adjusting it. Our primary goal is ensuring this partnership is a massive win for [Company Name].\n\nLet me know your thoughts when you have a moment!\n\nCheers,\n[Your Name]",
      "Subject: Action Required: Finalizing [Software/Service] Onboarding\n\nHi [Client Name],\n\nHope all is well.\n\nI noticed the Docusign link for the [Software/Service] contract hasn’t been completed yet. \n\nBecause I want to make sure your team is fully onboarded and trained by the end of the month, I’m hoping we can finalize the paperwork this week.\n\nIf you need me to resend the secure link, or if you need any additional documentation for your procurement department, just let me know.\n\nTalk soon,\n[Your Name]"
    ],
    tips: [
      "Always tie the signature to the client's timeline. ('We need this signed so you can launch on time' works better than 'We need this signed so I can get paid').",
      "Acknowledge their internal process. Stating 'I know legal reviews take time' shows empathy and business acumen.",
      "If utilizing Docusign, click 'Send Reminder' through the software before sending a manual written follow-up."
    ],
    faq: [
      { question: "How many days should I wait before sending a contract follow up?", answer: "Wait 3 to 4 business days. Give their legal and finance teams adequate time to review." },
      { question: "What if they want to heavily redline (edit) the contract?", answer: "This is standard in Enterprise B2B. Do not panic. Send the redlines to your own internal legal team to review and negotiate the terms." },
      { question: "Should I start the work before the contract is signed?", answer: "Never. Verbal agreements hold zero weight. Do not write code, launch ads, or allocate resources until the signature is captured." }
    ]
  },
  {
    slug: 'payment-reminder-email-polite',
    title: 'Polite Payment Reminder Email Templates',
    description: 'Get paid faster without ruining client relationships. Use these highly professional, polite payment reminder email templates for overdue invoices.',
    intro: 'Chasing down unpaid invoices is arguably the most frustrating administrative task for freelancers, agency owners, and B2B companies. However, aggressive or antagonistic collection emails often damage the long-term client relationship, essentially guaranteeing that you won\'t be hired again. In the vast majority of cases, the client isn\'t maliciously withholding funds; the invoice simply got buried in their inbox, or the accounting department missed a payment run. A professional payment reminder assumes positive intent while establishing firm operational boundaries.\n\nA flawless payment reminder sequence escalates smoothly. The first touchpoint (sent the day after the due date) should be incredibly soft and helpful, assuming the invoice was simply misplaced. The second touchpoint (one week late) should be firmer, attaching the invoice directly again. The final touchpoint (14-30 days late) should professionally invoke any late-fee clauses explicitly outlined in your master contract and request an immediate status update from their accounts payable department.\n\nThe templates below provide a staggered, professional collection sequence. Use them to protect your cash flow, maintain a strict paper trail, and handle awkward financial conversations gracefully.',
    templates: [
      "Subject: Payment Reminder: Invoice #[Number] for [Project Name]\n\nHi [Client Name],\n\nI hope you’re having a great week!\n\nI’m reaching out because our accounting system flagged that Invoice #[Number] for $[Amount] was due yesterday, [Date]. \n\nI know how easily these emails can get buried, so I’ve attached another copy of the invoice for your reference. You can pay securely via credit card or ACH using the link within the PDF.\n\nIf your accounts payable team has already processed this, please disregard this note. Thank you for your continued partnership!\n\nBest regards,\n[Your Name]",
      "Subject: Overdue Notice: Invoice #[Number]\n\nHi [Client Name],\n\nHope everything is going well over at [Company Name].\n\nI am writing to respectfully follow up on Invoice #[Number] for $[Amount], which is now one week past due. \n\nCould you please let me know the current status of this payment? If there are any issues with the payment link or if you require an updated W-9 from us to process the funds, please let me know so we can resolve it immediately.\n\nI’ve attached the invoice again for your convenience.\n\nBest,\n[Your Name]",
      "Subject: Urgent: Invoice #[Number] is 30 Days Overdue\n\nHi [Client Name/Accounts Payable],\n\nI am reaching out regarding Invoice #[Number], which is now 30 days past due.\n\nAs outlined in our Master Services Agreement, invoices outstanding beyond 30 days are subject to a [X]% monthly late fee. We highly value our relationship with [Company Name] and want to avoid applying these extra charges.\n\nPlease process the payment of $[Amount] today, or let me know immediately when we can expect the wire transfer to hit our account.\n\nThank you for your prompt attention to this matter.\n\nSincerely,\n[Your Name]"
    ],
    tips: [
      "Always attach the invoice directly to the follow-up email. Do not make the client dig through their inbox to find the original link.",
      "Blame 'automated accounting software'. Saying 'Our system flagged this as unpaid' removes the personal friction from the confrontation.",
      "If the invoice is significantly overdue, explicitly CC their accounts payable (AP) department or the CFO."
    ],
    faq: [
      { question: "When should I send the first payment reminder?", answer: "Early the morning following the due date. Establishing a precedent of strict accounting encourages clients to pay you first in the future." },
      { question: "Is it legal to charge late fees?", answer: "Yes, but strictly only if late fees were explicitly outlined in the mutually signed contract before the work began." },
      { question: "What should I do if they still refuse to pay?", answer: "You must escalate. This involves stopping all active project work instantly, sending a formal 'Demand Letter', and eventually pursuing small claims court or professional collection agencies." }
    ]
  },
  {
    slug: 'declining-a-job-offer-email-template',
    title: 'How to Politely Decline a Job Offer via Email',
    description: 'Reject an offer without burning bridges. Use these polite, professional email templates to decline a job offer gracefully.',
    intro: 'Declining a formal job offer is a delicate professional maneuver. Even though you are turning down the position, you must recognize that the hiring manager and recruiting team have invested significant time, resources, and social capital into interviewing and selecting you. A blunt, dismissive rejection can severely damage your reputation within your industry. The corporate world is remarkably small; the hiring manager you reject today might be the VP of Engineering at your target company five years from now.\n\nA masterful rejection email requires three core components: profound gratitude for the offer and their time, a clear and decisive statement that you are declining (do not leave room for ambiguity), and a brief, high-level reason for your decision. You do not need to over-explain your rationale. Simply stating that you have accepted an offer that better aligns with your current long-term career goals, or that the compensation package wasn\'t a fit, is sufficient. Attempt to end the email by offering to stay connected on LinkedIn.\n\nBelow are various templates designed for declining a job offer. Whether you are accepting a competing offer, realizing the company culture isn\'t a fit, or deciding to stay at your current job, these scripts ensure you exit the process with tremendous grace.',
    templates: [
      "Subject: Job Offer - [Your Name] - [Job Title]\n\nHi [Hiring Manager's Name],\n\nThank you so much for offering me the [Job Title] position. I am deeply honored to have been selected, and I truly enjoyed learning about the incredible work your team is doing at [Company Name].\n\nAfter careful consideration, I have made the difficult decision to decline the offer at this time.\n\nI have ultimately decided to accept another opportunity that better aligns with my specific, long-term career goals regarding [Specific Field/Niche]. \n\nI want to sincerely thank you and the rest of the team for your time and transparency throughout the entire interview process. I wish you the absolute best in finding the perfect candidate for this role, and I would love to stay connected on LinkedIn.\n\nWarmly,\n[Your Name]",
      "Subject: Re: Job Offer - [Your Name]\n\nHi [Recruiter's Name],\n\nThank you again for extending the offer to join [Company Name] as a [Job Title].\n\nWhile I am a massive fan of the product and deeply respected everyone I met during the interview process, I will unfortunately be declining the position. \n\nUltimately, the compensation package does not align with my current requirements and the other offers I am fielding. \n\nI am incredibly grateful for your time and advocacy over the past few weeks. I hope our paths cross again in the future!\n\nBest regards,\n[Your Name]",
      "Subject: Thank you / Decision regarding [Job Title] role\n\nHi [Hiring Manager Name],\n\nThank you for presenting me with the offer to join [Company Name].\n\nThis was an incredibly difficult choice, as I was deeply impressed by the ambitious roadmap you outlined for the [Department Name] team. However, I have decided to decline the offer and remain with my current employer to finish a vital, ongoing project.\n\nIt was a pleasure meeting you, and I look forward to watching [Company Name]’s continued success from afar.\n\nSincerely,\n[Your Name]"
    ],
    tips: [
      "Send the email immediately after making your final decision. Do not hold the offer hostage for days, as it delays their ability to offer it to the runner-up.",
      "Keep the rejection incredibly polite but completely firm. Do not use phrases like 'I think I will decline', use 'I am declining'.",
      "Mentioning another offer is acceptable, but there is no need to name the specific competitor you are joining."
    ],
    faq: [
      { question: "Is it better to decline via phone or email?", answer: "If you spoke extensively with the hiring manager on the phone during the process, a brief phone call is the classiest move, followed immediately by an email to HR for their records." },
      { question: "Should I tell them exactly why I declined?", answer: "Keep it high-level. Stating it 'doesn’t align with my career goals' is much safer than detailing why you hated their vacation policy or office environment." },
      { question: "What if they counter-offer?", answer: "If you explicitly state in the rejection email that you are declining due to compensation, be prepared for them to immediately counter-offer with a higher salary." }
    ]
  }
];

const out = [...data, ...newTemplates];
fs.writeFileSync(file, JSON.stringify(out, null, 2));
