const fs = require('fs');
const file = 'src/data/templates.json';
const data = JSON.parse(fs.readFileSync(file, 'utf-8'));

const newTemplates = [
  {
    slug: 'follow-up-email-after-networking-event',
    title: 'Follow-Up Email After a Networking Event',
    description: 'Turn quick conversations into lasting connections. Send these professional follow-up emails after a networking event or conference.',
    intro: 'Attending a networking event or highly targeted industry conference is exhausting. You exchange dozens of business cards and have countless brief interactions. However, all that effort is entirely wasted if you fail to execute the final, critical step: the follow-up email. The vast majority of professionals collect business cards and never reach out, relying on the false assumption that swapping LinkedIn connections is sufficient. To truly convert a brief interaction into a valuable connection, you must send a highly personalized email within 48 hours.\n\nThe perfect post-networking event follow-up is simple, warm, and hyper-specific. The recipient likely met 50 other people that night. If you send a generic "Great meeting you" email, they will instantly forget who you are. Instead, you must immediately reference a specific detail from your conversation—whether you discussed a recent industry regulation, a shared hometown, or a mutual hobby. By anchoring their memory to that specific point, you ensure they recall the interaction clearly. Close the email with a very low-lift call to action, such as an invitation for a virtual 15-minute coffee chat or simply sending them a relevant article you referenced.\n\nUtilize the optimized templates below to maximize your ROI from networking events. Whether you are following up with a potential mentor, an intriguing vendor, or a senior executive, these scripts ensure your conversation translates into a tangible relationship.',
    templates: [
      "Subject: Great meeting you at [Event Name] / [Your Name]\n\nHi [Name],\n\nIt was fantastic meeting you yesterday evening at the [Event Name] mixer.\n\nI particularly enjoyed our conversation regarding the [Specific Detail from Conversation, e.g., upcoming changes to the privacy regulations in Q3]. Your insights on how [Company Name] is proactively preparing for that shift were incredibly helpful.\n\nI’d love to stay in touch as the year progresses. If you’re ever open to grabbing a virtual coffee for 15 minutes, I’d love to hear more about your work scaling the [Department] team.\n\nBest of luck with the upcoming launch!\n\nCheers,\n[Your Name]",
      "Subject: Reconnecting after [Conference Name] / The article we discussed\n\nHi [Name],\n\nIt was a pleasure crossing paths with you during the breakout session at [Conference Name] yesterday.\n\nWhile we were chatting about [Specific Topic], I mentioned a recent case study that I felt completely overhauled my approach to [That Strategy]. I dug through my bookmarks this morning and finally found it! \n\nYou can read it here: [Link to Article]. I specifically found the section detailing [Specific Point] highly relevant to the challenges [Their Company] is currently facing.\n\nLet me know your thoughts if you get a chance to read it!\n\nWarmly,\n[Your Name]",
      "Subject: Coffee/Intro chat next week?\n\nHi [Name],\n\nThanks for grabbing a coffee with me between sessions at [Event Name] last week. \n\nI loved hearing about how you successfully transitioned your career from [Industry A] into [Industry B] at [Company Name]. Since I am currently embarking on a very similar transition, your perspective was incredibly valuable.\n\nWould you be open to a 10-minute informational chat via Zoom sometime next month? I’d love to ask two or three brief questions about your experience maneuvering that transition.\n\nRegardless, I sent you a connection request on LinkedIn and hope we can stay in touch!\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Always write down one specific personal or business detail on the back of their business card immediately after the conversation to use in your email.",
      "Send the email within 24 to 48 hours. If you wait a week, the connection is completely cold.",
      "If you promised to introduce them to someone or send an article, do it in the very first email."
    ],
    faq: [
      { question: "Should I include my resume?", answer: "No. Unless they explicitly asked you to send your resume, attaching it immediately transitions the interaction from 'peer networking' to 'asking for a job', which kills the new relationship." },
      { question: "Is LinkedIn better than email?", answer: "Email is significantly better for standing out, as inboxes are less cluttered with generic connection requests. However, sending a LinkedIn request alongside the email is highly recommended." },
      { question: "What if they don't respond?", answer: "Busy professionals often miss emails. Send one polite follow-up a week later containing an insightful industry article. If there is still no response, let it go." }
    ]
  },
  {
    slug: 'welcome-email-for-new-employees-onboarding',
    title: 'Welcome Emails for New Employees (Onboarding Templates)',
    description: 'Create an incredible first day. Use these comprehensive onboarding welcome email templates for new employees to set clear expectations and culture.',
    intro: 'The onboarding experience dictates the long-term success and retention of a new employee securely. Statistically, an exceptional onboarding process boosts new hire retention by 82% and massively accelerates their productivity. Before the new employee even boots up their laptop on day one, they will experience "new job jitters." A phenomenal welcome email instantly alleviates that anxiety by laying out a completely transparent, well-structured roadmap for their first week.\n\nA great onboarding welcome email should be sent several days before their official start date by their direct manager. The tone should be overwhelmingly enthusiastic and supportive, immediately integrating them into the company culture. Crucially, the email must contain a bulleted list of highly specific logistical details: what exact time do they need to log on (or arrive at the office), who will be securely provisioning their tech stack and passwords, and a high-level overview of their agenda for the first 48 hours. Ambiguity is the enemy of a smooth onboarding.\n\nUtilize the onboarding email templates below to welcome your newest hires with extreme professionalism. Whether you are onboarding a remote developer, a junior marketing associate, or a senior executive, these scripts ensure your new employee feels entirely supported from minute one.',
    templates: [
      "Subject: Welcome to [Company Name]! Your First Week Agenda\n\nHi [Employee Name],\n\nWelcome to the [Department] team at [Company Name]! We are incredibly thrilled that you are joining us, and your workspace is fully prepped for your start date on [Date].\n\nTo ensure your first week is completely friction-free, I wanted to provide a quick rundown of what your first day will look like:\n\n- 9:00 AM: Kickoff Call. Log into Zoom via this link [Link] for an informal welcome chat with me.\n- 9:30 AM: IT Setup. [IT Contact Name] will guide you through getting access to Slack, email, and internal software.\n- 11:00 AM: HR Onboarding. A quick session to finalize your benefits enrollment.\n- 12:00 PM: Virtual Team Lunch! We’ll introduce you to the wider team.\n\nYour company laptop should have arrived via FedEx yesterday. Please let me know immediately if it hasn't.\n\nWe couldn't be more excited to have you on board. See you Monday!\n\nBest,\n[Your Name] / Manager",
      "Subject: Introducing [New Employee Name] to the Team!\n\nHi Everyone,\n\nPlease join me in extending a massive welcome to [New Employee Name], who officially joins the [Department] team today as our new [Job Title]!\n\n[Employee Name] comes to us from [Previous Company], where they played a pivotal role in scaling [Specific Project]. They possess incredible expertise in [Skill A] and [Skill B], and will primarily be focused on driving our upcoming [Project Name] initiative this quarter.\n\nOutside of work, [Employee Name] is an avid [Hobby/Interest] and recently traveled to [Location].\n\nPlease drop them a Slack message today to say hello and officially welcome them to the [Company Name] family!\n\nCheers,\n[Your Name]",
      "Subject: Pre-Arrival Notes for your first day at [Company Name]\n\nHi [Employee Name],\n\nWe are looking forward to officially welcoming you to the office next [Day of week]!\n\nTo help you get settled, here are a few quick logistical details regarding your first day:\n- Arrival Time: Please arrive at [Building Address] by [Time].\n- Check-In: Ask for [Point of Contact Name] at the front desk, and they will show you to your desk.\n- Dress Code: [Company Name] is strictly business casual. Jeans are perfectly fine!\n- Lunch: We are treating you to lunch with the immediate team on your first day.\n\nIf you have any last-minute questions over the weekend, please don't hesitate to email me directly.\n\nWelcome aboard!\n\nWarmly,\n[Your Name]"
    ],
    tips: [
      "Send a copy of the employee handbook and any HR paperwork ahead of time so they don't spend their entire first day reading documents.",
      "Assign them an 'Onboarding Buddy'—a peer (not a manager) who they can direct small, casual questions to during their first week.",
      "Clearly lay out the schedule for the first few days so they never feel lost or unsure of what they should be doing."
    ],
    faq: [
      { question: "What should be included in the 'Team Welcome' email?", answer: "Include their professional background, their core responsibilities, and one or two fun, personal facts (e.g., 'They have a Golden Retriever named Max') to spark casual conversations with colleagues." },
      { question: "When should I send the onboarding email?", answer: "Send the logistical email to the new hire the Thursday or Friday before they start so they can mentally prepare for Monday." },
      { question: "Should we send company swag?", answer: "Absolutely. Mailing a branded t-shirt or coffee mug to their home before their start date dramatically increases their sense of belonging and enthusiasm." }
    ]
  },
  {
    slug: 'email-introducing-a-new-account-manager-to-client',
    title: 'Email Templates: Introducing a New Account Manager to a Client',
    description: 'Ensure a smooth, risk-free transition. Use these templates to seamlessly introduce a new account manager to your top clients without breaking trust.',
    intro: 'Transitioning a highly valued B2B client to a new Account Manager (AM) or Customer Success Manager (CSM) is an incredibly high-risk scenario. Clients loathe transitions because they fear that the deep institutional knowledge and customized workflows they’ve built with their previous rep will be lost. If you merely send a generic two-sentence email announcing a new point of contact, the client will immediately feel undervalued, leading to massive friction and potential churn.\n\nA seamless Account Manager introduction email must execute a meticulous "warm handoff." The tone should remain overwhelmingly positive, celebrating the transition rather than apologizing for it. Crucially, the outgoing representative or executive sponsor should send the first email, thoroughly endorsing the incoming AM. You must reassure the client explicitly that the new AM has been fully briefed on their historical data, ongoing projects, and Q3 goals. Finally, schedule a brief, tri-party introductory call to formally cement the transition and establish rapport.\n\nThe customized templates below are designed to mitigate risk during an account transition. Use them to ensure your customers feel supported, confident in their new representation, and entirely unaffected by internal staffing shifts.',
    templates: [
      "Subject: Updating your dedicated Account Manager at [Company Name]\n\nHi [Client Name],\n\nI hope your week is off to a phenomenal start.\n\nI’m writing to enthusiastically announce that [New Rep’s Name] is officially stepping in as your newly dedicated Account Manager starting [Date]. I am taking on a new role internally, but ensuring your team is flawlessly supported remains my absolute top priority.\n\nI have extensively briefed [New Rep’s Name] on your specific SLA, your outstanding deliverables for the [Ongoing Project], and the aggressive ROI goals we established for Q4. They are an absolute rockstar and previously led similar accounts at [Impressive Detail], meaning your team is in incredibly capable hands.\n\nCould we schedule a quick 15-minute handoff call next Tuesday? I’d love to officially introduce you both.\n\nBest regards,\n[Your Name]",
      "Subject: Introduction: [New Rep Name] / [Client Name]\n\nHi [Client Name],\n\nAs promised, I wanted to officially introduce you to [New Rep Name]! \n\n[New Rep Name] will be stepping in to manage your account moving forward. They have already reviewed your full account history and specifically looked at the recent reporting data regarding your [Specific Pain Point]. \n\nI’ll let [New Rep Name] take it from here to schedule your upcoming monthly sync!\n\nBest,\n[Your Name (Outgoing)]\n\n---\n\nHi [Client Name],\n\nIt is an absolute pleasure to step in and support your team. I’ve heard incredible things about the work you are doing on the [Client's Project Name] front. \n\nI am fully up to speed on your required deliverables for this week. Would you have 10 minutes on Friday for a brief call to align on cadence moving forward?\n\nSincerely,\n[New Rep Name]",
      "Subject: Action Required: Your point of contact at [Company Name] is changing\n\nHi [Client Name],\n\nThank you for being such a highly valued partner of [Company Name] over the last year.\n\nI am reaching out to proactively let you know that as we continue to scale our operations, your account is being transitioned to [New Rep Name], a Senior Customer Success Manager on our Enterprise team.\n\n[New Rep Name] specializes exactly in your industry and will be taking over all strategic guidance and support queries moving forward. You can reach them directly at [New Rep Email].\n\nThere will absolutely be no disruption to your service during this transition.\n\nThanks,\n[Your Name/Leadership]"
    ],
    tips: [
      "Use the 'Triple Endorsement': have the outgoing rep boast about how talented the incoming rep is to transfer trust immediately.",
      "Never allow the new rep to ask 'So, what are your goals?' on the first call. They must prove they read the historical notes.",
      "The handoff email should always come from the original, trusted point of contact, not an automated billing system."
    ],
    faq: [
      { question: "How much notice should I give before a rep change?", answer: "Ideally, at least 2 weeks. This gives the outgoing rep time to close any immediate loose ends before gracefully exiting." },
      { question: "What if the client complains about the new rep?", answer: "A manager or director must step in immediately. Hop on a call, actively listen to their concerns, re-affirm the new rep's qualifications, and establish a 30-day check-in to monitor progress." },
      { question: "Should the outgoing rep join the introduction video call?", answer: "Yes, this is known as a 'Warm Handoff'. The outgoing rep leads the first 5 minutes to set the tone, introduces the new rep, and safely transfers the social capital." }
    ]
  },
  {
    slug: 'salary-negotiation-email-after-job-offer',
    title: 'Salary Negotiation Emails After Receiving a Job Offer',
    description: 'Get paid what you are worth. Use these strategic salary negotiation templates to gracefully counter-offer your new job proposal without losing the offer.',
    intro: 'Receiving a job offer is the culmination of a grueling interview process, but it is not the end of the road. Far too many professionals instantly accept the initial offer because they fear that negotiating will cause the hiring manager to rescind it entirely. However, negotiating your compensation is an expected, standard business practice. If you approach the negotiation professionally and ground your counter-offer in objective market data rather than personal demands, you can significantly boost your baseline salary while simultaneously impressing the hiring team with your business acumen.\n\nA masterclass salary negotiation email requires precision and gratitude. The email must begin by expressing profound excitement for the opportunity. Next, clearly state the specific base salary (or overall compensation value) you are seeking. You must justify this number objectively by referencing your specialized skills (e.g., specific software certifications), the current local market rate for the role, or the immediate value you will deliver based on the challenges discussed in your interviews. End the email by reiterating that you are ready to sign the contract immediately if the numbers align.\n\nUse the tested templates below to confidently negotiate a higher base salary, a signing bonus, or a modified compensation structure. Tailor the specific justifications to match your unique professional strengths and market leverage.',
    templates: [
      "Subject: Re: Job Offer from [Company Name] - [Your Name]\n\nHi [Hiring Manager's Name],\n\nThank you so much for sending over the formal offer letter! I am absolutely thrilled about the opportunity to join the [Department] team and begin contributing to the [Specific Project].\n\nBefore formally accepting, I was hoping we could briefly discuss the base compensation. Based on the current market data for similar senior roles in [City], and the extensive specialized experience I bring in [Skillset A] and [Skillset B], I am seeking a base salary closer to $[Target Salary].\n\nI am incredibly excited about the vision of [Company Name] and am eager to immediately add value. Is there flexibility to bring the base salary closer to that number?\n\nI look forward to discussing this with you.\n\nBest regards,\n[Your Name]",
      "Subject: Re: Offer Details - [Your Name]\n\nHi [Recruiter's Name],\n\nI truly appreciate you taking the time to outline the compensation package on the phone today. The opportunity to work alongside the team at [Company Name] is incredibly exciting.\n\nWhile the overall benefits package is fantastic, the base salary is slightly below what I was expecting given the heavy [Specific Responsibility] requirements of the role.\n\nIf we are able to increase the base salary to $[Target Salary] or provide a one-time signing bonus of $[Bonus Amount] to bridge the gap, I would be more than happy to sign the offer immediately and submit my 2-weeks notice today.\n\nPlease let me know if this is something the compensation team can accommodate.\n\nCheers,\n[Your Name]",
      "Subject: Checking in regarding competing offers - [Your Name]\n\nHi [Hiring Manager Name],\n\nThank you again for the offer! My conversations with the leadership team have only solidified my belief that [Company Name] is the perfect cultural fit for me.\n\nIn the spirit of complete transparency, I am currently navigating a competing offer from another firm that includes a base salary of $[Competitor Salary Amount].\n\nHowever, [Company Name] remains my absolute first choice due to the incredible growth trajectory of your team. If you are able to match—or come closer to—this competing salary of $[Target Salary], I will formally decline the other offer and accept yours immediately.\n\nI hope we can make this work! Let me know if you would like me to forward the details.\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Never give an ultimatum unless you possess massive leverage and are genuinely prepared to walk away from the offer.",
      "If the base salary is entirely rigid, pivot immediately to asking for a one-time signing bonus, extra PTO days, or an accelerated 6-month performance review.",
      "Always justify your counter-offer using data: market rates, your unique certifications, or competing offers."
    ],
    faq: [
      { question: "Will they rescind my offer if I ask for more money?", answer: "No. A professional, data-backed counter-offer will not cause a reputable company to rescind an offer. The worst they will say is 'We do not have the budget to increase it.'" },
      { question: "Should I negotiate via email or phone?", answer: "Email is often better for a counter-offer because it allows you to clearly outline your data and constraints, while removing the awkwardness of an immediate live reaction." },
      { question: "How much more should I ask for?", answer: "A standard counter-offer aims for 10% to 20% above the initial offer, provided you have the market data to support that valuation." }
    ]
  },
  {
    slug: 'apology-email-for-missing-a-meeting',
    title: 'Apology Email for Missing a Professional Meeting',
    description: 'Missed a critical call? Use these highly professional apology email templates to recover gracefully and reschedule without burning the relationship.',
    intro: 'Missing a scheduled professional meeting—whether due to a severe technical issue, an unavoidable personal emergency, or an embarrassing calendar oversight—is an incredibly stressful scenario that can severely damage your professional reputation. If left unaddressed, the other party will inherently assume you simply do not value their time. To salvage the relationship and prove your reliability, you must deploy an apology email immediately.\n\nThe anatomy of a flawless meeting apology involves extreme accountability and proactive resolution. Do not invent a convoluted excuse; convoluted excuses reek of dishonesty. Briefly apologize, state high-level why you missed it (e.g., "a sudden family emergency" or "a calendar glitch"), and immediately take on the entire burden of rescheduling. Do not simply ask, "When are you free next?" Offer them priority availability. Suggest two or three highly specific times when you are free, or provide your direct calendar link to minimize any further friction for them.\n\nThe templates provided below cover various missed meeting scenarios—from ghosting an important sales prospect to missing an internal team check-in. Use these precise scripts to quickly transition from apologizing to efficiently rescheduling.',
    templates: [
      "Subject: My sincere apologies / Rescheduling our meeting\n\nHi [Name],\n\nPlease accept my deepest apologies for completely missing our scheduled call at [Time] today. \n\nI had an unexpected [Family Emergency / Urgent Client Escalation] arise that completely pulled me away from my desk, and I unfortunately was unable to notify you beforehand.\n\nI highly value your time and feel terrible for the inconvenience this caused your schedule today. \n\nIf you are still open to connecting, I would love to reschedule at your earliest convenience. I am prioritizing our chat and have cleared my calendar for the following times:\n- Tomorrow at 10:00 AM EST\n- Thursday at 2:00 PM EST\n\nPlease let me know if either of those work, or feel free to drop a block on my calendar here: [Link].\n\nBest regards,\n[Your Name]",
      "Subject: Apology for the calendar mix-up!\n\nHi [Name],\n\nI am so sorry I missed our meeting this afternoon!\n\nDue to a bizarre syncing issue between my calendar application and different time zones, the meeting dropped off my radar entirely. It was an oversight on my end, and I apologize for leaving you waiting on the Zoom link.\n\nCould we reschedule this for later in the week? I’m wide open on Friday morning if you have 15 minutes to spare.\n\nThanks for your understanding,\n[Your Name]",
      "Subject: Running very behind / Can we push 30 mins?\n\nHi [Name],\n\nI am incredibly sorry, but my current meeting regarding [Urgent Topic] is running significantly over schedule and I am not able to step away.\n\nWould it be possible to push our 2:00 PM sync back by just 30 minutes to 2:30 PM? \n\nIf your schedule is packed this afternoon and you need to push it to tomorrow morning, I completely understand. Let me know what works best for you!\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Send the email the absolute second you realize you missed the meeting. Speed proves you care.",
      "Take full ownership. Do not say 'The calendar didn't remind me'. Say 'It was an oversight on my end.'",
      "Offer multiple specific times to reschedule so they do not have to think about checking their calendar."
    ],
    faq: [
      { question: "Should I call or email if I am late?", answer: "If you are currently 5 minutes late to a Zoom, email or Slack immediately. If you entirely ghosted a phone meeting, a quick apologetic phone call is best, followed by an email to reschedule." },
      { question: "What if it was the other person's fault they sent the wrong link?", answer: "Do not play the blame game. Simply state 'It looks like we crossed wires on the Zoom link today, no worries! Let's reschedule for tomorrow.'" },
      { question: "Is a 'family emergency' excuse always acceptable?", answer: "Yes. In professional environments, a 'family emergency' is universally respected and rarely questioned. However, only use it if it is true, as it severely damages trust if caught in a lie." }
    ]
  }
];

const out = [...data, ...newTemplates];
fs.writeFileSync(file, JSON.stringify(out, null, 2));
