const fs = require('fs');
const file = 'src/data/templates.json';
const data = JSON.parse(fs.readFileSync(file, 'utf-8'));

const newTemplates = [
  {
    slug: 'meeting-reschedule-email-professional',
    title: 'How to Reschedule a Meeting Professionally',
    description: 'Emergencies happen. Use these incredibly professional meeting reschedule email templates to gracefully postpone a call without losing trust.',
    intro: 'Rescheduling a committed professional meeting at the absolute last minute is highly uncomfortable. Whether a massive server outage occurred, a personal family medical emergency developed, or your previous client meeting simply ran 45 minutes over, you must act instantly to minimize the massive disrespect of wasting the other person\'s time. Handled poorly, a last-minute cancellation burns the relationship permanently. Handled with extreme grace, it actually demonstrates your high operational integrity.\n\nA brilliant reschedule email must instantly apologize, briefly state the specific reason without over-explaining the drama, and immediately shoulder the entire burden of finding a new time. Do not make them hunt through your calendar. Propose two explicitly clear, specific alternative time slots formatted in their local time zone. The primary goal is to make the entire rescheduling process entirely frictionless for the inconvenienced party.\n\nUse the tested templates below to execute emergency rescheduling. From moving a high-stakes sales call to gracefully dodging an internal sync, these scripts preserve your professional reputation during chaotic moments.',
    templates: [
      "Subject: Rescheduling our call today / [Your Name]\n\nHi [Name],\n\nI am so incredibly sorry, but I have to request that we reschedule our meeting scheduled for [Time] today.\n\nWe are currently dealing with an unexpected [Urgent Issue/Server Outage] that requires my immediate, undivided attention for the next few hours.\n\nI highly value your time and sincerely apologize for the last-minute disruption. Are you available to connect at either of the following times later this week?\n\n- Thursday at 2:00 PM EST\n- Friday at 10:00 AM EST\n\nLet me know if either of those options work, and I will gladly send an updated invite.\n\nBest regards,\n[Your Name]",
      "Subject: Apologies - needing to reschedule our Sync\n\nHi [Name],\n\nI am writing to sincerely apologize, but I have a sudden personal family emergency that requires me to step entirely offline for the remainder of the day.\n\nBecause I want to ensure I am fully present and prepared for our discussion regarding [Topic], I unfortunately need to postpone our meeting this afternoon.\n\nI will circle back early next week once I am back online so we can proactively coordinate a new time.\n\nThank you so much for your understanding!\n\nBest,\n[Your Name]",
      "Subject: Running heavily behind schedule\n\nHi [Name],\n\nI am so sorry, but my previous client presentation is running significantly over the allotted time block.\n\nTo ensure I don’t rush our conversation, would you be open to pushing our call back by exactly one hour today? If your afternoon is completely booked up, we can easily move this to [Alternative Day] instead.\n\nAgain, apologies for the incredibly poor timing on my end!\n\nCheers,\n[Your Name]",
      "Subject: Rescheduling: [Meeting Title] - [Your Name]\n\nHi [Name],\n\nI am writing to catch you before you hop on the Zoom link!\n\nI unfortunately need to reschedule our sync today. I simply haven't gathered all the necessary data points from the [Department] team yet, and I don't want to completely waste your time discussing an incomplete model.\n\nI should have everything finalized by tomorrow. Does [Time] on [Day] work better to officially review the numbers?\n\nThanks for being flexible!\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Send the email the exact second you realize you will miss the meeting. Giving someone 30 minutes of warning is infinitely better than emailing them 5 minutes after they logged into the Zoom room.",
      "Offer specific times. 'Can we reschedule?' forces them to do the painful calendar math. 'Can we do 2 PM on Thursday?' requires only a one-word reply.",
      "Never lie entirely. Keep the reason vague ('urgent cross-functional priority') rather than inventing elaborate fictional sicknesses."
    ],
    faq: [
      { question: "Is it better to email or text a cancellation?", answer: "If the meeting starts in less than 15 minutes and you have their cell number, definitively text them. Emails are easily missed in the final minutes before a call." },
      { question: "Can I reschedule an initial job interview?", answer: "It is highly risky. Only do it for a legitimate hospitalization or severe physical emergency. Rescheduling an initial interview usually results in an automatic rejection." },
      { question: "What if they are annoyed?", answer: "Simply apologize profusely again on the rescheduled call, then immediately pivot to the business at hand. Do not dwell on the mistake for 10 minutes." }
    ]
  },
  {
    slug: 'cold-email-freelance-writer',
    title: 'Cold Email Templates for Freelance Writers',
    description: 'Build a massive client roster. Pitch editors, marketing directors, and SaaS founders with these proven freelance writing cold email templates.',
    intro: 'The freelance writing market is oversaturated with beginners sending aggressive, grammatically flawed emails begging "hire me to write your blog." Editors and Marketing Directors instantly delete these emails. To successfully acquire lucrative retainer clients as a freelance copywriter or content marketer, your cold outreach must prove your supreme competency instantly. Your cold email is your ultimate portfolio piece; if the email itself is boring, they will logically conclude your articles will be boring.\n\nA masterful freelance writing pitch focuses entirely on SEO ROI and industry expertise. You cannot pitch a generic 500-word blog post. You must vividly identify a gap in the prospect\'s current content strategy. Explain that their direct competitor currently ranks #1 for a massive keyword, and clearly offer to write a 2,000-word pillar asset that will outrank them. Prove you deeply understand their highly specific industry jargon, instantly removing the massive editing burden most freelancers place on marketing directors.\n\nUse the hyper-targeted templates below to pitch Editors and founders securely. These scripts bypass the cheap job boards and position you instantly as a premium, consultative SEO asset.',
    templates: [
      "Subject: Quick idea for the [Company Name] blog\n\nHi [Name],\n\nI am a massive fan of the recent teardown you published regarding [Specific Topic]. \n\nI am a freelance content marketer specifically focused on the B2B SaaS space. I was doing some brief keyword research this morning and noticed that [Direct Competitor] is currently hoarding all the organic traffic for the keyword '[High Value Keyword]'.\n\nI’d love to write a highly technical, 2,000-word pillar post for [Company Name] specifically designed to outrank them and capture that inbound lead flow.\n\nFor context on my writing style, I recently published [Link to Best Article] for [Major Industry Blog].\n\nWould you be open to me sending over a brief outline for this idea?\n\nBest,\n[Your Name]",
      "Subject: Freelance writing capacity at [Company Name]\n\nHi [Name],\n\nI see [Company Name] has aggressively ramped up its content production this quarter. The recent piece on [Topic] was brilliantly structured.\n\nSince your marketing team is clearly scaling output, I wanted to quickly introduce myself. I am a freelance copywriter who exclusively writes high-converting technical documentation and SEO assets for [Niche/Industry] brands.\n\nIf you are currently looking to outsource overflow writing work to someone who already natively understands [Complex Industry Jargon] without requiring heavy editing, I’d love to help.\n\nHere are two recent pieces I published in your exact space:\n- [Link 1]\n- [Link 2]\n\nLet me know if you have any freelance bandwidth needs this month!\n\nCheers,\n[Your Name]",
      "Subject: Re-writing the [Page Name] landing page\n\nHi [Founder/Name],\n\nI absolutely love the software you are building at [Company Name].\n\nI actually clicked through your funnel today and noticed that your core [Feature] landing page isn't highly optimized for conversions. The copy focuses heavily on technical features rather than the raw financial ROI your specific target customer is looking for.\n\nI am a freelance conversion copywriter. I recently rewrote the entire funnel for [Similar Company], resulting in a 22% increase in trial signups within 30 days.\n\nI’d love to completely rewrite that single landing page for you. If it doesn't beat your current control variant in an A/B test, I won't charge you a dime.\n\nOpen to exploring this?\n\nBest regards,\n[Your Name]"
    ],
    tips: [
      "Pitch ideas, not yourself. Sending 3 highly researched headline ideas is infinitely more valuable than sending blindly asking for 500-word assignments.",
      "Link to a live Google Doc URL. Never attach random PDFs of your writing; they look unprofessional and trigger spam filters.",
      "Target SaaS companies that recently received Series A funding; they suddenly have massive marketing budgets and zero time to write in-house."
    ],
    faq: [
      { question: "How much should I charge?", answer: "Premium SEO content freelancers charge between $0.20 to $0.50+ per word, or $500 to $1,500+ per pillar post, based purely on the ROI the traffic generates." },
      { question: "Should I offer a free trial article?", answer: "No. Offering pure free work instantly devalues your brand. Instead, offer a risk-free pilot: 'Pay me if you love it, don't pay if you trash it.'" },
      { question: "Who do I email?", answer: "Email the 'Director of Content', 'Head of Marketing', or at smaller startups, the Founder directly." }
    ]
  },
  {
    slug: 'cold-email-link-building-guest-post',
    title: 'Cold Email Templates for Link Building & Guest Posts',
    description: 'Boost your Domain Authority. Secure massive organic traffic with these incredibly effective, non-spammy link building and guest post outreach templates.',
    intro: 'Organic link building remains the single most critical factor in modern SEO. However, blindly blasting massive lists of website owners with highly automated, generic "Please link to my article" emails is a mathematically failing strategy. Editors at high Domain Authority (DA) websites receive dozens of these spammy requests daily and delete them instantly. To successfully secure a high-value backlink, your outreach must prioritize hyper-personalization and immediately observable mutual value.\n\nA great link-building email completely avoids begging. The most effective strategy involves "Broken Link Building" (alerting them to a 404 error on their site and offering your link as a replacement) or pitching an insanely valuable, free piece of content (like a custom infographic) that naturally earns a link. You must clearly identify exactly where the link should go and explicitly prove why linking to your asset actively improves the user experience of their existing readers.\n\nUtilize the highly strategic templates below to execute massive white-hat SEO campaigns. These scripts are engineered to bypass spam filters and build genuine relationships with elite content managers.',
    templates: [
      "Subject: Quick heads up: Broken link on the [Company Name] blog\n\nHi [Name],\n\nI was doing some research on [Topic] this morning and came across your fantastic resource page: [Link to their page].\n\nI actually noticed that one of the resources you linked to under the [Specific Header] section is returning a dead 404 error page. \n\nI recently published a massive, highly updated 3,000-word guide on that exact same topic here: [Link to your asset].\n\nIf you are looking to quickly swap out the dead link to improve the user experience for your readers, my guide would be a perfect fit! \n\nEither way, keep up the fantastic work on the blog!\n\nBest regards,\n[Your Name]",
      "Subject: Idea for a Guest Post: [Highly specific headline]\n\nHi [Editor's Name],\n\nI am a massive fan of the [Company Name] blog. The recent piece you published on [Topic] entirely changed how my team handles our internal workflow.\n\nI noticed you haven’t published a deep dive on [Niche Sub-Topic] yet. Because I have 5 years of extremely hands-on experience in that exact area, I would love to write a highly actionable guest post summarizing exactly how to execute it.\n\nHere are three potential headlines I think your audience would love:\n- [Idea 1]\n- [Idea 2]\n- [Idea 3]\n\nI recently wrote a similar guest post for [Major Site] here: [Link].\n\nLet me know if any of those jump out at you and I will gladly draft a quick outline!\n\nCheers,\n[Your Name]",
      "Subject: Addition to your resource list on [Topic]\n\nHi [Name],\n\nI just finished reading your incredibly thorough roundup on [Topic] — specifically, your point regarding [Specific insight] was absolutely brilliant.\n\nBecause your readers clearly care deeply about [Data Point], I thought I would reach out. My team just spent 4 weeks formally surveying 1,000 professionals in the space and compiled all the raw data into a custom infographic.\n\nI think it would make an incredibly valuable addition to your current article to back up your hypothesis visually.\n\nHere is the link to the data: [Link]\n\nIf you find it useful, feel free to embed it or link to it!\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Offer custom graphics. If you offer to build them a custom diagram for their existing article in exchange for a tiny credit link, they will almost always say yes.",
      "Hunt down the specific editor. Sending link requests to 'info@website.com' guarantees a bounce. Find the 'Content Manager' on LinkedIn.",
      "Be relentlessly polite. Never demand a link. Always offer it as a helpful suggestion to improve their own SEO metrics."
    ],
    faq: [
      { question: "Do these templates work for paid links?", answer: "These are explicitly designed for genuine, white-hat outreach. If a site demands $500 for a link, walk away. Google actively penalizes paid link farms." },
      { question: "What is a good reply rate for link building?", answer: "Because the industry is completely saturated with spam, a 3% to 5% successful placement rate on cold outreach is actually considered highly successful." },
      { question: "Should I automatically build links to my homepage?", answer: "No. Build links deeply to your specific, high-quality blog posts (Pillar Content) rather than blindly linking to your root domain." }
    ]
  },
  {
    slug: 'cold-email-pr-outreach-journalists',
    title: 'Cold Email PR Outreach to Journalists',
    description: 'Get massive press coverage. Learn the exact cold email template formulas to successfully pitch journalists and secure huge PR features.',
    intro: 'Securing a feature article in a massive publication like Forbes, TechCrunch, or a niche industry magazine can drive tens of thousands of instant visitors to your platform. However, PR outreach is fundamentally broken. Founders blindly blast massive Excel spreadsheets of journalists with highly aggressive, generic press releases detailing minor software updates that no one cares about. Journalists delete these emails instantly; they are desperately searching for compelling narratives, not corporate advertisements.\n\nA masterful PR cold email requires extreme brevity and a violently compelling "hook". You must pitch a localized, highly relevant story, not a product. If you launched a new AI software, do not detail the features. Detail exactly how this specific software is currently resulting in thousands of local accounting jobs being replaced overnight. Give the journalist a ready-made story arc containing conflict, massive data points, and exclusive access to a primary source (you).\n\nUse the customized PR outreach templates below to cut through the massive noise in a reporter’s inbox. These scripts are engineered to effortlessly provide journalists exactly what they need: an easy, highly clickable story.',
    templates: [
      "Subject: Exclusive Data: How [Trend] is ravaging the [Industry] sector\n\nHi [Journalist Name],\n\nI loved your recent piece regarding the massive supply chain disruptions in the [Specific Sector].\n\nBecause you cover the [Niche/Beat] so extensively, I wanted to offer you exclusive early access to a new dataset my team at [Company Name] just compiled. We tracked 5,000 local businesses over the last 6 months and found that [Highly Shocking, Counter-Intuitive Data Point].\n\nIt entirely contradicts the current narrative that [Competitor Idea] is winning the market.\n\nI’ve attached the raw summary below. I am available all day tomorrow if you’d like an exclusive quote or a brief interview regarding the findings before we publish them publicly next week.\n\nBest regards,\n[Your Name]",
      "Subject: Local Story: [City] startup completely automates [Process]\n\nHi [Journalist Name],\n\nSince you consistently cover the rapid rise of the B2B tech scene here in [City], I thought this might be a great fit for your column.\n\nMy co-founder and I recently left our secure jobs at [Major recognizable company] to quietly build [Company Name]. We just officially launched an application that entirely automates [Process]—a massive regulatory bottleneck that currently costs local [City] agencies millions annually.\n\nWe successfully piloted the program with [Local Famous Client], saving them [Massive Metric] in just 30 days.\n\nIf you think your readers would be interested in how local tech is disrupting this dinosaur industry, I’d love to hop on a quick call and give you the full scoop.\n\nCheers,\n[Your Name]",
      "Subject: Expert Source: [Current Trending News Crisis]\n\nHi [Journalist Name],\n\nI quickly saw your latest tweet requesting opinions on the sudden [Current News Event/Crisis] occurring in the [Industry] sector.\n\nAs the CEO of [Company Name], I have spent the last 15 years deeply navigating this exact regulatory environment. The massive underlying issue no one is currently discussing is actually [Unique, insightful contrarian take].\n\nIf you are currently writing a piece on this and need a quick, highly technical quote from an industry veteran, I am completely available for a 5-minute phone call anytime today.\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Offer absolute exclusivity. Journalists crave scoops. Promising them 'You are the only person seeing this data before it goes public' is a massive psychological hook.",
      "Pitch the 'Contrarian Take'. If everyone holds Opinion A, journalists are desperately searching for whoever holds credible Opinion B to create conflict.",
      "Never attach massive PDFs. Paste the immediate, most shocking bullet points directly into the email body."
    ],
    faq: [
      { question: "When is the best time to email a journalist?", answer: "Early morning, typically Tuesday or Wednesday. Never pitch on a Friday afternoon when the news cycle is absolutely dead." },
      { question: "Should I follow up with reporters?", answer: "Only once, roughly 48 hours later. If they don't reply, the story isn't a fit. Do not harass them." },
      { question: "Do I need to hire an expensive PR firm?", answer: "No. A founder sending a highly authentic, personalized email to a specific niche reporter will frequently out-perform a massive $10,000 PR agency blast." }
    ]
  },
  {
    slug: 'cold-email-speaker-podcast-invite',
    title: 'Cold Email Invites for Podcasts & Virtual Summits',
    description: 'Book massive guests. Use these cold email templates to invite high-profile experts to speak on your podcast or virtual summit.',
    intro: 'Securing a high-profile, highly influential guest for your niche podcast or virtual summit is the fastest strategy to exponentially grow your audience. When an elite expert shares your interview with their massive audience, your downloads spike instantly. However, high-profile executives, bestselling authors, and influencers are violently protective of their time. They receive dozens of podcast requests daily from completely amateur shows boasting zero actual audience.\n\nA masterful cold invitation must instantly prove that appearing on your show requires near-zero logistical effort while providing massive vanity ROI. Do not pitch how great your show is; pitch the exact, highly vetted audience the expert will be addressing. Validate your credibility instantly by implicitly mentioning a recognizable previous guest. Most importantly, explicitly state that the interview will be flawlessly organized, take exactly 30 minutes, and require absolutely zero prior preparation on their end.\n\nUse the customized booking templates below to secure elite guests. These scripts drastically lower the perceived friction of an interview, turning skeptical cold prospects into enthusiastic speakers.',
    templates: [
      "Subject: Request: Interview on the [Podcast Name] podcast\n\nHi [Name],\n\nI am the host of the [Podcast Name] podcast, a show dedicated entirely to helping [Specific Audience, e.g., 10,000+ SaaS founders] scale their operations.\n\nI just finished reading your new book, [Book Title], and your framework regarding [Specific Concept] absolutely blew my mind. I am highly confident my audience desperately needs to hear that exact philosophy.\n\nWe recently hosted [Recognizable Peer/Previous Guest] and the response was incredible. I would be completely honored to have you on for a brief, 30-minute interview.\n\nI handle 100% of the logistics—zero prep required on your end. Are you open to exploring a quick recording sometime next month?\n\nBest regards,\n[Your Name]",
      "Subject: Speaking Invite: The [Summit Name] Virtual Summit\n\nHi [Name],\n\nI absolutely loved your recent highly-viral Twitter thread regarding [Topic].\n\nI am organizing the upcoming [Summit Name] Virtual Summit, streaming live to an expected audience of 5,000+ [Target Persona] this October. Our core theme is entirely focused on [Niche Topic].\n\nBecause you are the preeminent expert in this exact space, I would love to officially invite you to deliver a brief 20-minute virtual keynote presentation.\n\nIt is entirely remote, requires minimal slide prep, and gives you a fantastic platform to plug your highly-anticipated upcoming course launch.\n\nLet me know if this aligns with your Q4 marketing schedule!\n\nCheers,\n[Your Name]",
      "Subject: Idea for a brief collaboration\n\nHi [Name],\n\nI’ve followed your work on the [Their Blog/Company] for years and constantly reference the [Specific Article] to my internal team.\n\nI run a highly targeted newsletter reaching 15,000+ [Audience Persona]. I am currently putting together a feature piece summarizing the absolute best advice for [Specific Challenge].\n\nRather than assuming, I wanted to ask the expert directly. Would you be open to providing a quick 2-sentence quote replying to this exact email regarding how you handle [Specific Challenge]?\n\nI will gladly link directly back to [Their Website] in the newsletter.\n\nThanks for your time!\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Name drop ruthlessly. Mentioning 'We just interviewed [Their Peer]' provides instant social proof that your show is highly legitimate.",
      "Pitch during their launch window. Always pitch an influencer precisely one month before their new book or course launches; they are actively seeking free media tours.",
      "Remove all friction. State explicitly 'You do not need to prepare aggressively, it is just a casual chat.' High-level people hate homework."
    ],
    faq: [
      { question: "What if my podcast has zero listeners right now?", answer: "Do not mention download numbers. Instead, pitch your extreme niche. Say 'I am building an incredibly tight-knit community of strictly B2B finance experts.'" },
      { question: "Should I ask their publicist or email them directly?", answer: "Always attempt their direct email or LinkedIn first. Publicists say 'No' by default to protect the executive. The executive themselves will often say 'Yes' out of sheer vanity." },
      { question: "Is 30 minutes too long?", answer: "30 minutes is the optimal ask. Anything over 45 minutes feels like grueling, exhausting labor to a busy executive." }
    ]
  }
];

const out = [...data, ...newTemplates];
fs.writeFileSync(file, JSON.stringify(out, null, 2));
