const fs = require('fs');
const file = 'src/data/templates.json';
const data = JSON.parse(fs.readFileSync(file, 'utf-8'));

const newTemplates = [
  {
    slug: 'cold-email-saas-onboarding-users',
    title: 'Highly Effective SaaS Onboarding Emails',
    description: 'Reduce user churn instantly. Use these proven SaaS onboarding email templates to activate new signups and drive product adoption.',
    intro: 'User onboarding is the most critical phase of the SaaS customer journey. If a new user signs up for your product but fails to experience the core value (the "Aha!" moment) within their first few sessions, they will almost certainly churn. A brilliant SaaS onboarding email sequence is not simply a tutorial; it is a psychological nudge designed to drive the user directly toward a highly specific activation metric, such as creating their first project or inviting a team member.\n\nGreat onboarding emails must be painfully simple. The biggest mistake founders make is overwhelming new users with ten different features in the welcome email. Instead, each email in your sequence should strictly focus on one single action. Keep the copy incredibly brief, heavily utilize whitespace, and feature one massively prominent Call-to-Action (CTA) button. Provide a tiny bit of education—a 30-second video GIF often works best—and then immediately ask them to replicate that action inside their own account.\n\nUse the customized templates below to construct a high-converting onboarding sequence. From the initial welcome message to the crucial Day-3 activation nudge, these templates are designed to maximize your trial-to-paid conversion rate.',
    templates: [
      "Subject: Welcome to [Company Name]! Let's get started.\n\nHi [Name],\n\nWelcome to [Company Name]! We are absolutely thrilled to have you on board.\n\nOur goal is to help you [Core Value Proposition, e.g., cut your server costs in half] starting today. To see immediate results, the absolute best first step is to [Specific Activation Action, e.g., integrate your database].\n\nIt takes less than 2 minutes. Click the link below to get set up instantly:\n\n[Link: Complete Your Setup]\n\nIf you get stuck or have absolutely any questions, just reply directly to this email. I read every single one.\n\nCheers,\n[Your Name] - Founder",
      "Subject: Quick tip: How to [Core Feature] in 30 seconds\n\nHi [Name],\n\nI noticed you signed up for [Company Name] yesterday but haven't had a chance to [Activation Action] yet.\n\nMost of our most successful users, like [Client Name], tell us that setting this up immediately saved them [Time/Money Metric] right out of the gate.\n\nI created a ridiculously brief 30-second walkthrough video here to show you exactly how easy it is:\n\n[Link: Watch Quick Video]\n\nWhenever you have a spare moment today, jump in and give it a try!\n\nBest,\n[Your Name]",
      "Subject: Unlock the power of [Secondary Feature]\n\nHi [Name],\n\nAwesome job setting up your first [Project/Campaign]! \n\nNow that you have the basics down, I wanted to share a quick advanced strategy. Did you know that you can easily [Secondary Benefit] by utilizing our [Feature Name] tool?\n\nBy simply enabling this toggle, our system will automatically [Action], freeing up hours of your time each week. \n\n[Link: Enable Feature Now]\n\nLet me know if you need any help configuring it!\n\nBest regards,\n[Your Name]",
      "Subject: [Name], need any help getting set up?\n\nHi [Name],\n\nI just wanted to send a quick personal note to check in.\n\nI see you created an account a few days ago, but it looks like you haven't fully deployed your first [Project/Asset] yet.\n\nIs there anything blocking you, or was the platform slightly confusing to navigate? If you’d like, I’m happy to hop on a quick 10-minute onboarding call this week to personally walk you through the setup and ensure everything is optimized perfectly for your team.\n\n[Link: Schedule 10-Min Setup Call]\n\nThanks!\n[Your Name]",
      "Subject: Your trial is ending soon! Here’s what you missed.\n\nHi [Name],\n\nJust a quick heads up that your [Company Name] free trial will officially expire in 48 hours.\n\nOver the last two weeks, you successfully utilized the platform to [List User's Action if tracking, or just mention the platform's core benefit]. To continue building on that momentum without interruption, you can upgrade your account here: \n\n[Link: Upgrade to Pro]\n\nIf you actually need a few more days to properly evaluate the software with your team, just reply to this email and I will happily extend your trial for another week. No questions asked.\n\nCheers,\n[Your Name]"
    ],
    tips: [
      "Always send emails from a real person's name (e.g., 'David at SaaSCo') rather than a generic 'noreply@saasco.com' to boost open rates.",
      "Track your activation metric. Do not send 'Feature B' onboarding emails if the user hasn't even completed 'Feature A' yet.",
      "Rely on plain-text formatted emails for onboarding directly from the founder; they feel much more personal than highly polished, graphics-heavy HTML emails."
    ],
    faq: [
      { question: "How many onboarding emails should a SaaS sequence have?", answer: "Typically 4 to 6 emails spread across the first 14 days, heavily weighted towards the first 72 hours when intent is highest." },
      { question: "What is an 'activation metric'?", answer: "It is the specific action a user must take to realize the product's value. For Slack, it is sending 2,000 messages. For a CRM, it might be importing 100 contacts." },
      { question: "Should I include images in onboarding emails?", answer: "Limit images. However, a single, high-quality GIF showing exactly where to click in the UI is highly effective at driving action." }
    ]
  },
  {
    slug: 'cold-email-saas-upsell-existing-customers',
    title: 'SaaS Upsell Emails to Increase ARR',
    description: 'Grow revenue without acquiring new leads. Use these SaaS upsell email templates to upgrade existing customers to premium tiers.',
    intro: 'Acquiring a new SaaS customer is intensely expensive, often requiring months of paid advertising, content marketing, and sales demos. Conversely, upselling a highly satisfied, existing customer to a higher pricing tier is the most cost-effective method to drive massive Net Revenue Retention (NRR) and scale your ARR. Your current users already trust your platform and understand its underlying value; they simply need to be shown how upgrading solves a new, more complex problem they are currently facing.\n\nA highly converting SaaS upsell email relies entirely on behavioral triggers, not random timing. Do not blast your entire user base asking them to upgrade. Instead, trigger the upsell email exactly when the user hits a specific usage limit (e.g., "You have used 90% of your storage") or when they repeatedly click on a premium feature that is currently gate-locked. By anchoring the upgrade pitch to their immediate, real-time need, the upsell feels like a helpful suggestion rather than a greedy sales pitch.\n\nUse the customized templates below to gracefully present upgrade opportunities. These scripts focus on highlighting the lost ROI of their current constraints and seamlessly transitioning them to your premium or enterprise plans.',
    templates: [
      "Subject: You’re almost at your [Limit Type] limit!\n\nHi [Name],\n\nHope you're having a great week!\n\nJust a quick heads up: your workspace is currently at 95% of its monthly [Limit Type, e.g., API request] limit on the Basic Plan.\n\nSince your team is clearly getting massive value out of the platform right now, upgrading to the Pro Plan will immediately unlock unlimited [Feature] and provide access to our advanced analytics dashboard, ensuring your workflow isn't paused this week.\n\nYou can seamlessly upgrade your workspace with one click here:\n\n[Link: Upgrade to Pro Plan]\n\nLet me know if you have any questions!\n\nBest,\n[Your Name]",
      "Subject: Unlock [Premium Feature] for your team\n\nHi [Name],\n\nI noticed that you recently tried to access the [Premium Feature Name] dashboard.\n\nThis is actually one of our most powerful tools available exclusively on the Enterprise tier. Companies similar to [Their Company Name] use this specific feature to entirely automate their [Process], usually resulting in a [Metric]% efficiency gain.\n\nSince you are already a power user of our core platform, I would love to activate a complimentary 7-day trial of the Enterprise tier on your account so you can test this feature entirely risk-free.\n\nWould you like me to toggle that on for you?\n\nCheers,\n[Your Name]",
      "Subject: Quick idea regarding your current plan\n\nHi [Name],\n\nI was looking through your account metrics and it is amazing to see how heavily [Company Name] is utilizing our [Specific Feature]!\n\nI noticed you are currently paying seat-by-seat on the standard tier. Given your rapid growth over the last quarter, it would actually be significantly more cost-effective for your team to transition to our flat-rate Enterprise tier.\n\nNot only would this lower your cost-per-user by roughly [X]%, but it would also instantly unlock Single Sign-On (SSO) and dedicated account management.\n\nDo you have 5 minutes next week to review the numbers?\n\nBest regards,\n[Your Name]",
      "Subject: Feature Update: [New Premium Feature] is live!\n\nHi [Name],\n\nAs one of our longest-tenured customers, I wanted to personally reach out with some exciting news.\n\nWe just launched [New Feature Name]—a highly requested tool that allows you to [Huge Benefit]. It fundamentally changes how teams manage [Project Type].\n\nBecause this feature requires massive computational resources, it is strictly available on our Pro Plan. However, since you’ve been with us since the early days, if you upgrade this week, I’ll gladly lock you in at a 20% lifetime discount on the Pro tier.\n\nYou can claim the discounted upgrade here: [Link: Upgrade to Pro]\n\nThanks again for your continued support!\n\nBest,\n[Your Name]",
      "Subject: Need more [Resources/Seats]? Let's chat.\n\nHi [Name],\n\nJust a brief note to check in on how [Company Name] is scaling.\n\nAs you head into Q3, if you find your team constantly bumping up against the [Limit Type] restrictions on your current plan, it might be time to discuss a custom capacity increase.\n\nWe offer deeply discounted volume pricing for our high-growth clients. If expanding your usage is on the horizon, let me know and I can put together a custom package that fits your exact anticipated workflow.\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Tie the upsell directly to an immediate pain point. A 'Limit Warning' email has a drastically higher conversion rate than a generic 'Upgrade Now' blast.",
      "Offer to do the heavy lifting. Tell them 'I can toggle the trial on for you' instead of forcing them to navigate through complex billing settings.",
      "Reward loyalty. Giving long-term free users a slight, exclusive discount is a highly effective psychological catalyst for an immediate upgrade."
    ],
    faq: [
      { question: "When is the best time to attempt an upsell?", answer: "Immediately after the user experiences a major win on your platform (e.g., closing their first deal in your CRM) or right as they hit a hard usage limit." },
      { question: "Should I push annual plans during an upsell?", answer: "Yes! Offer a steep discount (e.g., '2 months free') if they upgrade to the premium tier and commit to an annual contract simultaneously." },
      { question: "What if they ignore the limit warning email?", answer: "If they hit the hard limit, the software naturally pauses their capability, which usually forces them to open the billing dashboard to upgrade without further emails." }
    ]
  },
  {
    slug: 'cold-email-saas-churn-recovery',
    title: 'SaaS Churn Recovery & Win-Back Emails',
    description: 'Bring lost customers back from the dead. Use these proven SaaS churn recovery templates to win back canceled accounts instantly.',
    intro: 'It is an inevitable reality of running a SaaS business: customers will cancel. Churn is the silent killer of compounding revenue. However, a cancellation is rarely a permanent rejection of your product. Users frequently churn because their budget temporarily tightened, they lacked the time to properly implement the software, or they encountered a minor bug that frustrated them. A masterful SaaS churn recovery (often called a "win-back") sequence can successfully reactivate up to 15% of your canceled users, recovering thousands in lost recurring revenue.\n\nThe anatomy of a brilliant churn recovery email is rooted in genuine curiosity and irresistible incentives. Do not beg them to return. The first email should strictly be a polite request for raw feedback—understanding exactly *why* they left is more valuable than winning them back. Wait 30 to 60 days to send your primary win-back pitch. By then, they may realize the competitor they switched to is actually much worse, or their budget may have reopened. At that precise moment, offer a major feature update or a highly compelling discount to drastically lower their barrier to reentry.\n\nDeploy the tested templates below to automate your churn recovery process. These scripts perfectly balance professionalism with persuasive incentives, turning lost users back into paying evangelists.',
    templates: [
      "Subject: Quick question about your cancellation\n\nHi [Name],\n\nI noticed you recently canceled your [Company Name] subscription. \n\nI’m the founder here, and I am obsessed with fixing the flaws in our product. If it isn't too much trouble, would you mind replying with a single sentence explaining why the platform ultimately didn't work out for your team?\n\nWas it missing a critical feature, too confusing to set up, or simply out of budget right now?\n\nBrutally honest feedback is the only way we improve. Thank you again for giving us a try in the first place!\n\nBest regards,\n[Your Name]",
      "Subject: We fixed the [Specific Bug/Issue]!\n\nHi [Name],\n\nWhen you left [Company Name] a few months ago, you graciously mentioned that our lack of [Specific Feature/Integration] was the primary dealbreaker.\n\nI wanted to personally reach out and let you know that our engineering team just spent the last 8 weeks entirely rebuilding that system. As of this morning, [Feature] is officially live, blazing fast, and fully integrated.\n\nBecause your feedback directly fueled this update, I’d love to welcome you back with a completely free month to test out the new systems.\n\nHere is a link to automatically reactive your account with the credit applied: [Link: Claim Free Month]\n\nHope to see you back!\n\nCheers,\n[Your Name]",
      "Subject: A quick offer to welcome you back\n\nHi [Name],\n\nIt’s been a little while since you paused your [Company Name] account, and we genuinely miss having your team on the platform.\n\nWe’ve rolled out a massive amount of new tools since you left, specifically designed to help [Industry] teams automate their workflow even faster.\n\nIf you have been considering jumping back in, I’ve activated a special welcome-back offer on your account: 50% off your next 3 months on any plan.\n\nYou can instantly claim the discount here: [Link: Claim 50% Off]\n\nLet me know if you need a quick refresher demo, I’m happy to hop on a call.\n\nBest,\n[Your Name]",
      "Subject: Is [Company Name] still a priority?\n\nHi [Name],\n\nWhen you initially signed up for [Company Name], I know streamlining your [Specific Process] was a massive priority for your Q1 goals.\n\nI completely understand that software implementations sometimes get stalled due to internal bandwidth. If this initiative is back on your radar for Q3, I’d love to make your reentry as smooth as possible.\n\nIf you reactivate this week, our customer success team will personally handle your entire data migration and initial setup completely free of charge.\n\nWould it make sense to hop on a quick 5-minute call to discuss timelines?\n\nThanks,\n[Your Name]",
      "Subject: Can I help migrate your data? [Action Required]\n\nHi [Name],\n\nJust a quick administrative note regarding your recently canceled [Company Name] account.\n\nPer our data retention policy, we will be permanently deleting your workspace and associated assets in exactly 7 days. \n\nIf you plan to return eventually and want us to securely pause and store your data instead, simply hit reply and let me know! Otherwise, no action is needed.\n\nShould you decide you want to instantly reactivate your account today to save your setup, you can do so here: [Link: Reactivate Account]\n\nAll the best,\n[Your Name]"
    ],
    tips: [
      "Send the exit-survey feedback email from the CEO or Founder's email address. People are highly likely to respond with honest feedback to the founder.",
      "Timing is everything. Send the immediate feedback email on Day 1, but wait at least 45 to 60 days before sending a deep-discount win-back email.",
      "Use loss aversion. Alerting them that their historical data will be permanently deleted is the single highest converting trigger to reactive an 'on the fence' user."
    ],
    faq: [
      { question: "Should I offer a discount immediately upon cancellation?", answer: "Yes, an automated 'Wait, stay for 30% off!' prompt inside the app during the actual cancellation flow is highly effective at saving price-sensitive users instantly." },
      { question: "What if they reply saying the product was terrible?", answer: "Thank them profusely! Critical, painful feedback from angry churned users is the exact blueprint your product team needs to fix the software." },
      { question: "How many win-back emails should I send?", answer: "Usually just two or three over a 6-month period. Anything more is borderline spam." }
    ]
  },
  {
    slug: 'cold-email-saas-enterprise-outreach',
    title: 'Enterprise SaaS Cold Email Templates',
    description: 'Close six-figure ARR deals. Master enterprise SaaS sales with these highly consultative, targeted cold email templates for C-suite executives.',
    intro: 'Selling SaaS to the Enterprise mid-market or Fortune 500 requires a fundamentally different playbook than selling to small businesses. In SMB sales, you pitch speed, affordability, and ease of use. In Enterprise sales, you are selling risk mitigation, complex integrations, deep security, and massive organizational cost reduction. Enterprise executives (CIOs, CTOs, VP of Engineering) possess highly aggressive spam filters and zero patience for generic, automated templated pitches. To capture their attention, your cold outreach must be hyper-personalized and deeply consultative.\n\nA winning Enterprise SaaS cold email does not list product features; it highlights a massive, specific inefficiency currently hiding within their organization. You must do extreme background research. Read their annual 10-K reports, listen to podcasts the executive was featured on, and monitor their recent hiring trends. Your email should immediately reference this highly specific trigger event, present a hypothesis regarding the financial pain that event is causing, and softly offer an executive summary showing how you solved this exact multi-million dollar problem for a direct competitor.\n\nLeverage the highly advanced templates below to initiate conversations with C-level targets. These scripts prioritize extreme professionalism, social proof, and completely frictionless, low-commitment calls to action.',
    templates: [
      "Subject: [Company Name]’s expansion / [Specific Process]\n\nHi [First Name],\n\nI was reviewing [Company Name]’s recent Q2 earnings report and noted your team's massive aggressive expansion into the [Specific Market/Region] sector.\n\nTypically, when organizations scale this rapidly, managing the immense data load across legacy [Specific System] environments rapidly becomes a profound bottleneck, often increasing infrastructure costs by upwards of 40%.\n\nWe recently partnered with [Their Direct Competitor or Similar Giant] to completely overhaul this exact infrastructure, resulting in a documented $2.4M reduction in annual operating expenses within identical compliance frameworks.\n\nI have a brief 2-page executive summary detailing the exact migration architecture we utilized for them. \n\nAre you open to reviewing it if I send it over?\n\nBest regards,\n[Your Name]",
      "Subject: Quick question regarding your [Specific Department] org structure\n\nHi [Name],\n\nI noticed the recent wave of engineering hires [Company Name] has made over the last 6 months specifically focused on [Specific Technical Area].\n\nAs technical teams swell past the 500+ mark, I frequently see VPs facing crippling inefficiencies regarding [Specific Pain Point, e.g., cross-departmental secure access].\n\nMy team built a specific enterprise-grade automation platform that integrates natively with your existing [Software/Tech Stack] architecture to eliminate this friction entirely. We currently handle this securely for [Massive Brand] and [Massive Brand].\n\nIs standardizing this process a priority for your leadership team this fiscal year?\n\nBest,\n[Your Name]",
      "Subject: Idea for [Their Given Name or Company Name Initiative]\n\nHi [Name],\n\nI thoroughly enjoyed your recent interview on the [Podcast Name] podcast. Your specific point regarding the unforeseen security challenges of rolling out [Specific Tech] to a remote workforce was incredibly insightful.\n\nBecause you are clearly heavily focused on risk-mitigation right now, I hypothesize your team might be struggling with [Highly Specific Niche Problem]. \n\nOur platform, [Your Software], was engineered from the ground up to solve that precise vulnerability, fully compliant with SOC2 and HIPAA standards.\n\nIf it makes sense, I’d love to coordinate a brief 15-minute high-level technical overview with your Director of [Department]. \n\nShould I route that request to you initially, or directly to [Name of their subordinate]?\n\nSincerely,\n[Your Name]",
      "Subject: Re: Follow up on [Specific Pain Point]\n\nHi [Name],\n\nI know enterprise architecture overhauls are massive, multi-quarter initiatives, so I will keep this extremely brief.\n\nAre you still actively exploring solutions to modernize your [Process] workflow, or has the board tabled this initiative for the remainder of the year?\n\nA quick 'Yes' or 'No' is absolutely all I need.\n\nBest,\n[Your Name]"
    ],
    tips: [
      "Drop massive names. In enterprise sales, 'Nobody ever got fired for buying IBM.' You must extensively name-drop your biggest, most recognizable clients to instantly establish trust and reduce perceived risk.",
      "Ask permission to share material. Asking 'Can I send over the 2-page summary?' drastically increases reply rates compared to aggressively demanding a 45-minute demo immediately.",
      "Target the direct reports. Sometimes pitching the VP is too high. Pitch the 'Director of [Department]' and map the account upwards."
    ],
    faq: [
      { question: "How long is an enterprise SaaS sales cycle?", answer: "Typically 6 to 18 months. Patience, multithreading (talking to multiple executives at once), and rigorous follow-up are absolutely mandatory." },
      { question: "Should I attach PDFs to cold enterprise emails?", answer: "No. High-level corporate firewalls will automatically quarantine cold emails containing attachments. Ask permission first, then attach it in the reply." },
      { question: "Is security important to mention?", answer: "It is the only thing that matters. You must explicitly mention 'Enterprise-grade', 'SOC2 Compliant', or 'SSO integration' to prove you are a serious vendor." }
    ]
  },
  {
    slug: 'second-follow-up-after-proposal-no-response',
    title: 'Second Follow-Up Email After Sending a Proposal',
    description: 'Close the deal. Use these professional second follow-up email templates when a client ignores your business proposal or quote.',
    intro: 'You spent hours carefully crafting a detailed scope of work, precisely pricing your services, and submitting a beautiful business proposal. You sent your first polite follow-up a few days later—and still received total silence. Do not panic, and absolutely do not aggressively demand an answer. A second follow-up after a proposal requires extreme nuance. The prospect is likely experiencing internal friction: the budget wasn\'t fully approved, they are scared to pull the trigger, or the key decision-maker went on vacation.\n\nYour second follow-up must elegantly pivot from "checking in" to "removing friction." Assume the price or the complexity of the scope is causing their hesitation. Use this touchpoint to gently offer flexibility. Ask if they need the proposal broken down into smaller, phased deliverables, or if they need specific case studies to present to their CFO. The goal is to let them know that the proposal is a living document, not a rigid ultimatum, making it psychologically safe for them to reply and voice their concerns.\n\nUse the customized scripts below to expertly nudge cold proposals. These templates apply slight urgency regarding your team\'s availability while keeping the tone incredibly supportive and consultative, maximizing your chances of signing the contract.',
    templates: [
      "Subject: Re: Proposal for [Project Name]\n\nHi [Client Name],\n\nHope you are having a fantastic week.\n\nI wanted to circle back on the proposal I submitted last week for the [Project Name] initiative. Since I know these larger [Service Type] scopes can sometimes raise questions internally, I wanted to see if you or your team needed any further clarification on the deliverables?\n\nIf the initial scope is slightly too aggressive for your Q3 budget, please let me know. I am completely open to phasing the project out into smaller chunks so we can immediately get started on the highest-priority items first.\n\nLet me know your thoughts!\n\nBest regards,\n[Your Name]",
      "Subject: Re: [Company Name] Quote - Timeline check\n\nHi [Client Name],\n\nJust floating this quote back to the top of your inbox.\n\nI am currently finalizing my team's resourcing schedule for next month. Because I absolutely want to ensure we have dedicated bandwidth mapped out for [Company Name], could you let me know if you are still planning to launch this project in [Month]?\n\nIf the timeline has shifted internally, totally understood—just let me know roughly when I should reach back out.\n\nCheers,\n[Your Name]",
      "Subject: Re: Next Steps for [Project Name]\n\nHi [Client Name],\n\nFollowing up on my note from earlier this week.\n\nOften when things go quiet at this stage, it means the leadership team is requiring a bit more hard data before signing off on the budget.\n\nTo help make your internal pitch easier, I’ve attached a brief 1-page PDF highlighting the exact ROI metrics we delivered for [Similar Company in their industry] when we executed this exact same project for them last year.\n\nI’ll hold off on reaching out further, but please let me know if you’d like to hop on a quick 5-minute call to review the numbers!\n\nBest,\n[Your Name]",
      "Subject: Re: [Project Name] Proposal\n\nHi [Client Name],\n\nI know how quickly things can pile up on the desk, so I will keep this extremely brief.\n\nAre you still actively reviewing the [Project Name] proposal, or has this initiative been put on hold for the remainder of the quarter?\n\nA quick reply of 'yes' or 'no' is all I need, zero pressure either way!\n\nThanks,\n[Your Name]"
    ],
    tips: [
      "Create scarcity. Mentioning 'I am finalizing my team's bandwidth for the month' reminds them that your availability is not infinite, subtly forcing an answer.",
      "Offer to modify the scope. The #1 unspoken reason proposals are ignored is sticker shock. Explicitly stating you can adjust the scope to fit their budget opens the door to negotiation instead of ghosting.",
      "Always reply in your original email thread so they can instantly open and review the original attached PDF proposal."
    ],
    faq: [
      { question: "How long should I wait before sending the second follow-up?", answer: "Wait roughly 4 to 5 business days after your *first* follow-up. Do not email them every single day." },
      { question: "Is this the 'break up' email?", answer: "It can be, but usually, a final third 'Break Up' email is sent a week later politely stating you are closing the file." },
      { question: "Should I lower the price in the second follow up?", answer: "Never blindly discount. Offer to 'phase the project' or 'adjust the scope'. This maintains your value while lowering the total immediate cost." }
    ]
  }
];

const out = [...data, ...newTemplates];
fs.writeFileSync(file, JSON.stringify(out, null, 2));
