const fs = require('fs');
const file = 'src/data/templates.json';
const data = JSON.parse(fs.readFileSync(file, 'utf-8'));

const newTemplates = [
  {
    slug: 'linkedin-recruiter-follow-up-message',
    title: 'LinkedIn Recruiter Follow-Up Messages',
    description: 'Keep the conversation going. Master the art of the LinkedIn recruiter follow-up message to secure your next interview.',
    intro: 'Following up with a recruiter on LinkedIn after an initial screen, a final interview, or simply after sending your resume requires extreme tact. Recruiters represent the gatekeepers to your target company; managing an enormous pipeline of candidates daily means they frequently fall behind schedule. A pushy, demanding LinkedIn direct message will rapidly relegate your application to the "No" pile. Conversely, a highly professional, polite nudge demonstrates excellent communication skills and intense interest in the role.\n\nThe perfect LinkedIn follow-up message to a recruiter must be brief, gracious, and empathetic to their heavy workload. Start by explicitly referencing your previous interaction—whether it was a phone screen last Tuesday or simply an application you filed yesterday. Briefly reiterate exactly why your core experience aligns with their open position, providing a single, specific metric or skill as proof. Conclude by respectfully asking for a timeline update without demanding an immediate decision.\n\nUse the customized LinkedIn DM and InMail templates below to gracefully follow up with recruiters across various stages of the hiring pipeline. These proven scripts help ensure your name remains top-of-mind without seeming desperate.',
    templates: [
      "Subject: Following up: [Your Name] for [Job Title]\n\nHi [Recruiter's Name],\n\nI hope your week is off to a great start!\n\nI’m reaching out to follow up on my application for the [Job Title] role. Since we connected last [Day/Week], I’ve been researching [Company Name]’s recent pivot into [Specific Strategy/Market], which makes me even more excited about the opportunity.\n\nGiven my 5+ years of experience leading similar [Specific Skill] initiatives at [Previous Company], I strongly believe my background closely aligns with the team's Q3 goals.\n\nCould you kindly let me know if there is an updated timeline regarding next steps in the interview process?\n\nBest regards,\n[Your Name]",
      "Subject: Checking in - [Job Title] role\n\nHi [Recruiter Name],\n\nHope all is well.\n\nI completely understand how busy your pipeline must be right now! I simply wanted to check in regarding the [Job Title] position we discussed during our phone screen last Tuesday.\n\nI remain highly interested in joining the team and helping scale the [Specific Department]. \n\nPlease let me know if the hiring manager requires any additional references or work samples from me to make their decision. Looking forward to hearing from you!\n\nBest,\n[Your Name]",
      "Subject: Re: [Your Name] / [Job Title] candidacy\n\nHi [Recruiter's Name],\n\nI am writing to provide a quick update on my end regarding the [Job Title] position.\n\nI remain incredibly passionate about the opportunity to join [Company Name], specifically because of the amazing culture you described during our last call.\n\nHowever, I recently advanced to the final stage with another organization. Because [Company Name] remains my absolute top choice, I wanted to respectfully check in on your timeline to see if we might be able to coordinate final next steps before [Deadline Date].\n\nHope to connect soon,\n[Your Name]",
      "Subject: Great speaking with you today! \n\nHi [Recruiter Name],\n\nThank you so much for taking the time to speak with me today about the [Job Title] role. \n\nLearning more about the team's immediate focus on [Specific Challenge] solidified my interest in the position. As discussed, I successfully managed a similar transition at [Previous Company], resulting in a [Huge Tangible Metric].\n\nI’ve attached my updated portfolio here for your reference. I look forward to hearing about the next steps by the end of the week!\n\nCheers,\n[Your Name]"
    ],
    tips: [
      "Wait at least 48 hours after their promised deadline before gently checking in.",
      "LinkedIn DMs do not require formal 'Dear Sir' greetings; keep the tone professional but slightly conversational.",
      "If you have a competing offer, transparently stating your deadline is the best way to force an immediate timeline update."
    ],
    faq: [
      { question: "Should I message the recruiter or email them?", answer: "Reply using whatever platform they used to contact you last. If they scheduled the call via email, reply to that email thread. If they reached out via LinkedIn InMail, reply there." },
      { question: "What if the recruiter ignores my follow-up?", answer: "Recruiters are often waiting on hiring managers. Wait another full week, send one final polite message. If there is still no response, assume the role was filled." },
      { question: "Is it okay to connect with the recruiter after applying?", answer: "Yes. Sending a customized connection request ('Hi [Name], I just applied for the [Role] and would love to stay connected regarding future opportunities') is highly proactive." }
    ]
  },
  {
    slug: 'linkedin-cold-outreach-for-business-partnerships',
    title: 'LinkedIn Cold Outreach for Business Partnerships',
    description: 'Forge powerful B2B alliances. Use these LinkedIn cold outreach templates to secure lucrative business partnerships and co-marketing deals.',
    intro: 'Securing a strategic B2B partnership or co-marketing agreement can immediately unlock a massive new audience for your business without the hefty customer acquisition costs associated with paid ads. However, executives guarding these audiences receive dozens of "partnership" requests weekly that are thinly veiled sales pitches. To successfully secure a highly leveraged business partnership on LinkedIn, your cold outreach must clearly, instantly articulate the mutual benefit (the "What\'s In It For Me" or WIIFM).\n\nA brilliant partnership pitch focuses entirely on synergy and audience overlap. Do not begin by talking extensively about your own product\'s features. Instead, compliment their recent work, identify that both of your companies target the exact same customer persona (e.g., "e-commerce founders doing $1M+ ARR"), and propose a straightforward, low-lift collaboration—such as a co-hosted webinar, a guest newsletter take-over, or a native software integration. Your goal is to drastically lower the perceived risk and effort required on their end.\n\nUse the tested LinkedIn InMail and Connection Request templates below to initiate these high-value conversations. Because LinkedIn constraints require brevity, these scripts prioritize impactful metrics, explicit synergy, and an incredibly frictionless call to action.',
    templates: [
      "Subject: Partnership idea: [Your Company] + [Their Company]\n\nHi [Name],\n\nI’ve been following [Company Name]’s recent growth and absolutely love the new [Feature/Product] you launched last month. \n\nI am the [Title] at [Your Company]. Since we both strictly serve [Target Audience Persona, e.g., B2B SaaS Founders], I believe there is a massive opportunity for a mutually beneficial co-marketing partnership this quarter.\n\nWe currently have an active email list of [Number] highly engaged founders. I would love to explore hosting a joint [Webinar/Co-authored E-book] to cross-pollinate our audiences and drive incredibly low-CAC leads for both of our sales teams.\n\nAre you open to a brief 10-minute exploratory chat next Tuesday?\n\nBest,\n[Your Name]",
      "Subject: Quick idea regarding a native integration\n\nHi [Name],\n\nAs a massive fan of [Company Name], I wanted to reach out directly.\n\nMy team at [Your Company] provides [Specific Service/Software] to over [Number] clients in the [Industry] space. The number one request we consistently receive is 'Does this integrate seamlessly with [Company Name]?'\n\nI strongly believe formally integrating our platforms could drastically increase retention for both of our user bases by solving [Shared Pain Point].\n\nIf exploring strategic product partnerships is a priority for you right now, I’d love to show you a quick 3-minute mockup of how this could work.\n\nCheers,\n[Your Name]",
      "Subject: Connection Request (Note)\n\nHi [Name],\n\nSince [Company A] and [Company B] both cater heavily to [Target Audience], I’d love to connect. We’re currently looking for trusted partners in the [Niche] space to refer our excess inbound leads to.\n\nWould be great to network and explore potential synergies down the line. Keep up the great work!\n\nBest,\n[Your Name]",
      "Subject: Idea for a Guest Masterclass with [Company Name]\n\nHi [Name],\n\nI absolutely loved your recent LinkedIn post outlining [Specific Topic]. Your framework for [Specific Detail] is brilliant.\n\nWe host a monthly Masterclass for our community of [Number] [Target Audience, e.g., real estate agents]. I would be honored to have you or a member of your leadership team come on as a guest expert to teach that exact framework.\n\nIt’s a great, low-lift opportunity to organically pitch [Company Name]’s services to a highly engaged, vetted audience.\n\nLet me know if this sounds interesting and I can send over the details!\n\nBest regards,\n[Your Name]"
    ],
    tips: [
      "Quantify your audience size (e.g., 'an active list of 10,000 developers') to instantly prove you bring tangible value to the partnership.",
      "Pitch a specific, low-friction idea (like a webinar or a blog swap) rather than a vague 'Let's partner'.",
      "Ensure your own LinkedIn profile is optimized and looks deeply professional before sending high-level partnership pitches."
    ],
    faq: [
      { question: "What makes a 'good' partnership?", answer: "The golden rule is audience overlap without direct competition. You should target the exact same customer persona, but sell entirely different, complementary products." },
      { question: "Who handles partnerships at a large company?", answer: "Look for titles like 'Director of Strategic Partnerships', 'Head of Business Development', or 'VP of Marketing'." },
      { question: "Should I ask for a referral fee immediately?", answer: "No. Focus on audience cross-pollination first. Once trust is established, negotiate formal affiliate structures or revenue shares." }
    ]
  },
  {
    slug: 'thank-you-email-after-job-rejection',
    title: 'Thank You Email After Job Rejection Templates',
    description: 'Keep the door open. Learn exactly how to write a classy thank you email after a job rejection to secure future opportunities.',
    intro: 'Receiving a job rejection email after numerous rounds of interviews is incredibly demoralizing. The instinct is to immediately delete the email and move on. However, sending a professional, gracious "thank you" email after a rejection is a masterclass in emotional intelligence and long-term networking. Hiring managers frequently keep the resumes of stellar "runner-up" candidates; when their first-choice candidate declines the offer or suddenly quits three months later, the runner-up who sent a classy thank you email is the very first person they call.\n\nA brilliant post-rejection email serves three distinct purposes. First, it graciously thanks the hiring team for their time, proving extremely high character. Second, it briefly reiterates your continued passion for the company\'s mission. Third, it clearly asks them to keep your resume on file for future openings within that specific department. By maintaining a supremely professional tone despite the disappointment, you transition from a rejected applicant into a highly valued connection within the hiring manager’s network.\n\nUse the templates below to strategically respond to a rejection. These customized emails will help you leave a lasting, positive impression, keeping the door wide open for future roles, freelance projects, or referrals.',
    templates: [
      "Subject: Re: [Job Title] role - [Your Name]\n\nHi [Hiring Manager's Name],\n\nThank you so much for getting back to me and letting me know about your decision.\n\nWhile I am naturally disappointed I won’t be joining the team at this time, I truly appreciate the opportunity to interview for the [Job Title] position. I thoroughly enjoyed our conversations regarding [Specific Project or Topic], and the process only reinforced my deep admiration for [Company Name]’s mission.\n\nI would love to stay connected as you continue to scale the [Department Name] team. Please keep my resume on file for any future opportunities where my background in [Skill A] and [Skill B] might be a strong fit.\n\nWishing you and the entire team the absolute best with the upcoming Q3 product launch.\n\nBest regards,\n[Your Name]",
      "Subject: Thank you and keeping in touch / [Your Name]\n\nHi [Recruiter's Name],\n\nThank you for the update. While I am certainly bummed to hear the news, I genuinely appreciate your transparency and the incredibly smooth interview process you facilitated.\n\nI remain incredibly passionate about the work [Company Name] is doing in the [Industry] space. If a similar [Job Title/Department] position opens up in the future, I would be thrilled to be considered again.\n\nThank you again for your time, and I wish the team great success moving forward.\n\nCheers,\n[Your Name]",
      "Subject: Re: [Job Title] update\n\nHi [Hiring Manager Name],\n\nThank you for reaching out to let me know the team’s decision.\n\nIt was a privilege to learn more about the incredible culture you’ve built at [Company Name]. I especially appreciated your insights on [Specific Challenge discussed in interview]—it gave me a lot to think about regarding my own career growth in [Industry].\n\nI’ve sent you a connection request on LinkedIn. I look forward to following the team's continued success, and I hope our paths cross again in the future!\n\nWarmly,\n[Your Name]"
    ],
    tips: [
      "Reply within 24 hours while your candidacy is still fresh in their minds.",
      "Send a connection request to the hiring manager on LinkedIn immediately after sending the email.",
      "Keep it genuinely polite; absolutely no passive-aggression or demands to know exactly why you were rejected."
    ],
    faq: [
      { question: "Should I ask for feedback in this email?", answer: "You can, but it is often better to ask in a separate 'Feedback Request' email or combine it very softly: 'If you have a brief moment to share any feedback on areas I could improve, I would greatly appreciate it.'" },
      { question: "Do runner-ups really get hired later?", answer: "Absolutely. The #1 candidate often falls through during salary negotiations or quits rapidly. Hiring managers hate re-opening job reqs; they prefer to call the polite runner-up immediately." },
      { question: "Who should receive the email?", answer: "Reply directly to the person who delivered the rejection (usually HR), but explicitly ask them to pass your gratitude along to the specific Hiring Manager." }
    ]
  },
  {
    slug: 'email-asking-for-feedback-after-interview',
    title: 'How to Ask for Feedback After an Interview (Templates)',
    description: 'Turn a "No" into a growth opportunity. Use these polite, professional email templates to ask for actionable feedback after a job rejection.',
    intro: 'Asking for feedback following a job rejection is one of the most proactive steps you can take to accelerate your career growth. While many companies possess strict HR policies against providing detailed interview feedback (to avoid potential liability), hiring managers will occasionally share invaluable, candid critique if your request is remarkably humble and professional. This feedback can highlight a blind spot in your interview presence or a specific technical gap you need to close before applying for your next role.\n\nThe key to a successful feedback request is removing all pressure. The hiring manager must know that you are not attempting to argue with their decision or litigate your rejection. State clearly that you accept their decision fully, and explicitly note that you are asking purely for your own professional development. Ask for one or two highly specific bullet points rather than a comprehensive performance review. Make it as easy as possible for them to reply safely and quickly.\n\nBelow are customized templates designed to extract constructive criticism gracefully. Whether you are asking the internal recruiter or the direct hiring manager, these scripts maximize your chances of receiving actionable advice while cementing your reputation as a dedicated professional.',
    templates: [
      "Subject: Re: Update on the [Job Title] role\n\nHi [Hiring Manager's Name],\n\nThank you again for letting me know about your final decision regarding the [Job Title] role. I truly appreciate your transparency and the time your team spent with me.\n\nSince I am constantly looking for ways to improve my professional skill set, I was hoping to ask a brief favor. If you have 2 minutes to spare, I would immensely appreciate any brief, candid feedback regarding my interview performance or any specific gaps in my [Skillset, e.g., technical background] compared to the successful candidate.\n\nI completely accept your decision and am strictly looking for constructive critique to help my continued career growth.\n\nThank you again for your time and leadership.\n\nBest regards,\n[Your Name]",
      "Subject: Re: [Job Title] Application Feedback\n\nHi [Recruiter's Name],\n\nThank you for providing the update. While disappointed, I genuinely enjoyed the rigorous interview process and remain a massive fan of [Company Name].\n\nAs I continue my job search within the [Industry] sector, I would love to ask if the hiring team shared any specific feedback regarding where my candidacy fell short.\n\nWhether it was a lack of experience in [Software] or simply a culture fit, any brief pointers you could share would be incredibly valuable for my future interviews.\n\nThank you so much for your guidance throughout this entire process.\n\nBest,\n[Your Name]",
      "Subject: Gathering feedback / [Your Name]\n\nHi [Interviewer's Name],\n\nThank you for the update on the [Job Title] position.\n\nI am currently looking to aggressively upskill in [Industry Field] over the next six months. Because I deeply respect your technical expertise in this area, your objective feedback would mean the world to me.\n\nIf you have a brief moment, could you share one or two areas where you felt my technical assessment could have been stronger?\n\nI completely understand if company policy prevents you from sharing specifics. Regardless, I wish you and the team a fantastic rest of the year.\n\nCheers,\n[Your Name]"
    ],
    tips: [
      "State explicitly that you accept their decision. This lowers their defense mechanism and makes them feel safe providing critique.",
      "Ask a specific question (e.g., 'Was my technical presentation lacking?'). Generic questions yield generic corporate answers.",
      "Never respond defensively. If they provide critique, reply only with a sincere 'Thank you so much for this insight'."
    ],
    faq: [
      { question: "Why do companies often refuse to give feedback?", answer: "Many corporate HR departments expressly forbid hiring managers from giving feedback to avoid any risk of discrimination lawsuits if the candidate misinterprets the critique." },
      { question: "Should I ask for a phone call to get feedback?", answer: "No. Asking for a call is a massive time commitment. Allow them to send two quick bullet points asynchronously via email." },
      { question: "Is it worth asking if I didn't make it past the first round?", answer: "Usually not. First-round rejections are often purely based on resume metrics. Only ask for feedback if you completed later-stage, intensive interviews." }
    ]
  },
  {
    slug: 'asking-for-a-referral-email-to-hiring-manager',
    title: 'Asking for a Job Referral Email Templates',
    description: 'Bypass the resume black hole. Learn how to ask a connection for a job referral or an introduction to the hiring manager with these templates.',
    intro: 'Employee referrals are the single highest-converting source of hires for virtually every major corporation. Applying through the standard online portal means competing against hundreds, sometimes thousands, of applicants. An internal referral guarantees your resume skips the initial automated ATS screening and lands directly on the recruiter’s desk. However, asking a professional connection to vouch for you is a significant request; they are putting their own internal reputation on the line.\n\nWhen writing an email to ask for a referral, your primary objective is to make the process completely frictionless for your contact. Do not ask them "Hey, are there any jobs open at your company?" You must do the heavy lifting beforehand. Identify the exact open job requisition ID, write a brief paragraph outlining exactly why you are hyper-qualified, and attach your polished resume. By providing them with a "forwardable email," they simply click forward, add a quick "Hey HR, see my friend below," and the referral is complete.\n\nThe customized templates below cover various referral scenarios, from asking a close former colleague to requesting a referral from a loose LinkedIn acquaintance. Use them to dramatically increase your interview rate and access the hidden job market.',
    templates: [
      "Subject: Quick question regarding the [Job Title] role at [Company Name]\n\nHi [Connection's Name],\n\nI hope you’re having a great week! I saw the recent news about [Company Name]'s Series B—huge congratulations to the team.\n\nI’m reaching out because I noticed your team just opened a requisition for a [Job Title] (Req ID: #1234). I actually successfully managed a very similar [Specific Project] during my time at [Previous Company], and I strongly believe my deep expertise in [Skill] makes me a perfect fit for this role.\n\nWould you be comfortable submitting my resume as an internal referral for this position, or connecting me directly with the hiring manager?\n\nI’ve attached my updated resume and a brief 'forwardable' paragraph below to make it as easy as possible. Absolutely no pressure at all if you aren't comfortable doing so!\n\nBest,\n[Your Name]",
      "Subject: Forwardable: [Your Name] for [Job Title] role\n\nHi [Contact's Name],\n\nHope everything is going great over in the [Department]!\n\nAs we’ve discussed previously, I’m actively looking to transition into a [Target Role] position, and [Company Name] is at the absolute top of my list. I saw the [Job Title] role was just posted today.\n\nIf you believe I’d be a strong cultural add to the team, would you be open to passing my resume along to the recruiting team? \n\nI pasted a brief blurb below you can easily forward. Let me know if you need any other info from me. I really appreciate your support!\n\nCheers,\n[Your Name]\n\n---\nFORWARDABLE BLURB:\nHi Team,\nI’d love to refer my former colleague, [Your Name], for the [Job Title] role. They have 5+ years of experience in [Skill] and recently led [Specific Massive Win]. I loved working with them and strongly believe they’d be a massive asset to our team. I’ve attached their resume for review.",
      "Subject: Connecting regarding an open role at [Company Name]\n\nHi [Name],\n\nIt’s been great following your career since our time together at [Previous Company]!\n\nI’m reaching out because I am preparing to apply for the [Open Role] at [Company Name]. Since you know my work ethic firsthand from our time collaborating on the [Project Name], I was hoping you might be willing to act as an internal referral for me.\n\nWould you be open to a quick 5-minute chat next week to discuss what the hiring manager is primarily looking for in this role?\n\nHope to catch up soon!\n\nWarmly,\n[Your Name]"
    ],
    tips: [
      "Always provide a 'Forwardable Blurb'. This allows the employee to refer you in 30 seconds rather than having to draft an email themselves.",
      "Include the exact Job Link and the Requisition ID number so HR knows exactly which role you are applying for.",
      "Offer an 'out'. Saying 'No pressure if you don't feel comfortable' preserves the relationship if they decline."
    ],
    faq: [
      { question: "Should I apply online first or ask for the referral first?", answer: "Usually, ask for the referral first. Many companies have an internal portal where the employee must submit your resume before you formally apply so they get their referral bonus." },
      { question: "Is it okay to ask for a referral from someone I barely know?", answer: "It is high-risk. Employees are staking their internal reputation on you. It is better to ask them for an 'informational interview' first to build trust." },
      { question: "How much is an employee referral bonus?", answer: "Many tech and corporate companies pay employees $1,000 to $5,000 for successful engineering or senior hires, meaning they are financially motivated to refer strong candidates." }
    ]
  }
];

const out = [...data, ...newTemplates];
fs.writeFileSync(file, JSON.stringify(out, null, 2));
